//! The public query surface: `registry`, `support`, and the coverage report.

use super::tables::{CPU_CAPABILITIES, CUDA_CAPABILITIES, METAL_CAPABILITIES, WGPU_CAPABILITIES};
use incin_core::exec::{
    Capabilities, CapabilityQuery, CapabilityRegistry, CapabilityRule, OPERATION_CATALOG,
    SupportLevel,
};
use incin_core::shapes::error::OperationKind;
use incin_core::tensor::device::DeviceKind;

static EMPTY_CAPABILITIES: &[CapabilityRule] = &[];

#[must_use]
pub fn registry(device: DeviceKind) -> CapabilityRegistry {
    let rules = match device {
        DeviceKind::Cpu => CPU_CAPABILITIES,
        DeviceKind::Cuda => CUDA_CAPABILITIES,
        DeviceKind::Wgpu => WGPU_CAPABILITIES,
        DeviceKind::Metal => METAL_CAPABILITIES,
        _ => EMPTY_CAPABILITIES,
    };
    CapabilityRegistry::new(rules)
}

#[must_use]
pub fn support(device: DeviceKind, query: &CapabilityQuery) -> SupportLevel {
    registry(device).support(query)
}

/// Exact support decisions generated by joining backend declarations to the
/// canonical operation catalog. A zero count is an explicit unsupported or
/// migration-blocked decision, never an omitted row.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BackendCoverageRow {
    pub operation: OperationKind,
    pub cpu_rules: usize,
    pub cuda_rules: usize,
    pub wgpu_rules: usize,
    pub metal_rules: usize,
}

#[must_use]
pub fn coverage_report() -> alloc::vec::Vec<BackendCoverageRow> {
    OPERATION_CATALOG
        .iter()
        .map(|entry| BackendCoverageRow {
            operation: entry.operation,
            cpu_rules: CPU_CAPABILITIES
                .iter()
                .filter(|rule| rule.operation == entry.operation)
                .count(),
            cuda_rules: CUDA_CAPABILITIES
                .iter()
                .filter(|rule| rule.operation == entry.operation)
                .count(),
            wgpu_rules: WGPU_CAPABILITIES
                .iter()
                .filter(|rule| rule.operation == entry.operation)
                .count(),
            metal_rules: METAL_CAPABILITIES
                .iter()
                .filter(|rule| rule.operation == entry.operation)
                .count(),
        })
        .collect()
}
