[package]
name = "kindle-native"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
kindle-core = { path = "../kindle-core" }
rand = "0.8"
rand_distr = "0.4"
half = { workspace = true }
bytemuck = { version = "1.25", features = ["derive"] }
anyhow = "1.0.103"

[dev-dependencies]
kindle-backends = { path = "../kindle-backends", features = ["candle"] }

[lints]
workspace = true
