version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - area:release
      - type:maintenance

  - package-ecosystem: npm
    directory: /editors/vscode
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - area:editor
      - type:maintenance

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - area:release
      - type:maintenance
