[workspace]
resolver = "2"

members = [
    "crates/incin",
    "crates/incin-backends",
    "crates/incin-core",
    "crates/incin-diagnostics",
    "crates/incin-lsp",
    "crates/incin-data",
    "crates/incin-macros",
    "crates/incin-telemetry",
    "crates/incin-viz-plugin-api",
    "crates/incin-viz",
    "crates/incin/examples/*",
    "crates/incin-core/examples/*"
]

exclude = []

[workspace.package]
edition = "2024"
version = "0.0.0"
readme = "README.md"
license = "MIT OR Apache-2.0"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"
[workspace.dependencies]
proc-macro2 = { version = "1.0.106", default-features = false }
syn = { version = "2.0.118", features = ["full"] }
quote = { version = "1.0.46", default-features = false }
candle-core = { version = "0.9.1", default-features = false }
candle-nn = { version = "0.9.1", default-features = false }
thiserror = { version = "2.0.18", default-features = false }
half = { version = "2.7.1", default-features = false }
# miette = "7.6.0"
[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"
