[package]
name = "kindle-wgpu"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
kindle-core = { path = "../kindle-core", default-features = false }
wgpu = "22.0.0"
pollster = "0.3.0"
bytemuck = { version = "1.16.1", features = ["derive"] }
log = "0.4.22"
spin = { version = "0.9.8", default-features = false, features = ["mutex"] }
anyhow = { version = "1.0.86", default-features = false }

[lints]
workspace = true

[features]
default = ["std"]
std = ["kindle-core/std", "anyhow/std"]
