//! The support tables in `docs/capabilities.md`, rendered from the
//! registrations in [`crate::capability`].
//!
//! `PROPOSALS.md` §2.10 states this one as a prohibition rather than a feature:
//! "Do not maintain independent handwritten support tables that can drift from
//! code." A generated table can still drift — it drifts the moment someone edits
//! a rule and forgets to regenerate — so the generated text is checked in and
//! `tests/generated_docs.rs` fails when the checked-in copy and this renderer
//! disagree. Regenerate with `INCIN_DOCS=overwrite`.
//!
//! Everything here is a pure function of `&[CapabilityRule]`, which is what
//! makes the tables testable without a machine that has the hardware: the
//! registrations are static data compiled into every build, so this renders the
//! CUDA table on a laptop with no GPU.

use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::fmt::Write as _;

use incin_core::exec::{CapabilityRule, OPERATION_CATALOG};
use incin_core::prelude::{DeviceKind, MAX_RANK};

use crate::capability::{CPU_CAPABILITIES, CUDA_CAPABILITIES, WGPU_CAPABILITIES};

/// The devices the document covers, in the order it prints them.
const DEVICES: &[(DeviceKind, &[CapabilityRule])] = &[
    (DeviceKind::Cpu, CPU_CAPABILITIES),
    (DeviceKind::Cuda, CUDA_CAPABILITIES),
    (DeviceKind::Wgpu, WGPU_CAPABILITIES),
];

/// The complete text of `docs/capabilities.md`.
#[must_use]
pub fn document() -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(&summary(DEVICES));
    for &(device, rules) in DEVICES {
        out.push_str(&device_section(device, rules));
    }
    out.push_str(&legend());
    out
}

const HEADER: &str = "\
# Backend capability matrix

<!--
Generated by `incin_backends::capability_docs` from the registrations in
`crates/incin-backends/src/capability.rs`. Do not edit by hand: run
`INCIN_DOCS=overwrite cargo test -p incin-backends --test generated_docs`.

A row here is a rule a backend registered, not a claim about a machine. It says
what this build of Incin would run if the device were present; `cargo incin
doctor` reports whether it is. `EXE-005`'s `capability_matrix` suite is what
makes the two agree — it executes the boundary cases of every rule below.
-->

`PROPOSALS.md` §2.10 requires that support tables be generated from the
capability registrations rather than maintained beside them. These are those
registrations.

A backend advertises an operation for a set of element types, memory layouts and
ranks. Anything it does not advertise is unsupported, and is reported as such by
the capability registry rather than by a trait method that returns an error at
run time.

";

/// One catalog operation per row and one backend per column. The cell contains
/// only dtypes established by that backend's executable declaration; a dash is
/// an explicit absence, never a family-level inference.
fn summary(devices: &[(DeviceKind, &[CapabilityRule])]) -> String {
    // The catalog, not a union of backend tables, defines the rows. This makes
    // absence visible and makes adding an operation without a support decision
    // change the generated document immediately.
    let mut operations: Vec<_> = OPERATION_CATALOG.iter().map(|row| row.operation).collect();
    operations.sort_unstable_by_key(|op| op.name());

    let mut out = String::from("## Element types by operation and backend\n\n| Operation |");
    for &(device, _) in devices {
        let _ = write!(out, " {} |", device.name());
    }
    out.push_str("\n|---|");
    for _ in devices {
        out.push_str("---|");
    }
    out.push('\n');

    for operation in operations {
        let _ = write!(out, "| `{}` |", operation.name());
        for &(_, rules) in devices {
            // The union across rules, because an operation can be registered
            // more than once for one device — CPU registers `reshape` four
            // times, splitting on layout and on whether training is covered.
            let mut dtypes = Vec::new();
            for rule in rules.iter().filter(|rule| rule.operation == operation) {
                for &dtype in rule.dtypes {
                    if !dtypes.contains(&dtype) {
                        dtypes.push(dtype);
                    }
                }
            }
            if dtypes.is_empty() {
                out.push_str(" — |");
            } else {
                let _ = write!(out, " {} |", join(dtypes.iter().map(|d| code(d.name()))));
            }
        }
        out.push('\n');
    }
    out.push_str(
        "\nEvery stable semantic operation comes from the canonical catalog. A dash is an explicit unsupported or migration-blocked decision. Layout, rank and training coverage are in the per-backend tables below.\n\n",
    );
    out
}

/// The full registration list for one device, one row per rule.
fn device_section(device: DeviceKind, rules: &[CapabilityRule]) -> String {
    let mut out = String::new();
    let _ = write!(out, "## `{}`\n\n", device.name());
    if rules.is_empty() {
        out.push_str("No registrations.\n\n");
        return out;
    }
    out.push_str("| Operation | Element types | Layouts | Rank | Training | Implementation |\n");
    out.push_str("|---|---|---|---|:--:|---|\n");
    for rule in rules {
        let dtypes = join(rule.dtypes.iter().map(|d| code(d.name())));
        let layouts = join(rule.layouts.iter().map(|l| code(l.as_str())));
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {} |",
            rule.operation.name(),
            dtypes,
            layouts,
            rank_range(rule),
            if rule.training { "yes" } else { "no" },
            rule.implementation.name(),
        );
    }
    out.push('\n');
    out
}

/// A rule's rank bound, written the way a reader would say it.
///
/// `0..=MAX_RANK` is "any rank" — printing the number there would invite the
/// reader to think rank 8 is a property of *this rule* rather than the
/// workspace-wide ceiling `SHP-006` set.
fn rank_range(rule: &CapabilityRule) -> String {
    match (rule.min_rank, rule.max_rank) {
        (0, MAX_RANK) => "any".to_string(),
        (min, MAX_RANK) => alloc::format!("{min}+"),
        (min, max) if min == max => alloc::format!("{min}"),
        (min, max) => alloc::format!("{min}–{max}"),
    }
}

fn legend() -> String {
    alloc::format!(
        "## Reading this\n\
         \n\
         - **Element types** are the dtypes the rule covers. A dtype absent from \
         every rule for an operation is refused by the registry, which is what \
         lets a planner ask before it allocates.\n\
         - **Layouts** are `LayoutClass` values. `contiguous` is dense row-major; \
         `strided` means the kernel handles a non-dense view without a copy.\n\
         - **Rank** is the tensor rank the rule accepts. `any` is `0..={MAX_RANK}`, \
         the single workspace ceiling.\n\
         - **Training** says whether the rule also covers the backward pass. A \
         rule with `no` still runs under inference.\n\
         - **Implementation** is `native` for a dedicated kernel and `composed` \
         for an operation built from others. Both execute; they differ in cost.\n"
    )
}

fn code(s: &str) -> String {
    alloc::format!("`{s}`")
}

fn join(items: impl Iterator<Item = String>) -> String {
    let collected: Vec<String> = items.collect();
    collected.join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use incin_core::exec::{ImplementationKind, LayoutClass, MathMode};
    use incin_core::prelude::{DTypeId, OperationKind};

    const PRECISE: &[MathMode] = &[MathMode::Precise];
    const CONTIGUOUS: &[LayoutClass] = &[LayoutClass::Contiguous];

    const fn rule(operation: OperationKind, dtypes: &'static [DTypeId]) -> CapabilityRule {
        CapabilityRule::new(
            operation,
            dtypes,
            CONTIGUOUS,
            0,
            MAX_RANK,
            false,
            PRECISE,
            ImplementationKind::Native,
        )
    }

    static HAS_MATMUL: &[CapabilityRule] = &[rule(OperationKind::MatMulExact, &[DTypeId::F32])];
    static HAS_NEITHER: &[CapabilityRule] = &[rule(OperationKind::ReshapeExact, &[DTypeId::F32])];

    /// The real backends all register the same eleven operations, so the cell
    /// for an operation one backend lacks never renders against them. It is the
    /// one cell whose wording matters most — a blank there would read as "no
    /// data" rather than "not supported" — so it is exercised against a fixture
    /// where the backends do differ.
    #[test]
    fn a_backend_missing_an_operation_gets_an_explicit_dash() {
        let devices: &[(DeviceKind, &[CapabilityRule])] = &[
            (DeviceKind::Cpu, HAS_MATMUL),
            (DeviceKind::Cuda, HAS_NEITHER),
        ];
        let table = summary(devices);
        assert!(
            table.contains("| `matmul` | `f32` | — |"),
            "a backend that does not register matmul must be marked, got:\n{table}"
        );
        assert!(
            table.contains("| `reshape` | — | `f32` |"),
            "the dash has to follow the backend, not the column, got:\n{table}"
        );
    }

    /// One device registering an operation twice must widen the cell rather
    /// than have the second row overwrite the first.
    #[test]
    fn repeated_registrations_are_unioned_rather_than_replaced() {
        static TWICE: &[CapabilityRule] = &[
            rule(OperationKind::ReshapeExact, &[DTypeId::F32]),
            rule(OperationKind::ReshapeExact, &[DTypeId::I64, DTypeId::F32]),
        ];
        let table = summary(&[(DeviceKind::Cpu, TWICE)]);
        assert!(
            table.contains("| `reshape` | `f32`, `i64` |"),
            "got:\n{table}"
        );
    }

    /// `any` has to mean the workspace ceiling and nothing else, or a reader
    /// takes rank 8 for a property of the rule.
    #[test]
    fn a_rank_bound_reads_as_a_bound_only_when_it_is_one() {
        let unbounded = rule(OperationKind::MatMul, &[DTypeId::F32]);
        assert_eq!(rank_range(&unbounded), "any");

        let floored = CapabilityRule::new(
            OperationKind::MatMul,
            &[DTypeId::F32],
            CONTIGUOUS,
            2,
            MAX_RANK,
            false,
            PRECISE,
            ImplementationKind::Native,
        );
        assert_eq!(rank_range(&floored), "2+");

        let windowed = CapabilityRule::new(
            OperationKind::Conv2d,
            &[DTypeId::F32],
            CONTIGUOUS,
            3,
            4,
            false,
            PRECISE,
            ImplementationKind::Native,
        );
        assert_eq!(rank_range(&windowed), "3–4");
    }
}
