use crate::prelude::*;

/// A marker type indicating that a reshape dimension should be inferred from the remaining elements.
///
/// When used in an `idx![]` expression, this corresponds to `-1` in Python/NumPy semantics.
/// Only one inferred dimension is allowed per reshape expression.
pub struct InferDim;

/// A marker type indicating that a slice should span the entire extent of a dimension.
///
/// When used in an `idx![]` expression, `..` (or `Ellipsis`) means "take all elements along this axis".
/// This results in a dynamically-sized output dimension (`usize`).
pub struct Ellipsis;

/// A type-level slice spanning the half-open interval `[Start, End)` with known width `Diff`.
///
/// This is generated by the `idx![]` macro when a range literal like `2..5` is used.
/// All three parameters are `typenum::Unsigned` types so the width is a compile-time constant.
///
/// ## Type Parameters
/// * `Start` — The inclusive lower bound (a `typenum::Unsigned`).
/// * `End` — The exclusive upper bound (a `typenum::Unsigned`).
/// * `Diff` — The width of the slice, equal to `End - Start` (a `typenum::Unsigned`).
pub struct Slice<Start, End, Diff> {
    _marker: core::marker::PhantomData<(Start, End, Diff)>,
}

/// A trait for types that can be used as dimension specifiers in the `idx![]` macro for reshaping.
///
/// Implemented by:
/// * `typenum` types (e.g., `U128`) — The dimension is statically known.
/// * `InferDim` — The dimension is computed from the total element count divided by all other known dimensions.
pub trait DimIdx {
    /// The resolved [`Dim`] type in the output shape. `InferDim` resolves to `usize`.
    type Resolved: Dim;

    /// Returns the specified size if known, or `None` if it's `InferDim`.
    fn size() -> Option<usize>;
}

use super::dim::Dim;
use typenum::consts::*;
use typenum::{Bit, UInt, UTerm, Unsigned};

impl DimIdx for UTerm {
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = UTerm;
    /// Core abstraction for `size` within the Kindle framework..
    fn size() -> Option<usize> {
        Some(0)
    }
}

impl<U, B> DimIdx for UInt<U, B>
where
    U: Unsigned + Dim,
    B: Bit + Default + Copy + Clone + core::fmt::Debug + Send + Sync + Eq + PartialEq + 'static,
    UInt<U, B>: Unsigned
        + Default
        + Copy
        + Clone
        + core::fmt::Debug
        + Send
        + Sync
        + Eq
        + PartialEq
        + 'static,
{
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = UInt<U, B>;
    /// Core abstraction for `size` within the Kindle framework..
    fn size() -> Option<usize> {
        Some(Self::USIZE)
    }
}

impl DimIdx for InferDim {
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = usize;
    /// Core abstraction for `size` within the Kindle framework..
    fn size() -> Option<usize> {
        None
    }
}

// Implement for NamedDyn
impl<Tag: 'static + Send + Sync + Copy + Clone + core::fmt::Debug + Eq + PartialEq> DimIdx
    for NamedDyn<Tag>
{
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = NamedDyn<Tag>;
    /// Core abstraction for `size` within the Kindle framework..
    fn size() -> Option<usize> {
        None
    } // Not a static known size, but handled specially
}

/// Computes the new shape resulting from a reshape.
#[diagnostic::on_unimplemented(
    message = "Cannot reshape dimension into `{Self}`",
    label = "Invalid dimension for reshape",
    note = "The element count must remain constant during reshape"
)]
/// Core abstraction for `ReshapeTarget` within the Kindle framework..
pub trait ReshapeTarget<In: Shape> {
    /// Core abstraction for `Output` within the Kindle framework..
    type Output: Shape;
    /// Core abstraction for `calculate_shape` within the Kindle framework..
    fn calculate_shape(in_shape_vec: &[usize]) -> Vec<usize>;
}

// Generate implementations for tuples up to 4D for now to match the user's common cases
macro_rules! impl_reshape_target {
    ($($D:ident),*) => {
        impl<In: Shape, $($D: DimIdx),*> ReshapeTarget<In> for ($($D,)*)
        where
            ($($D::Resolved,)*): Shape,
        {
            /// Core abstraction for `Output` within the Kindle framework..
            type Output = ($($D::Resolved,)*);

            /// Core abstraction for `calculate_shape` within the Kindle framework..
            fn calculate_shape(in_shape_vec: &[usize]) -> Vec<usize> {
                let total_elements: usize = in_shape_vec.iter().product();
                let mut resolved_sizes = vec![];
                let mut infer_idx = None;

                // Collect specified sizes and find the InferDim
                let mut _current_idx = 0usize;
                $(
                    let size = $D::size();
                    if size.is_none() {
                        // Both InferDim and NamedDyn can lack a statically known size (returning None).
                        // In Reshape contexts, InferDim acts as the unique auto-inferred dimension.

                        if infer_idx.is_some() {
                            panic!("Only one inferred dimension (-1 or NamedDyn) is allowed in reshape");
                        }
                        infer_idx = Some(_current_idx);
                        resolved_sizes.push(0); // placeholder
                    } else {
                        resolved_sizes.push(size.unwrap());
                    }
                    _current_idx += 1;
                )*

                if let Some(idx) = infer_idx {
                    let known_product: usize = resolved_sizes.iter().filter(|&&s| s != 0).product();
                    if known_product > 0 {
                        resolved_sizes[idx] = total_elements / known_product;
                    } else {
                        resolved_sizes[idx] = 0;
                    }
                }

                resolved_sizes
            }
        }
    };
}

impl_reshape_target!(D1);
impl_reshape_target!(D1, D2);
impl_reshape_target!(D1, D2, D3);
impl_reshape_target!(D1, D2, D3, D4);

/// A trait for types that describe a slicing operation along a single tensor axis in the `idx![]` macro.
///
/// Implementors include:
/// * [`Slice<Start, End, Diff<End, Start>>`] \u2014 A half-open range, e.g. `idx![1..3]` on an axis of size 10 yields 2 elements.
/// * `typenum` types \u2014 Selects a single index, reducing the rank by 1 in the output.
/// * [`Ellipsis`] \u2014 Selects the full axis extent; output dimension becomes `usize` (dynamic).
pub trait SliceIdx {
    /// The resolved [`Dim`] type in the output shape after this slice is applied.
    type Resolved: Dim;

    /// Computes the `(start, end)` indices for a dimension of the given `size`.
    fn bounds(size: usize) -> (usize, usize);
}

impl<Start: Unsigned, End: Unsigned, Diff: Dim> SliceIdx for Slice<Start, End, Diff> {
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = Diff;
    /// Core abstraction for `bounds` within the Kindle framework..
    fn bounds(_size: usize) -> (usize, usize) {
        (Start::USIZE, End::USIZE)
    }
}

impl SliceIdx for UTerm {
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = U1;
    /// Core abstraction for `bounds` within the Kindle framework..
    fn bounds(_size: usize) -> (usize, usize) {
        (0, 1)
    }
}

impl<U, B> SliceIdx for UInt<U, B>
where
    U: Unsigned + Dim,
    B: Bit + Default + Copy + Clone + core::fmt::Debug + Send + Sync + Eq + PartialEq + 'static,
    UInt<U, B>: Unsigned
        + Default
        + Copy
        + Clone
        + core::fmt::Debug
        + Send
        + Sync
        + Eq
        + PartialEq
        + 'static,
{
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = U1;
    /// Core abstraction for `bounds` within the Kindle framework..
    fn bounds(_size: usize) -> (usize, usize) {
        (Self::USIZE, Self::USIZE + 1)
    }
}

// Ellipsis represents taking the full dimension for all remaining dims.
// We can't easily implement a variadic Ellipsis in simple tuple traits without
// advanced macro work. For now, we assume `..` is a single full dimension slice.
impl SliceIdx for Ellipsis {
    /// Core abstraction for `Resolved` within the Kindle framework..
    type Resolved = usize; // Dyn size since it depends on the input
    /// Core abstraction for `bounds` within the Kindle framework..
    fn bounds(size: usize) -> (usize, usize) {
        (0, size)
    }
}

#[diagnostic::on_unimplemented(
    message = "Cannot slice dimension with `{Self}`",
    label = "Invalid slice target",
    note = "The slice range must be within the bounds of the original dimension"
)]
/// Core abstraction for `SliceTarget` within the Kindle framework..
pub trait SliceTarget<In: Shape> {
    /// Core abstraction for `Output` within the Kindle framework..
    type Output: Shape;
    /// Returns the bounds (start, end) for each dimension in `in_shape_vec`
    fn calculate_bounds(in_shape_vec: &[usize]) -> Vec<(usize, usize)>;
}

macro_rules! impl_slice_target {
    ($($D:ident),*) => {
        impl<In: Shape, $($D: SliceIdx),*> SliceTarget<In> for ($($D,)*)
        where
            ($($D::Resolved,)*): Shape,
        {
            /// Core abstraction for `Output` within the Kindle framework..
            type Output = ($($D::Resolved,)*);

            /// Core abstraction for `calculate_bounds` within the Kindle framework..
            fn calculate_bounds(in_shape_vec: &[usize]) -> Vec<(usize, usize)> {
                let mut bounds = vec![];
                let mut _current_idx = 0usize;
                $(
                    let size = in_shape_vec.get(_current_idx).copied().unwrap_or(0);
                    bounds.push($D::bounds(size));
                    _current_idx += 1;
                )*
                bounds
            }
        }
    };
}

impl_slice_target!(D1);
impl_slice_target!(D1, D2);
impl_slice_target!(D1, D2, D3);
impl_slice_target!(D1, D2, D3, D4);

#[cfg(test)]
/// Core abstraction for `tests` within the Kindle framework..
mod tests {
    use super::*;
    use crate::prelude::Shape;
    use typenum::{U0, U1, U2, U3, U4};

    /// Core abstraction for `assert_shape_eq` within the Kindle framework..
    fn assert_shape_eq<S1: Shape, S2: Shape>() {}

    #[test]
    /// Core abstraction for `slice_range_output_shape` within the Kindle framework..
    fn slice_range_output_shape() {
        // idx![1..3, .., 0..2] on (U4, U4, U3) → (U2, usize, U2)
        /// Core abstraction for `IdxT` within the Kindle framework..
        type IdxT = (Slice<U1, U3, U2>, Ellipsis, Slice<U0, U2, U2>);
        assert_shape_eq::<<IdxT as SliceTarget<(U4, U4, U3)>>::Output, (U2, usize, U2)>();
    }

    #[test]
    /// Core abstraction for `slice_full_passthrough` within the Kindle framework..
    fn slice_full_passthrough() {
        // idx![.., .., ..] on (U4, U4, U3) → (usize, usize, usize)
        /// Core abstraction for `IdxT` within the Kindle framework..
        type IdxT = (Ellipsis, Ellipsis, Ellipsis);
        assert_shape_eq::<<IdxT as SliceTarget<(U4, U4, U3)>>::Output, (usize, usize, usize)>();
    }
}
