//! The single declaration of stable semantic operations.
//!
//! The callback macro is intentionally data-only.  `shapes::error` uses it to
//! generate the exact diagnostic identity, while `exec::catalog` uses the same
//! rows to generate typed descriptor markers and the reviewed inventory.  A
//! backend declaration macro consumes the resulting identities when it couples
//! `Execute<O>` implementations to capability rows.

macro_rules! incin_operation_catalog {
    ($callback:ident) => {
        $callback! {
            // identity, spelling, family, semantic profile, typed attributes, min/max arity, legacy source
            (TensorFromData, "tensor_from_data", Storage, Creation, CreationAttributes, 0, 0, "TensorArgsData"),
            (TensorFromBytes, "tensor_from_bytes", Storage, Creation, CreationAttributes, 0, 0, "Tensor::from_bytes"),
            (TensorToBytes, "tensor_to_bytes", Storage, Transfer, NoAttributes, 1, 1, "Tensor::to_bytes"),
            (Zeros, "zeros", Fill, Creation, CreationAttributes, 0, 0, "CreationOps::zeros"),
            (Ones, "ones", Fill, Creation, CreationAttributes, 0, 0, "CreationOps::ones"),
            (UniformRandom, "rand", Random, Creation, CreationAttributes, 0, 0, "CreationOps::rand"),
            (NormalRandom, "randn", Random, Creation, CreationAttributes, 0, 0, "CreationOps::randn"),
            (VariableZeros, "var_zeros", Fill, Creation, CreationAttributes, 0, 0, "CreationOps::var_zeros"),
            (VariableOnes, "var_ones", Fill, Creation, CreationAttributes, 0, 0, "CreationOps::var_ones"),
            (VariableUniformRandom, "var_rand", Random, Creation, CreationAttributes, 0, 0, "CreationOps::var_rand"),
            (VariableNormalRandom, "var_randn", Random, Creation, CreationAttributes, 0, 0, "CreationOps::var_randn"),
            (Full, "full", Fill, Creation, FullAttributes, 0, 0, "CreationOps::full"),
            (Arange, "arange", Fill, Creation, ArangeAttributes, 0, 0, "CreationOps::arange"),
            (Linspace, "linspace", Fill, Creation, LinspaceAttributes, 0, 0, "CreationOps::linspace"),
            (Sample, "sample", Random, Creation, DistributionAttributes, 0, 0, "Tensor::sample"),

            (Relu, "relu", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::relu"),
            (Step, "step", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::step"),
            (Mish, "mish", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::mish"),
            (Elu, "elu", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::elu"),
            (Gelu, "gelu", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::gelu"),
            (Abs, "abs", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::abs"),
            (Exp, "exp", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::exp"),
            (Neg, "neg", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::neg"),
            (Sqrt, "sqrt", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::sqrt"),
            (Log, "log", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::log"),
            (Tanh, "tanh", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::tanh"),
            (Sigmoid, "sigmoid", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::sigmoid"),
            (Swish, "swish", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::swish"),
            (Softmax, "softmax", Normalization, Normalization, AxisAttributes, 1, 1, "FloatOps::softmax"),
            (AddScalar, "add_scalar", Pointwise, UnaryFloat, ScalarAttributes, 1, 1, "FloatOps::add_scalar_float"),
            (MulScalar, "mul_scalar", Pointwise, UnaryFloat, ScalarAttributes, 1, 1, "FloatOps::mul_scalar_float"),
            (Powf, "powf", Pointwise, UnaryFloat, ScalarAttributes, 1, 1, "FloatOps::powf"),
            (Clamp, "clamp", Pointwise, UnaryFloat, ClampAttributes, 1, 1, "FloatOps::clamp"),
            (Sign, "sign", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::sign"),
            (Floor, "floor", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::floor"),
            (Ceil, "ceil", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::ceil"),
            (Round, "round", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::round"),
            (Log2, "log2", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::log2"),
            (Log10, "log10", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::log10"),
            (Sin, "sin", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::sin"),
            (Cos, "cos", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::cos"),
            (Tan, "tan", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::tan"),
            (Asin, "asin", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::asin"),
            (Acos, "acos", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::acos"),
            (Atan, "atan", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::atan"),
            (Atan2, "atan2", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "FloatOps::atan2"),
            (Sinh, "sinh", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::sinh"),
            (Cosh, "cosh", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::cosh"),
            (Asinh, "asinh", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::asinh"),
            (Acosh, "acosh", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::acosh"),
            (Atanh, "atanh", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::atanh"),
            (Erf, "erf", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::erf"),
            (Rsqrt, "rsqrt", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::rsqrt"),
            (Trunc, "trunc", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::trunc"),
            (Frac, "frac", Pointwise, UnaryFloat, NoAttributes, 1, 1, "FloatOps::frac"),
            (Fmod, "fmod", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "FloatOps::fmod"),
            (Remainder, "remainder", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "FloatOps::remainder"),
            (Add, "add", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "NumericOps::add"),
            (Sub, "sub", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "NumericOps::sub"),
            (Mul, "mul", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "NumericOps::mul"),
            (Div, "div", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "NumericOps::div"),
            (SubScalar, "sub_scalar", Pointwise, UnaryFloat, ScalarAttributes, 1, 1, "TensorOps::sub_scalar"),
            (DivScalar, "div_scalar", Pointwise, UnaryFloat, ScalarAttributes, 1, 1, "TensorOps::div_scalar"),
            (Maximum, "maximum", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "TensorOps::maximum"),
            (Minimum, "minimum", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "TensorOps::minimum"),
            (AbsDiff, "abs_diff", Pointwise, BinaryBroadcast, NoAttributes, 2, 2, "TensorOps::abs_diff"),
            (Lerp, "lerp", Pointwise, BinaryBroadcast, LerpAttributes, 2, 2, "TensorOps::lerp"),
            (CmpEq, "cmp_eq", Pointwise, Comparison, NoAttributes, 2, 2, "TensorOps::cmp_eq"),
            (CmpNe, "cmp_ne", Pointwise, Comparison, NoAttributes, 2, 2, "TensorOps::cmp_ne"),
            (CmpLt, "cmp_lt", Pointwise, Comparison, NoAttributes, 2, 2, "TensorOps::cmp_lt"),
            (CmpLe, "cmp_le", Pointwise, Comparison, NoAttributes, 2, 2, "TensorOps::cmp_le"),
            (CmpGt, "cmp_gt", Pointwise, Comparison, NoAttributes, 2, 2, "TensorOps::cmp_gt"),
            (CmpGe, "cmp_ge", Pointwise, Comparison, NoAttributes, 2, 2, "TensorOps::cmp_ge"),
            (LogicalAnd, "logical_and", Pointwise, Logical, NoAttributes, 2, 2, "TensorOps::logical_and"),
            (LogicalOr, "logical_or", Pointwise, Logical, NoAttributes, 2, 2, "TensorOps::logical_or"),
            (LogicalNot, "logical_not", Pointwise, Logical, NoAttributes, 1, 1, "TensorOps::logical_not"),
            (AddInPlace, "add_in_place", Pointwise, Mutation, NoAttributes, 2, 2, "Tensor::add_"),
            (SubInPlace, "sub_in_place", Pointwise, Mutation, NoAttributes, 2, 2, "Tensor::sub_"),
            (MulInPlace, "mul_in_place", Pointwise, Mutation, NoAttributes, 2, 2, "Tensor::mul_"),
            (DivInPlace, "div_in_place", Pointwise, Mutation, NoAttributes, 2, 2, "Tensor::div_"),
            (ZeroInPlace, "zero_in_place", Fill, Mutation, NoAttributes, 1, 1, "Tensor::zero_"),
            (FillInPlace, "fill_in_place", Fill, Mutation, ScalarAttributes, 1, 1, "Tensor::fill_"),

            (ReshapeExact, "reshape", Storage, Shape, ShapeAttributes, 1, 1, "TensorOps::reshape"),
            (TransposeExact, "transpose", Storage, Shape, TransposeAttributes, 1, 1, "TensorOps::transpose"),
            (MatMulExact, "matmul", Reduction, MatMul, NoAttributes, 2, 2, "TensorOps::matmul"),
            (Dot, "dot", Reduction, MatMul, NoAttributes, 2, 2, "Tensor::dot"),
            (Outer, "outer", Reduction, MatMul, NoAttributes, 2, 2, "Tensor::outer"),
            (BroadcastAs, "broadcast_as", Storage, Shape, ShapeAttributes, 1, 1, "TensorOps::broadcast_as"),
            (Narrow, "narrow", Storage, Shape, NarrowAttributes, 1, 1, "TensorOps::narrow"),
            (SqueezeExact, "squeeze", Storage, Shape, AxisAttributes, 1, 1, "TensorOps::squeeze"),
            (StackExact, "stack", Storage, Shape, AxisAttributes, 1, usize::MAX, "TensorOps::stack"),
            (ConcatExact, "concat", Storage, Shape, AxisAttributes, 1, usize::MAX, "TensorOps::concat"),
            (SliceExact, "slice", Storage, Shape, SliceAttributes, 1, 1, "TensorOps::slice"),
            (FlattenExact, "flatten", Storage, Shape, FlattenAttributes, 1, 1, "TensorOps::flatten"),
            (WhereCond, "where_cond", Pointwise, Selection, NoAttributes, 3, 3, "TensorOps::where_cond"),
            (Gather, "gather", Storage, Indexing, AxisAttributes, 2, 2, "TensorOps::gather"),
            (Scatter, "scatter", Storage, Indexing, ScatterAttributes, 3, 3, "TensorOps::scatter"),
            (IndexSelect, "index_select", Storage, Indexing, AxisAttributes, 2, 2, "TensorOps::index_select"),
            (MaskedFill, "masked_fill", Pointwise, Selection, ScalarAttributes, 2, 2, "TensorOps::masked_fill"),
            (UnsqueezeExact, "unsqueeze", Storage, Shape, AxisAttributes, 1, 1, "TensorOps::unsqueeze"),
            (Repeat, "repeat", Storage, Shape, RepeatAttributes, 1, 1, "TensorOps::repeat"),
            (Pad, "pad", Storage, Shape, PadAttributes, 1, 1, "TensorOps::pad"),
            (Triu, "triu", Storage, Shape, DiagonalAttributes, 1, 1, "TensorOps::triu"),
            (Tril, "tril", Storage, Shape, DiagonalAttributes, 1, 1, "TensorOps::tril"),
            (Diag, "diag", Storage, Shape, DiagonalAttributes, 1, 1, "TensorOps::diag"),
            (Chunk, "chunk", Storage, Shape, ChunkAttributes, 1, 1, "Tensor::chunk"),
            (Split, "split", Storage, Shape, SplitAttributes, 1, 1, "Tensor::split"),
            (Addmm, "addmm", Reduction, MatMul, AddmmAttributes, 3, 3, "TensorOps::addmm"),
            (BatchedMatMul, "bmm", Reduction, MatMul, NoAttributes, 2, 2, "TensorOps::bmm"),
            (ScaledDotProductAttention, "scaled_dot_product_attention", Reduction, Attention, AttentionAttributes, 3, 4, "TensorOps::scaled_dot_product_attention"),
            (Unfold, "unfold", Storage, Shape, UnfoldAttributes, 1, 1, "TensorOps::unfold"),
            (PixelShuffle, "pixel_shuffle", Storage, Shape, PixelShuffleAttributes, 1, 1, "TensorOps::pixel_shuffle"),
            (GroupNorm, "group_norm", Normalization, Normalization, GroupNormAttributes, 1, 1, "TensorOps::group_norm"),
            (InstanceNorm, "instance_norm", Normalization, Normalization, EpsilonAttributes, 1, 1, "TensorOps::instance_norm"),
            (BroadcastLeft, "broadcast_left", Storage, Shape, ShapeAttributes, 1, 1, "TensorOps::broadcast_left"),
            (ToHostFloatScalar, "float_to_scalar", Storage, Transfer, NoAttributes, 1, 1, "TensorOps::float_to_scalar"),
            (ToHostFloatVec, "float_to_vec1", Storage, Transfer, NoAttributes, 1, 1, "TensorOps::float_to_vec1"),
            (ToHostIntScalar, "int_to_scalar", Storage, Transfer, NoAttributes, 1, 1, "TensorOps::int_to_scalar"),
            (ToHostIntVec, "int_to_vec1", Storage, Transfer, NoAttributes, 1, 1, "TensorOps::int_to_vec1"),
            (ToDType, "to_dtype", Storage, Transfer, DTypeAttributes, 1, 1, "TensorOps::tensor_to_dtype"),
            (ToDevice, "to_device", Storage, Transfer, DeviceAttributes, 1, 1, "TransferTo"),
            (RequireGrad, "require_grad", Storage, Autograd, NoAttributes, 1, 1, "Tensor::require_grad"),
            (Detach, "detach", Storage, Autograd, NoAttributes, 1, 1, "Tensor::detach"),
            (Backward, "backward", Storage, Autograd, NoAttributes, 1, 1, "Tensor::backward"),

            (SumAll, "sum_all", Reduction, Reduction, NoAttributes, 1, 1, "ReductionOps::sum_all"),
            (MeanAll, "mean_all", Reduction, Reduction, NoAttributes, 1, 1, "ReductionOps::mean_all"),
            (MaxAll, "max_all", Reduction, Reduction, NoAttributes, 1, 1, "ReductionOps::max_all"),
            (MinAll, "min_all", Reduction, Reduction, NoAttributes, 1, 1, "ReductionOps::min_all"),
            (SumDim, "sum_dim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::sum_dim"),
            (SumKeepDim, "sum_keepdim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::sum_keepdim"),
            (MeanDim, "mean_dim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::mean_dim"),
            (MeanKeepDim, "mean_keepdim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::mean_keepdim"),
            (MaxDim, "max_dim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::max_dim"),
            (MaxKeepDim, "max_keepdim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::max_keepdim"),
            (MinDim, "min_dim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::min_dim"),
            (MinKeepDim, "min_keepdim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::min_keepdim"),
            (ArgMax, "argmax", Reduction, IndexReduction, IndexReductionAttributes, 1, 1, "ReductionOps::argmax"),
            (ArgMin, "argmin", Reduction, IndexReduction, IndexReductionAttributes, 1, 1, "ReductionOps::argmin"),
            (ProdAll, "prod_all", Reduction, Reduction, NoAttributes, 1, 1, "ReductionOps::prod_all"),
            (ProdDim, "prod_dim", Reduction, Reduction, AxisAttributes, 1, 1, "ReductionOps::prod_dim"),
            (Cumsum, "cumsum", Reduction, Scan, AxisAttributes, 1, 1, "ReductionOps::cumsum"),
            (TopK, "topk", Reduction, IndexReduction, TopKAttributes, 1, 1, "ReductionOps::topk"),
            (Argsort, "argsort", Reduction, IndexReduction, ArgsortAttributes, 1, 1, "ReductionOps::argsort"),
            (Norm, "norm", Reduction, Reduction, NormAttributes, 1, 1, "Tensor::norm"),
            (VarianceAll, "var_all", Reduction, Reduction, VarianceAttributes, 1, 1, "Tensor::var_all"),
            (VarianceDim, "var_dim", Reduction, Reduction, AxisVarianceAttributes, 1, 1, "Tensor::var_dim"),
            (VarianceKeepDim, "var_keepdim", Reduction, Reduction, AxisVarianceAttributes, 1, 1, "Tensor::var_keepdim"),
            (StdAll, "std_all", Reduction, Reduction, VarianceAttributes, 1, 1, "Tensor::std_all"),
            (StdDim, "std_dim", Reduction, Reduction, AxisVarianceAttributes, 1, 1, "Tensor::std_dim"),
            (StdKeepDim, "std_keepdim", Reduction, Reduction, AxisVarianceAttributes, 1, 1, "Tensor::std_keepdim"),

            (LayerNorm, "layer_norm", Normalization, Module, LayerNormAttributes, 2, 3, "ModuleOps::layer_norm"),
            (BatchNorm, "batch_norm", Normalization, Module, BatchNormAttributes, 1, 5, "ModuleOps::batch_norm"),
            (EmbeddingExact, "embedding", Storage, Module, NoAttributes, 2, 2, "ModuleOps::embedding"),
            (Conv1dExact, "conv1d", Reduction, Module, Conv1dAttributes, 2, 3, "ModuleOps::conv1d"),
            (Conv2dExact, "conv2d", Reduction, Module, Conv2dAttributes, 2, 3, "ModuleOps::conv2d"),
            (ConvTranspose2d, "conv_transpose2d", Reduction, Module, ConvTranspose2dAttributes, 2, 3, "ModuleOps::conv_transpose2d"),
            (MaxPool2d, "max_pool2d", Reduction, Module, Pool2dAttributes, 1, 1, "ModuleOps::max_pool2d"),
            (AvgPool2d, "avg_pool2d", Reduction, Module, AvgPool2dAttributes, 1, 1, "ModuleOps::avg_pool2d"),
            (AdaptiveAvgPool2dExact, "adaptive_avg_pool2d", Reduction, Module, AdaptivePool2dAttributes, 1, 1, "ModuleOps::adaptive_avg_pool2d"),
            (Linear, "linear", Reduction, Composite, LinearAttributes, 2, 3, "Linear::forward"),
            (RmsNorm, "rms_norm", Normalization, Composite, EpsilonAttributes, 2, 2, "RMSNorm::forward"),
            (Dropout, "dropout", Pointwise, Composite, DropoutAttributes, 1, 1, "Dropout::forward"),
            (Rnn, "rnn", Pointwise, Composite, RecurrentAttributes, 2, 2, "RNN::forward"),
            (Lstm, "lstm", Pointwise, Composite, RecurrentAttributes, 3, 3, "LSTM::forward"),

            (MseLoss, "mse_loss", Reduction, Loss, LossAttributes, 2, 2, "LossOps::mse_loss"),
            (L1Loss, "l1_loss", Reduction, Loss, LossAttributes, 2, 2, "LossOps::l1_loss"),
            (BceWithLogitsLoss, "bce_with_logits_loss", Reduction, Loss, LossAttributes, 2, 2, "LossOps::bce_with_logits_loss"),
            (CrossEntropyLoss, "cross_entropy_loss", Reduction, Loss, LossAttributes, 2, 2, "LossOps::cross_entropy_loss"),
            (Quantize, "quantize", Pointwise, Quantized, QuantizationAttributes, 1, 1, "QuantizedOps::quantize"),
            (Dequantize, "dequantize", Pointwise, Quantized, QuantizationAttributes, 1, 1, "QuantizedOps::dequantize"),
            (QuantizedMatMul, "quantized_matmul", Reduction, Quantized, NoAttributes, 2, 2, "QuantizedOps::quantized_matmul"),
            (SgdStep, "sgd_step", Pointwise, Optimizer, SgdAttributes, 2, 2, "SGD::step"),
            (AdamStep, "adam_step", Pointwise, Optimizer, AdamAttributes, 4, 4, "Adam::step"),
            (AdamWStep, "adamw_step", Pointwise, Optimizer, AdamWAttributes, 4, 4, "OptimizerOps::adamw_step"),
        }
    };
}
