[package]
authors = ["xupremix <xupremix.me@gmail.com>"]
name = "testing"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[features]

[dependencies]
kindle = { path = "../../crates/kindle", features = ["std"], default-features = false }
kindle-backends = { path = "../../crates/kindle-backends", features = ["candle"] }
