[package]
name = "backends"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true
publish = false

[dependencies]
incin = { path = "../..", version = "0.1.0", features = ["wgpu"] }

[features]
default = []
cuda = ["incin/cuda"]
wgpu = ["incin/wgpu"]

[lints]
workspace = true

