use crate::prelude::*;

/// A marker type indicating that a reshape dimension should be inferred from the remaining elements.
///
/// When used in an `idx![]` expression, this corresponds to `-1` in Python/NumPy semantics.
/// Only one inferred dimension is allowed per reshape expression.
pub struct InferDim;

/// A marker type indicating that a slice should span the entire extent of a dimension.
///
/// When used in an `idx![]` expression, `..` (or `Ellipsis`) means "take all elements along this axis".
/// This results in a dynamically-sized output dimension (`usize`).
pub struct Ellipsis;

/// A type-level slice spanning the half-open interval `[Start, End)` with known width `Diff`.
///
/// This is generated by the `idx![]` macro when a range literal like `2..5` is used.
/// All three parameters are `typenum::Unsigned` types so the width is a compile-time constant.
///
/// ## Type Parameters
/// * `Start` — The inclusive lower bound (a `typenum::Unsigned`).
/// * `End` — The exclusive upper bound (a `typenum::Unsigned`).
/// * `Diff` — The width of the slice, equal to `End - Start` (a `typenum::Unsigned`).
pub struct Slice<Start, End, Diff> {
    _marker: core::marker::PhantomData<(Start, End, Diff)>,
}

/// A trait for types that can be used as dimension specifiers in the `idx![]` macro for reshaping.
///
/// Implemented by:
/// * `typenum` types (e.g., `U128`) — The dimension is statically known.
/// * `InferDim` — The dimension is computed from the total element count divided by all other known dimensions.
pub trait DimIdx {
    /// The resolved [`Dim`] type in the output shape. `InferDim` resolves to `usize`.
    type Resolved: Dim;

    /// Returns the specified size if known, or `None` if it's `InferDim`.
    fn size() -> Option<usize>;
}

use super::dim::Dim;
use typenum::consts::*;
use typenum::{Bit, UInt, UTerm, Unsigned};

impl DimIdx for UTerm {
    /// `UTerm` (0) resolves to itself.
    type Resolved = UTerm;
    /// Always `Some(0)`.
    fn size() -> Option<usize> {
        Some(0)
    }
}

impl<U, B> DimIdx for UInt<U, B>
where
    U: Unsigned + Dim,
    B: Bit + Default + Copy + Clone + core::fmt::Debug + Send + Sync + Eq + PartialEq + 'static,
    UInt<U, B>: Unsigned
        + Default
        + Copy
        + Clone
        + core::fmt::Debug
        + Send
        + Sync
        + Eq
        + PartialEq
        + 'static,
{
    /// A known `typenum` size resolves to itself.
    type Resolved = UInt<U, B>;
    /// The compile-time-known size.
    fn size() -> Option<usize> {
        Some(Self::USIZE)
    }
}

impl DimIdx for InferDim {
    /// Resolves to a runtime-computed `usize`.
    type Resolved = usize;
    /// Always `None` — the size is inferred from the other dimensions.
    fn size() -> Option<usize> {
        None
    }
}

// Implement for NamedDyn
impl<Tag: 'static + Send + Sync + Copy + Clone + core::fmt::Debug + Eq + PartialEq> DimIdx
    for NamedDyn<Tag>
{
    /// A named-dynamic dimension resolves to itself.
    type Resolved = NamedDyn<Tag>;
    /// Always `None` — not a static known size, but handled specially.
    fn size() -> Option<usize> {
        None
    }
}

/// Computes the new shape resulting from a reshape.
#[diagnostic::on_unimplemented(
    message = "Cannot reshape dimension into `{Self}`",
    label = "Invalid dimension for reshape",
    note = "The element count must remain constant during reshape"
)]
pub trait ReshapeTarget<In: Shape> {
    /// The resolved output shape (each `DimIdx` entry resolved, with at
    /// most one `InferDim` inferred from the remaining element count).
    type Output: Shape;
    /// Computes the concrete output dimensions from the input's runtime shape.
    fn calculate_shape(
        in_shape_vec: &[usize],
    ) -> core::result::Result<Vec<usize>, crate::shapes::error::ShapeError>;
}

// Generate implementations for tuples up to 4D for now to match the user's common cases
macro_rules! impl_reshape_target {
    ($($D:ident),*) => {
        impl<In: Shape, $($D: DimIdx),*> ReshapeTarget<In> for ($($D,)*)
        where
            ($($D::Resolved,)*): Shape,
        {
            /// The resolved output shape.
            type Output = ($($D::Resolved,)*);

            /// Computes the concrete output dimensions from the input's runtime shape.

            fn calculate_shape(in_shape_vec: &[usize]) -> core::result::Result<Vec<usize>, crate::shapes::error::ShapeError> {
                let total_elements = crate::shapes::ShapeBuf::from_slice(in_shape_vec)
                    .checked_numel(crate::shapes::error::OperationKind::Reshape)?;
                let mut resolved_sizes = vec![];
                let mut infer_idx = None;

                // Collect specified sizes and find the InferDim
                let mut _current_idx = 0usize;
                $(
                    let size = $D::size();
                    if size.is_none() {
                        // Both InferDim and NamedDyn can lack a statically known size (returning None).
                        // In Reshape contexts, InferDim acts as the unique auto-inferred dimension.

                        if infer_idx.is_some() {
                            return Err(crate::shapes::error::ShapeError::InvalidParameter {
                                operation: crate::shapes::error::OperationKind::Reshape,
                                parameter: "inferred dimensions",
                                value: 2,
                            });
                        }
                        infer_idx = Some(_current_idx);
                        resolved_sizes.push(0); // placeholder
                    } else {
                        resolved_sizes.push(size.unwrap());
                    }
                    _current_idx += 1;
                )*

                if let Some(idx) = infer_idx {
                    let known_product = resolved_sizes
                        .iter()
                        .filter(|&&size| size != 0)
                        .try_fold(1usize, |product, &size| product.checked_mul(size))
                        .ok_or(crate::shapes::error::ShapeError::ArithmeticOverflow {
                            operation: crate::shapes::error::OperationKind::Reshape,
                            expression: "product of specified reshape dimensions",
                        })?;
                    if known_product > 0 {
                        if !total_elements.is_multiple_of(known_product) {
                            return Err(crate::shapes::error::ShapeError::DimensionMismatch {
                                operation: crate::shapes::error::OperationKind::Reshape,
                                axis: crate::shapes::error::Axis::Index(idx),
                                lhs: total_elements,
                                rhs: known_product,
                                constraint: crate::shapes::error::DimensionConstraint::DivisibleBy,
                            });
                        }
                        resolved_sizes[idx] = total_elements / known_product;
                    } else {
                        resolved_sizes[idx] = 0;
                    }
                }

                Ok(resolved_sizes)
            }
        }
    };
}

// Already variadic; it was simply never invoked above rank 4, so a rank-5
// reshape target had no impl while the rank-5 shape it targeted did.
incin_macros::rank_sweep!(names_from1 => impl_reshape_target);

/// A trait for types that describe a slicing operation along a single tensor axis in the `idx![]` macro.
///
/// Implementors include:
/// * [`Slice<Start, End, Diff<End, Start>>`] \u2014 A half-open range, e.g. `idx![1..3]` on an axis of size 10 yields 2 elements.
/// * `typenum` types \u2014 Selects a single index, reducing the rank by 1 in the output.
/// * [`Ellipsis`] \u2014 Selects the full axis extent; output dimension becomes `usize` (dynamic).
pub trait SliceIdx {
    /// The resolved [`Dim`] type in the output shape after this slice is applied.
    type Resolved: Dim;

    /// Computes the `(start, end)` indices for a dimension of the given `size`.
    fn bounds(size: usize) -> (usize, usize);
}

impl<Start: Unsigned, End: Unsigned, Diff: Dim> SliceIdx for Slice<Start, End, Diff> {
    /// The slice's known width.
    type Resolved = Diff;
    /// The compile-time-known `(Start, End)` bounds, ignoring the actual
    /// dimension size.
    fn bounds(_size: usize) -> (usize, usize) {
        (Start::USIZE, End::USIZE)
    }
}

impl SliceIdx for UTerm {
    /// A bare index selects a single element, reducing this axis to size 1.
    type Resolved = U1;
    /// Selects index `0`.
    fn bounds(_size: usize) -> (usize, usize) {
        (0, 1)
    }
}

impl<U, B> SliceIdx for UInt<U, B>
where
    U: Unsigned + Dim,
    B: Bit + Default + Copy + Clone + core::fmt::Debug + Send + Sync + Eq + PartialEq + 'static,
    UInt<U, B>: Unsigned
        + Default
        + Copy
        + Clone
        + core::fmt::Debug
        + Send
        + Sync
        + Eq
        + PartialEq
        + 'static,
{
    /// A bare index selects a single element, reducing this axis to size 1.
    type Resolved = U1;
    /// Selects the index encoded by this `typenum` value.
    fn bounds(_size: usize) -> (usize, usize) {
        (Self::USIZE, Self::USIZE + 1)
    }
}

// Ellipsis represents taking the full dimension for all remaining dims.
// We can't easily implement a variadic Ellipsis in simple tuple traits without
// advanced macro work. For now, we assume `..` is a single full dimension slice.
impl SliceIdx for Ellipsis {
    /// Dynamic size, since it depends on the input.
    type Resolved = usize;
    /// Selects the entire axis, `[0, size)`.
    fn bounds(size: usize) -> (usize, usize) {
        (0, size)
    }
}

#[diagnostic::on_unimplemented(
    message = "Cannot slice dimension with `{Self}`",
    label = "Invalid slice target",
    note = "The slice range must be within the bounds of the original dimension"
)]
/// Computes the output shape resulting from an `idx![]` slice expression.
pub trait SliceTarget<In: Shape> {
    /// The resolved output shape after applying each dimension's `SliceIdx`.
    type Output: Shape;
    /// Returns the bounds (start, end) for each dimension in `in_shape_vec`
    fn calculate_bounds(in_shape_vec: &[usize]) -> Vec<(usize, usize)>;
}

macro_rules! impl_slice_target {
    ($($D:ident),*) => {
        impl<In: Shape, $($D: SliceIdx),*> SliceTarget<In> for ($($D,)*)
        where
            ($($D::Resolved,)*): Shape,
        {
            /// The resolved output shape.
            type Output = ($($D::Resolved,)*);

            /// Computes each dimension's `(start, end)` bounds from the input's runtime shape.

            fn calculate_bounds(in_shape_vec: &[usize]) -> Vec<(usize, usize)> {
                let mut bounds = vec![];
                let mut _current_idx = 0usize;
                $(
                    let size = in_shape_vec.get(_current_idx).copied().unwrap_or(0);
                    bounds.push($D::bounds(size));
                    _current_idx += 1;
                )*
                bounds
            }
        }
    };
}

// Already variadic; same four-rank invocation ceiling as the reshape target.
incin_macros::rank_sweep!(names_from1 => impl_slice_target);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::prelude::Shape;
    use typenum::{U0, U1, U2, U3, U4};

    fn assert_shape_eq<S1: Shape, S2: Shape>() {}

    #[test]
    fn slice_range_output_shape() {
        // idx![1..3, .., 0..2] on (U4, U4, U3) → (U2, usize, U2)
        type IdxT = (Slice<U1, U3, U2>, Ellipsis, Slice<U0, U2, U2>);
        assert_shape_eq::<<IdxT as SliceTarget<(U4, U4, U3)>>::Output, (U2, usize, U2)>();
    }

    #[test]
    fn slice_full_passthrough() {
        // idx![.., .., ..] on (U4, U4, U3) → (usize, usize, usize)
        type IdxT = (Ellipsis, Ellipsis, Ellipsis);
        assert_shape_eq::<<IdxT as SliceTarget<(U4, U4, U3)>>::Output, (usize, usize, usize)>();
    }
}
