use crate::prelude::*;

/// A marker type indicating that a reshape dimension should be inferred from the remaining elements.
///
/// When used in an `idx![]` expression, this corresponds to `-1` in Python/NumPy semantics.
/// Only one inferred dimension is allowed per reshape expression.
pub struct InferDim;

/// A marker type indicating that a slice should span the entire extent of a dimension.
///
/// When used in an `idx![]` expression, `..` (or `Ellipsis`) means "take all elements along this axis".
/// This results in a dynamically-sized output dimension (`usize`).
pub struct Ellipsis;

/// A type-level slice spanning the half-open interval `[Start, End)` with known width `Diff`.
///
/// This is generated by the `idx![]` macro when a range literal like `2..5` is used.
/// All three parameters are `typenum::Unsigned` types so the width is a compile-time constant.
///
/// ## Type Parameters
/// * `Start` — The inclusive lower bound (a `typenum::Unsigned`).
/// * `End` — The exclusive upper bound (a `typenum::Unsigned`).
/// * `Diff` — The width of the slice, equal to `End - Start` (a `typenum::Unsigned`).
pub struct Slice<Start, End, Diff> {
    _marker: core::marker::PhantomData<(Start, End, Diff)>,
}

/// A trait for types that can be used as dimension specifiers in the `idx![]` macro for reshaping.
///
/// Implemented by:
/// * `typenum` types (e.g., `U128`) — The dimension is statically known.
/// * `InferDim` — The dimension is computed from the total element count divided by all other known dimensions.
pub trait DimIdx {
    /// The resolved [`Dim`] type in the output shape. `InferDim` resolves to `usize`.
    type Resolved: Dim;

    /// Returns the specified size if known, or `None` if it's `InferDim`.
    fn size() -> Option<usize>;
}

use super::dim::Dim;
use typenum::consts::*;
use typenum::{Bit, UInt, UTerm, Unsigned};

impl DimIdx for UTerm {
    /// `UTerm` (0) resolves to itself.
    type Resolved = UTerm;
    /// Always `Some(0)`.
    fn size() -> Option<usize> {
        Some(0)
    }
}

impl<U, B> DimIdx for UInt<U, B>
where
    U: Unsigned + Dim,
    B: Bit + Default + Copy + Clone + core::fmt::Debug + Send + Sync + Eq + PartialEq + 'static,
    UInt<U, B>: Unsigned
        + Default
        + Copy
        + Clone
        + core::fmt::Debug
        + Send
        + Sync
        + Eq
        + PartialEq
        + 'static,
{
    /// A known `typenum` size resolves to itself.
    type Resolved = UInt<U, B>;
    /// The compile-time-known size.
    fn size() -> Option<usize> {
        Some(Self::USIZE)
    }
}

impl DimIdx for InferDim {
    /// Resolves to a runtime-computed `usize`.
    type Resolved = usize;
    /// Always `None` — the size is inferred from the other dimensions.
    fn size() -> Option<usize> {
        None
    }
}

// A named runtime extent is a normal canonical `NamedDim`; its semantic tag
// does not change reshape's runtime inference rules.
impl<Tag: crate::shapes::AxisTag> DimIdx for NamedDim<Tag, usize> {
    type Resolved = NamedDim<Tag, usize>;
    fn size() -> Option<usize> {
        None
    }
}

/// Computes the new shape resulting from a reshape.
#[diagnostic::on_unimplemented(
    message = "Cannot reshape dimension into `{Self}`",
    label = "Invalid dimension for reshape",
    note = "The element count must remain constant during reshape"
)]
pub trait ReshapeTarget<In: Shape> {
    /// The resolved output shape (each `DimIdx` entry resolved, with at
    /// most one `InferDim` inferred from the remaining element count).
    type Output: Shape;
    /// Computes the concrete output dimensions from the input's runtime shape.
    fn calculate_shape(
        in_shape_vec: &[usize],
    ) -> core::result::Result<Vec<usize>, crate::shapes::error::ShapeError>;
}

/// Internal recursive collector for structural reshape targets.
#[doc(hidden)]
pub trait ReshapeSpec {
    type Output: Shape;

    fn collect(
        sizes: &mut Vec<usize>,
        inferred: &mut Option<usize>,
    ) -> core::result::Result<(), crate::shapes::error::ShapeError>;
}

impl ReshapeSpec for Nil {
    type Output = Nil;

    fn collect(
        _sizes: &mut Vec<usize>,
        _inferred: &mut Option<usize>,
    ) -> core::result::Result<(), crate::shapes::error::ShapeError> {
        Ok(())
    }
}

impl<D: DimIdx, T: ReshapeSpec> ReshapeSpec for DimCons<D, T>
where
    D::Resolved: Dim,
{
    type Output = DimCons<D::Resolved, T::Output>;

    fn collect(
        sizes: &mut Vec<usize>,
        inferred: &mut Option<usize>,
    ) -> core::result::Result<(), crate::shapes::error::ShapeError> {
        let index = sizes.len();
        if let Some(size) = D::size() {
            sizes.push(size);
        } else {
            if inferred.is_some() {
                return Err(crate::shapes::error::ShapeError::InvalidParameter {
                    operation: crate::shapes::error::OperationKind::Reshape,
                    parameter: "inferred dimensions",
                    value: 2,
                });
            }
            *inferred = Some(index);
            sizes.push(0);
        }
        T::collect(sizes, inferred)
    }
}

impl<In: Shape, Target: ReshapeSpec> ReshapeTarget<In> for Target {
    type Output = Target::Output;

    fn calculate_shape(
        in_shape_vec: &[usize],
    ) -> core::result::Result<Vec<usize>, crate::shapes::error::ShapeError> {
        let total_elements = crate::shapes::ShapeBuf::from_slice(in_shape_vec)
            .checked_numel(crate::shapes::error::OperationKind::Reshape)?;
        let mut sizes = Vec::new();
        let mut inferred = None;
        Target::collect(&mut sizes, &mut inferred)?;
        if let Some(index) = inferred {
            let known_product = sizes
                .iter()
                .enumerate()
                .filter(|(i, _)| *i != index)
                .try_fold(1usize, |product, (_, &size)| product.checked_mul(size))
                .ok_or(crate::shapes::error::ShapeError::ArithmeticOverflow {
                    operation: crate::shapes::error::OperationKind::Reshape,
                    expression: "product of specified reshape dimensions",
                })?;
            if known_product == 0 {
                sizes[index] = 0;
            } else if !total_elements.is_multiple_of(known_product) {
                return Err(crate::shapes::error::ShapeError::DimensionMismatch {
                    operation: crate::shapes::error::OperationKind::Reshape,
                    axis: crate::shapes::error::Axis::Index(index),
                    lhs: total_elements,
                    rhs: known_product,
                    constraint: crate::shapes::error::DimensionConstraint::DivisibleBy,
                });
            } else {
                sizes[index] = total_elements / known_product;
            }
        }
        Ok(sizes)
    }
}

/// A trait for types that describe a slicing operation along a single tensor axis in the `idx![]` macro.
///
/// Implementors include:
/// * [`Slice<Start, End, Diff<End, Start>>`] \u2014 A half-open range, e.g. `idx![1..3]` on an axis of size 10 yields 2 elements.
/// * `typenum` types \u2014 Selects a single index, reducing the rank by 1 in the output.
/// * [`Ellipsis`] \u2014 Selects the full axis extent; output dimension becomes `usize` (dynamic).
pub trait SliceIdx {
    /// The resolved [`Dim`] type in the output shape after this slice is applied.
    type Resolved: Dim;

    /// Computes the `(start, end)` indices for a dimension of the given `size`.
    fn bounds(size: usize) -> (usize, usize);
}

impl<Start: Unsigned, End: Unsigned, Diff: Dim> SliceIdx for Slice<Start, End, Diff> {
    /// The slice's known width.
    type Resolved = Diff;
    /// The compile-time-known `(Start, End)` bounds, ignoring the actual
    /// dimension size.
    fn bounds(_size: usize) -> (usize, usize) {
        (Start::USIZE, End::USIZE)
    }
}

impl SliceIdx for UTerm {
    /// A bare index selects a single element, reducing this axis to size 1.
    type Resolved = U1;
    /// Selects index `0`.
    fn bounds(_size: usize) -> (usize, usize) {
        (0, 1)
    }
}

impl<U, B> SliceIdx for UInt<U, B>
where
    U: Unsigned + Dim,
    B: Bit + Default + Copy + Clone + core::fmt::Debug + Send + Sync + Eq + PartialEq + 'static,
    UInt<U, B>: Unsigned
        + Default
        + Copy
        + Clone
        + core::fmt::Debug
        + Send
        + Sync
        + Eq
        + PartialEq
        + 'static,
{
    /// A bare index selects a single element, reducing this axis to size 1.
    type Resolved = U1;
    /// Selects the index encoded by this `typenum` value.
    fn bounds(_size: usize) -> (usize, usize) {
        (Self::USIZE, Self::USIZE + 1)
    }
}

// Ellipsis represents taking the full dimension for all remaining dims.
// We can't easily implement a variadic Ellipsis in simple tuple traits without
// advanced macro work. For now, we assume `..` is a single full dimension slice.
impl SliceIdx for Ellipsis {
    /// Dynamic size, since it depends on the input.
    type Resolved = usize;
    /// Selects the entire axis, `[0, size)`.
    fn bounds(size: usize) -> (usize, usize) {
        (0, size)
    }
}

#[diagnostic::on_unimplemented(
    message = "Cannot slice dimension with `{Self}`",
    label = "Invalid slice target",
    note = "The slice range must be within the bounds of the original dimension"
)]
/// Computes the output shape resulting from an `idx![]` slice expression.
pub trait SliceTarget<In: Shape> {
    /// The resolved output shape after applying each dimension's `SliceIdx`.
    type Output: Shape;
    /// Returns the bounds (start, end) for each dimension in `in_shape_vec`
    fn calculate_bounds(in_shape_vec: &[usize]) -> Vec<(usize, usize)>;
}

#[doc(hidden)]
pub trait SliceSpec {
    type Output: Shape;
    fn collect(input: &[usize], axis: &mut usize, output: &mut Vec<(usize, usize)>);
}

impl SliceSpec for Nil {
    type Output = Nil;
    fn collect(_input: &[usize], _axis: &mut usize, _output: &mut Vec<(usize, usize)>) {}
}

impl<D: SliceIdx, T: SliceSpec> SliceSpec for DimCons<D, T>
where
    D::Resolved: Dim,
{
    type Output = DimCons<D::Resolved, T::Output>;
    fn collect(input: &[usize], axis: &mut usize, output: &mut Vec<(usize, usize)>) {
        let size = input.get(*axis).copied().unwrap_or(0);
        output.push(D::bounds(size));
        *axis += 1;
        T::collect(input, axis, output);
    }
}

impl<In: Shape, Target: SliceSpec> SliceTarget<In> for Target {
    type Output = Target::Output;
    fn calculate_bounds(in_shape_vec: &[usize]) -> Vec<(usize, usize)> {
        let mut bounds = Vec::new();
        let mut axis = 0;
        Target::collect(in_shape_vec, &mut axis, &mut bounds);
        bounds
    }
}

/// Structural cursor for axis 0.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
pub struct Here;

impl Here {
    pub fn normalize(&self, rank: usize) -> crate::err::Result<Vec<usize>> {
        AxisSelector::new(&[0]).normalize(rank)
    }
}

/// Structural cursor for axis `I + 1`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
pub struct Next<I>(pub core::marker::PhantomData<I>);

impl<I> Next<I> {
    pub const DEFAULT: Self = Next(core::marker::PhantomData);

    pub fn normalize(&self, rank: usize) -> crate::err::Result<Vec<usize>>
    where
        Self: StaticCursor,
    {
        AxisSelector::new(&[Self::INDEX]).normalize(rank)
    }
}

/// Structural cursor for axis counting from end `-(I + 1)`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
pub struct FromEnd<I>(pub core::marker::PhantomData<I>);

impl<I> FromEnd<I> {
    pub const DEFAULT: Self = FromEnd(core::marker::PhantomData);

    pub fn normalize(&self, rank: usize) -> crate::err::Result<Vec<usize>>
    where
        Self: StaticCursor,
    {
        AxisSelector::new(&[Self::INDEX]).normalize(rank)
    }
}

/// Trait for static axis cursors with compile-time evaluated signed index.
pub trait StaticCursor:
    'static + Copy + Clone + core::fmt::Debug + Send + Sync + Eq + PartialEq
{
    const INDEX: isize;
}

impl StaticCursor for Here {
    const INDEX: isize = 0;
}

impl<I: StaticCursor> StaticCursor for Next<I> {
    const INDEX: isize = 1 + I::INDEX;
}

impl<I: StaticCursor> StaticCursor for FromEnd<I> {
    const INDEX: isize = -(1 + I::INDEX);
}

/// Value-level spelling of a compile-time axis cursor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct StaticAxis<I: StaticCursor>(core::marker::PhantomData<I>);

impl<I: StaticCursor> StaticAxis<I> {
    pub const DEFAULT: Self = Self(core::marker::PhantomData);

    pub fn normalize(&self, rank: usize) -> crate::err::Result<Vec<usize>> {
        AxisSelector::new(&[I::INDEX]).normalize(rank)
    }
}

/// A semantic named-axis selector. It carries only the tag and never stores a
/// structural position.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NamedAxisSelector<Tag: crate::shapes::AxisTag>(core::marker::PhantomData<Tag>);

impl<Tag: crate::shapes::AxisTag> Default for NamedAxisSelector<Tag> {
    fn default() -> Self {
        Self(core::marker::PhantomData)
    }
}

impl<Tag: crate::shapes::AxisTag> NamedAxisSelector<Tag> {
    /// Resolves this selector against the current exact shape.
    pub fn resolve<S>(&self) -> crate::err::Result<usize>
    where
        S: NamedAxisLookup<Tag>,
    {
        S::lookup_named().map_err(crate::err::Error::Shape)
    }
}

/// Runtime fallback for named lookup when Stable Rust cannot prove a unique
/// recursive type-level match without overlapping implementations.
pub trait NamedAxisLookup<Tag: crate::shapes::AxisTag>: Shape {
    /// Resolves the semantic name against the current structural shape.
    fn lookup_named() -> core::result::Result<usize, crate::shapes::ShapeError>;
}

trait NamedAxisMetadata {
    fn collect_named(name: &'static str, offset: usize, matches: &mut Vec<usize>);
}

impl NamedAxisMetadata for Nil {
    fn collect_named(_: &'static str, _: usize, _: &mut Vec<usize>) {}
}

impl<H: Dim, T: Shape + NamedAxisMetadata> NamedAxisMetadata for DimCons<H, T> {
    fn collect_named(name: &'static str, offset: usize, matches: &mut Vec<usize>) {
        if H::NAME == Some(name) {
            matches.push(offset);
        }
        T::collect_named(name, offset + 1, matches);
    }
}

impl<Tag: crate::shapes::AxisTag, S: Shape + NamedAxisMetadata> NamedAxisLookup<Tag> for S {
    fn lookup_named() -> core::result::Result<usize, crate::shapes::ShapeError> {
        let mut matches = Vec::new();
        S::collect_named(Tag::NAME, 0, &mut matches);
        match matches.as_slice() {
            [] => Err(crate::shapes::ShapeError::MissingNamedAxis { name: Tag::NAME }),
            [index] => Ok(*index),
            _ => Err(crate::shapes::ShapeError::AmbiguousNamedAxis { name: Tag::NAME }),
        }
    }
}

/// Canonical runtime/static axis selector sequence.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AxisSelector {
    pub raw_axes: Vec<isize>,
}

impl AxisSelector {
    pub fn new(axes: &[isize]) -> Self {
        Self {
            raw_axes: axes.to_vec(),
        }
    }

    /// Normalizes signed relative axis indices against input `rank`, rejecting out-of-range or duplicate indices.
    pub fn normalize(&self, rank: usize) -> crate::err::Result<Vec<usize>> {
        let mut normalized = Vec::with_capacity(self.raw_axes.len());
        for &raw in &self.raw_axes {
            let norm = if raw >= 0 {
                let u = raw as usize;
                if u >= rank {
                    return Err(crate::err::Error::Shape(
                        crate::shapes::error::ShapeError::InvalidAxis { axis: u, rank },
                    ));
                }
                u
            } else {
                let neg = raw.unsigned_abs();
                if neg > rank {
                    return Err(crate::err::Error::Shape(
                        crate::shapes::error::ShapeError::InvalidAxis { axis: rank, rank },
                    ));
                }
                rank - neg
            };
            if normalized.contains(&norm) {
                return Err(crate::err::Error::Shape(
                    crate::shapes::error::ShapeError::DuplicateAxis { axis: norm },
                ));
            }
            normalized.push(norm);
        }
        Ok(normalized)
    }
}

/// Trait allowing numbers and static cursors to be converted to signed axis indices.
pub trait ToAxisIndex {
    fn to_axis_index(&self) -> isize;
}

impl ToAxisIndex for isize {
    fn to_axis_index(&self) -> isize {
        *self
    }
}

impl ToAxisIndex for usize {
    fn to_axis_index(&self) -> isize {
        *self as isize
    }
}

impl ToAxisIndex for i32 {
    fn to_axis_index(&self) -> isize {
        *self as isize
    }
}

impl ToAxisIndex for Here {
    fn to_axis_index(&self) -> isize {
        Here::INDEX
    }
}

impl<I: StaticCursor> ToAxisIndex for Next<I> {
    fn to_axis_index(&self) -> isize {
        Next::<I>::INDEX
    }
}

impl<I: StaticCursor> ToAxisIndex for FromEnd<I> {
    fn to_axis_index(&self) -> isize {
        FromEnd::<I>::INDEX
    }
}

impl<I: StaticCursor> ToAxisIndex for StaticAxis<I> {
    fn to_axis_index(&self) -> isize {
        I::INDEX
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::prelude::{DimCons, Nil, Shape};
    use typenum::{U0, U1, U2, U3, U4};

    trait Same<T> {}
    impl<T> Same<T> for T {}

    fn assert_shape_eq<S1: Shape, S2: Shape>()
    where
        S1: Same<S2>,
    {
    }

    #[test]
    fn slice_range_output_shape() {
        // idx![1..3, .., 0..2] on [4, 4, 3] → [2, runtime, 2].
        type Input = DimCons<U4, DimCons<U4, DimCons<U3, Nil>>>;
        type IdxT = DimCons<Slice<U1, U3, U2>, DimCons<Ellipsis, DimCons<Slice<U0, U2, U2>, Nil>>>;
        type Expected = DimCons<U2, DimCons<usize, DimCons<U2, Nil>>>;
        assert_shape_eq::<<IdxT as SliceTarget<Input>>::Output, Expected>();
    }

    #[test]
    fn slice_full_passthrough() {
        // idx![.., .., ..] on [4, 4, 3] → [runtime, runtime, runtime].
        type Input = DimCons<U4, DimCons<U4, DimCons<U3, Nil>>>;
        type IdxT = DimCons<Ellipsis, DimCons<Ellipsis, DimCons<Ellipsis, Nil>>>;
        type Expected = DimCons<usize, DimCons<usize, DimCons<usize, Nil>>>;
        assert_shape_eq::<<IdxT as SliceTarget<Input>>::Output, Expected>();
    }
}
