[package]
name = "kindle-viz-plugin-api"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true
publish = false

[dependencies]
kindle-telemetry = { path = "../kindle-telemetry" }
thiserror.workspace = true
ratatui-core = "0.1.2"
ratatui-widgets = "0.3.2"

[lints]
workspace = true
