[package]
description = "Dataset loading and streaming utilities for incin"
repository = "https://github.com/xupremix/incin"
name = "incin-data"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
hf-hub = { version = "0.5.0", default-features = false, features = ["tokio", "rustls-tls", "ureq"] }
incin-core = { version = "0.0.0", path = "../incin-core" }
rayon = "1.12.0"
anyhow = "1.0.103"
rand = "0.8"
ureq = "3.3.0"
flate2 = "1.1.9"

[dev-dependencies]
incin-backends = { path = "../incin-backends", default-features = false, features = ["std", "cpu"] }

[lints]
workspace = true
