//! Generated by tools/build-api-examples.py -- do not edit by hand.
//!
//! Every example the capability reference shows for an operation lives here, so
//! that "this is how you call it" is a claim the compiler checks. An example
//! that stops compiling is an API change the reference has not caught up with,
//! and this file is where that shows up.
#![cfg(feature = "cpu")]
#![allow(unused_variables, unused_imports, clippy::type_complexity)]

use incin::prelude::*;

type B = incin_backends::cpu::CpuBackendImpl;

/// A 2x3 of distinct values, so an example that prints one can be read.
fn t23() -> Result<Tensor<s![2, 3], B>> {
    Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())
}

/// A second operand with the same shape, for the binary families.
fn u23() -> Result<Tensor<s![2, 3], B>> {
    Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())
}

#[test]
fn example_abs() -> Result<()> {
    let t = t23()?;
    let y = t.abs()?;
    Ok(())
}

#[test]
fn example_abs_diff() -> Result<()> {
    let a = t23()?;
    let b = u23()?;
    let y = a.abs_diff(&b)?;
    Ok(())
}

#[test]
fn example_acos() -> Result<()> {
    let t = t23()?;
    let y = t.acos()?;
    Ok(())
}

#[test]
fn example_acosh() -> Result<()> {
    let t = t23()?;
    let y = t.acosh()?;
    Ok(())
}

#[test]
fn example_argmax() -> Result<()> {
    let t = t23()?;
    let positions = t.argmax(axis!(0))?;
    Ok(())
}

#[test]
fn example_argmin() -> Result<()> {
    let t = t23()?;
    let positions = t.argmin(axis!(0))?;
    Ok(())
}

#[test]
fn example_asin() -> Result<()> {
    let t = t23()?;
    let y = t.asin()?;
    Ok(())
}

#[test]
fn example_asinh() -> Result<()> {
    let t = t23()?;
    let y = t.asinh()?;
    Ok(())
}

#[test]
fn example_atan() -> Result<()> {
    let t = t23()?;
    let y = t.atan()?;
    Ok(())
}

#[test]
fn example_atan2() -> Result<()> {
    let a = t23()?;
    let b = u23()?;
    let y = a.atan2(&b)?;
    Ok(())
}

#[test]
fn example_atanh() -> Result<()> {
    let t = t23()?;
    let y = t.atanh()?;
    Ok(())
}

#[test]
fn example_ceil() -> Result<()> {
    let t = t23()?;
    let y = t.ceil()?;
    Ok(())
}

#[test]
fn example_cos() -> Result<()> {
    let t = t23()?;
    let y = t.cos()?;
    Ok(())
}

#[test]
fn example_cosh() -> Result<()> {
    let t = t23()?;
    let y = t.cosh()?;
    Ok(())
}

#[test]
fn example_div_scalar() -> Result<()> {
    let t = t23()?;
    let y = t.div_scalar(2.0)?;
    Ok(())
}

#[test]
fn example_elu() -> Result<()> {
    let t = t23()?;
    let y = t.elu()?;
    Ok(())
}

#[test]
fn example_erf() -> Result<()> {
    let t = t23()?;
    let y = t.erf()?;
    Ok(())
}

#[test]
fn example_exp() -> Result<()> {
    let t = t23()?;
    let y = t.exp()?;
    Ok(())
}

#[test]
fn example_floor() -> Result<()> {
    let t = t23()?;
    let y = t.floor()?;
    Ok(())
}

#[test]
fn example_fmod() -> Result<()> {
    let a = t23()?;
    let b = u23()?;
    let y = a.fmod(&b)?;
    Ok(())
}

#[test]
fn example_frac() -> Result<()> {
    let t = t23()?;
    let y = t.frac()?;
    Ok(())
}

#[test]
fn example_gelu() -> Result<()> {
    let t = t23()?;
    let y = t.gelu()?;
    Ok(())
}

#[test]
fn example_l1_loss() -> Result<()> {
    let prediction = t23()?;
    let target = u23()?;
    let loss = prediction.l1_loss(&target)?;
    Ok(())
}

#[test]
fn example_log() -> Result<()> {
    let t = t23()?;
    let y = t.log()?;
    Ok(())
}

#[test]
fn example_log10() -> Result<()> {
    let t = t23()?;
    let y = t.log10()?;
    Ok(())
}

#[test]
fn example_log2() -> Result<()> {
    let t = t23()?;
    let y = t.log2()?;
    Ok(())
}

#[test]
fn example_logsumexp_keepdim() -> Result<()> {
    let t = t23()?;
    let reduced = t.logsumexp_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_matmul() -> Result<()> {
    let a = t23()?;
    let b = Tensor::<s![3, 2], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let product = a.matmul(&b)?;
    Ok(())
}

#[test]
fn example_max_all() -> Result<()> {
    let t = t23()?;
    let total = t.max_all()?;
    Ok(())
}

#[test]
fn example_max_keepdim() -> Result<()> {
    let t = t23()?;
    let reduced = t.max_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_maximum() -> Result<()> {
    let a = t23()?;
    let b = u23()?;
    let y = a.maximum(&b)?;
    Ok(())
}

#[test]
fn example_mean_all() -> Result<()> {
    let t = t23()?;
    let total = t.mean_all()?;
    Ok(())
}

#[test]
fn example_mean_keepdim() -> Result<()> {
    let t = t23()?;
    let reduced = t.mean_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_min_all() -> Result<()> {
    let t = t23()?;
    let total = t.min_all()?;
    Ok(())
}

#[test]
fn example_min_keepdim() -> Result<()> {
    let t = t23()?;
    let reduced = t.min_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_minimum() -> Result<()> {
    let a = t23()?;
    let b = u23()?;
    let y = a.minimum(&b)?;
    Ok(())
}

#[test]
fn example_mish() -> Result<()> {
    let t = t23()?;
    let y = t.mish()?;
    Ok(())
}

#[test]
fn example_mse_loss() -> Result<()> {
    let prediction = t23()?;
    let target = u23()?;
    let loss = prediction.mse_loss(&target)?;
    Ok(())
}

#[test]
fn example_neg() -> Result<()> {
    let t = t23()?;
    let y = t.neg()?;
    Ok(())
}

#[test]
fn example_powf() -> Result<()> {
    let t = t23()?;
    let y = t.powf(2.0)?;
    Ok(())
}

#[test]
fn example_prod_all() -> Result<()> {
    let t = t23()?;
    let total = t.prod_all()?;
    Ok(())
}

#[test]
fn example_relu() -> Result<()> {
    let t = t23()?;
    let y = t.relu()?;
    Ok(())
}

#[test]
fn example_remainder() -> Result<()> {
    let a = t23()?;
    let b = u23()?;
    let y = a.remainder(&b)?;
    Ok(())
}

#[test]
fn example_require_grad() -> Result<()> {
    let t = t23()?;
    let tracked = t.require_grad();
    Ok(())
}

#[test]
fn example_round() -> Result<()> {
    let t = t23()?;
    let y = t.round()?;
    Ok(())
}

#[test]
fn example_rsqrt() -> Result<()> {
    let t = t23()?;
    let y = t.rsqrt()?;
    Ok(())
}

#[test]
fn example_sigmoid() -> Result<()> {
    let t = t23()?;
    let y = t.sigmoid()?;
    Ok(())
}

#[test]
fn example_sign() -> Result<()> {
    let t = t23()?;
    let y = t.sign()?;
    Ok(())
}

#[test]
fn example_sin() -> Result<()> {
    let t = t23()?;
    let y = t.sin()?;
    Ok(())
}

#[test]
fn example_sinh() -> Result<()> {
    let t = t23()?;
    let y = t.sinh()?;
    Ok(())
}

#[test]
fn example_sqrt() -> Result<()> {
    let t = t23()?;
    let y = t.sqrt()?;
    Ok(())
}

#[test]
fn example_step() -> Result<()> {
    let t = t23()?;
    let y = t.step()?;
    Ok(())
}

#[test]
fn example_sub_scalar() -> Result<()> {
    let t = t23()?;
    let y = t.sub_scalar(2.0)?;
    Ok(())
}

#[test]
fn example_sum_all() -> Result<()> {
    let t = t23()?;
    let total = t.sum_all()?;
    Ok(())
}

#[test]
fn example_sum_keepdim() -> Result<()> {
    let t = t23()?;
    let reduced = t.sum_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_swish() -> Result<()> {
    let t = t23()?;
    let y = t.swish()?;
    Ok(())
}

#[test]
fn example_tan() -> Result<()> {
    let t = t23()?;
    let y = t.tan()?;
    Ok(())
}

#[test]
fn example_tanh() -> Result<()> {
    let t = t23()?;
    let y = t.tanh()?;
    Ok(())
}

#[test]
fn example_trunc() -> Result<()> {
    let t = t23()?;
    let y = t.trunc()?;
    Ok(())
}
