//! Generated by tools/build-api-examples.py -- do not edit by hand.
//!
//! Every example the capability reference shows for an operation lives here, so
//! that "this is how you call it" is a claim the compiler checks. An example
//! that stops compiling is an API change the reference has not caught up with,
//! and this file is where that shows up.
#![cfg(feature = "cpu")]
#![allow(unused_variables, unused_imports, clippy::type_complexity)]

use incin::prelude::*;

type B = incin_backends::cpu::CpuBackendImpl;

#[test]
fn example_abs() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.abs()?;
    Ok(())
}

#[test]
fn example_abs_diff() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.abs_diff(&b)?;
    Ok(())
}

#[test]
fn example_acos() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.acos()?;
    Ok(())
}

#[test]
fn example_acosh() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.acosh()?;
    Ok(())
}

#[test]
fn example_add() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.try_add(&b)?;
    Ok(())
}

#[test]
fn example_add_scalar() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.add_scalar(2.0)?;
    Ok(())
}

#[test]
fn example_arange() -> Result<()> {
    let t = Tensor::<s![6], B>::arange(0.0, 6.0, ())?;
    Ok(())
}

#[test]
fn example_argmax() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let positions = t.argmax(axis!(0))?;
    Ok(())
}

#[test]
fn example_argmin() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let positions = t.argmin(axis!(0))?;
    Ok(())
}

#[test]
fn example_argsort() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let order = t.argsort(1, false)?;
    Ok(())
}

#[test]
fn example_asin() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.asin()?;
    Ok(())
}

#[test]
fn example_asinh() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.asinh()?;
    Ok(())
}

#[test]
fn example_atan() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.atan()?;
    Ok(())
}

#[test]
fn example_atan2() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.atan2(&b)?;
    Ok(())
}

#[test]
fn example_atanh() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.atanh()?;
    Ok(())
}

#[test]
fn example_backward() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let tracked = t.require_grad();
    let loss = tracked.sum_all()?;
    let gradients = loss.backward()?;
    Ok(())
}

#[test]
fn example_ceil() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.ceil()?;
    Ok(())
}

#[test]
fn example_cmp_eq() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let mask = a.eq(&b)?;
    Ok(())
}

#[test]
fn example_cmp_ge() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let mask = a.ge(&b)?;
    Ok(())
}

#[test]
fn example_cmp_gt() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let mask = a.gt(&b)?;
    Ok(())
}

#[test]
fn example_cmp_le() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let mask = a.le(&b)?;
    Ok(())
}

#[test]
fn example_cmp_lt() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let mask = a.lt(&b)?;
    Ok(())
}

#[test]
fn example_cmp_ne() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let mask = a.ne(&b)?;
    Ok(())
}

#[test]
fn example_cos() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.cos()?;
    Ok(())
}

#[test]
fn example_cosh() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.cosh()?;
    Ok(())
}

#[test]
fn example_detach() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let tracked = t.require_grad();
    let plain = tracked.detach();
    Ok(())
}

#[test]
fn example_div() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.try_div(&b)?;
    Ok(())
}

#[test]
fn example_div_scalar() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.div_scalar(2.0)?;
    Ok(())
}

#[test]
fn example_elu() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.elu()?;
    Ok(())
}

#[test]
fn example_erf() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.erf()?;
    Ok(())
}

#[test]
fn example_exp() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.exp()?;
    Ok(())
}

#[test]
fn example_float_to_vec1() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let host = t.to_vec1::<f32>()?;
    Ok(())
}

#[test]
fn example_floor() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.floor()?;
    Ok(())
}

#[test]
fn example_fmod() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.fmod(&b)?;
    Ok(())
}

#[test]
fn example_frac() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.frac()?;
    Ok(())
}

#[test]
fn example_full() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::full(1.5, ())?;
    Ok(())
}

#[test]
fn example_gelu() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.gelu()?;
    Ok(())
}

#[test]
fn example_int_to_vec1() -> Result<()> {
    let t = Tensor::<s![3], B, i64>::from_slice(&[1, 2, 3], ())?;
    let host = t.to_vec1::<i64>()?;
    Ok(())
}

#[test]
fn example_l1_loss() -> Result<()> {
    let prediction = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let target = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let loss = prediction.l1_loss(&target)?;
    Ok(())
}

#[test]
fn example_linspace() -> Result<()> {
    let t = Tensor::<s![5], B>::linspace(0.0, 1.0, ())?;
    Ok(())
}

#[test]
fn example_log() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.log()?;
    Ok(())
}

#[test]
fn example_log10() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.log10()?;
    Ok(())
}

#[test]
fn example_log2() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.log2()?;
    Ok(())
}

#[test]
fn example_logical_and() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let left = a.gt(&b)?;
    let right = b.gt(&a)?;
    let y = left.logical_and(&right)?;
    Ok(())
}

#[test]
fn example_logical_not() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let mask = a.gt(&b)?;
    let y = mask.logical_not()?;
    Ok(())
}

#[test]
fn example_logical_or() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let left = a.gt(&b)?;
    let right = b.gt(&a)?;
    let y = left.logical_or(&right)?;
    Ok(())
}

#[test]
fn example_logsumexp_dim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.logsumexp(axis!(0))?;
    Ok(())
}

#[test]
fn example_logsumexp_keepdim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.logsumexp_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_matmul() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![3, 2], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let product = a.matmul(&b)?;
    Ok(())
}

#[test]
fn example_max_all() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let total = t.max_all()?;
    Ok(())
}

#[test]
fn example_max_dim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.max(axis!(0))?;
    Ok(())
}

#[test]
fn example_max_keepdim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.max_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_maximum() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.maximum(&b)?;
    Ok(())
}

#[test]
fn example_mean_all() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let total = t.mean_all()?;
    Ok(())
}

#[test]
fn example_mean_dim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.mean(axis!(0))?;
    Ok(())
}

#[test]
fn example_mean_keepdim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.mean_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_min_all() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let total = t.min_all()?;
    Ok(())
}

#[test]
fn example_min_dim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.min(axis!(0))?;
    Ok(())
}

#[test]
fn example_min_keepdim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.min_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_minimum() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.minimum(&b)?;
    Ok(())
}

#[test]
fn example_mish() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.mish()?;
    Ok(())
}

#[test]
fn example_mse_loss() -> Result<()> {
    let prediction = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let target = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let loss = prediction.mse_loss(&target)?;
    Ok(())
}

#[test]
fn example_mul() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.try_mul(&b)?;
    Ok(())
}

#[test]
fn example_mul_scalar() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.mul_scalar(2.0)?;
    Ok(())
}

#[test]
fn example_neg() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.neg()?;
    Ok(())
}

#[test]
fn example_ones() -> Result<()> {
    let t = Cpu.ones(shape![2, 3])?;
    Ok(())
}

#[test]
fn example_powf() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.powf(2.0)?;
    Ok(())
}

#[test]
fn example_prod_all() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let total = t.prod_all()?;
    Ok(())
}

#[test]
fn example_rand() -> Result<()> {
    let t = Cpu.rand(shape![2, 3])?;
    Ok(())
}

#[test]
fn example_randn() -> Result<()> {
    let t = Cpu.randn(shape![2, 3])?;
    Ok(())
}

#[test]
fn example_relu() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.relu()?;
    Ok(())
}

#[test]
fn example_remainder() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.remainder(&b)?;
    Ok(())
}

#[test]
fn example_require_grad() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let tracked = t.require_grad();
    Ok(())
}

#[test]
fn example_round() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.round()?;
    Ok(())
}

#[test]
fn example_rsqrt() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.rsqrt()?;
    Ok(())
}

#[test]
fn example_sigmoid() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.sigmoid()?;
    Ok(())
}

#[test]
fn example_sign() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.sign()?;
    Ok(())
}

#[test]
fn example_sin() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.sin()?;
    Ok(())
}

#[test]
fn example_sinh() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.sinh()?;
    Ok(())
}

#[test]
fn example_sort() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let (values, order) = t.sort(1, false)?;
    Ok(())
}

#[test]
fn example_sqrt() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.sqrt()?;
    Ok(())
}

#[test]
fn example_step() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.step()?;
    Ok(())
}

#[test]
fn example_sub() -> Result<()> {
    let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;
    let y = a.try_sub(&b)?;
    Ok(())
}

#[test]
fn example_sub_scalar() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.sub_scalar(2.0)?;
    Ok(())
}

#[test]
fn example_sum_all() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let total = t.sum_all()?;
    Ok(())
}

#[test]
fn example_sum_dim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.sum(axis!(0))?;
    Ok(())
}

#[test]
fn example_sum_keepdim() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let reduced = t.sum_keepdim(axis!(0))?;
    Ok(())
}

#[test]
fn example_swish() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.swish()?;
    Ok(())
}

#[test]
fn example_tan() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.tan()?;
    Ok(())
}

#[test]
fn example_tanh() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.tanh()?;
    Ok(())
}

#[test]
fn example_topk() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let (values, indices) = t.topk(2, axis!(1), true)?;
    Ok(())
}

#[test]
fn example_trunc() -> Result<()> {
    let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;
    let y = t.trunc()?;
    Ok(())
}

#[test]
fn example_zeros() -> Result<()> {
    let t = Cpu.zeros(shape![2, 3])?;
    Ok(())
}
