[package]
authors = ["xupremix <xupremix.me@gmail.com>"]
name = "kindle"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["std", "cpu"]
std = ["kindle-core/std", "kindle-macros/std", "kindle-backends/std"]
nightly = ["kindle-core/nightly", "kindle-macros/nightly"]
cpu = ["kindle-backends/cpu"]
cuda = ["kindle-core/cuda", "kindle-backends/cuda"]
wgpu = ["kindle-backends/wgpu"]
legacy = ["kindle-backends/legacy"]

[dependencies]
kindle-core = { path = "../kindle-core", version = "0.1.0", default-features = false }
kindle-macros = { path = "../kindle-macros/", version = "0.1.0", default-features = false }
kindle-backends = { path = "../kindle-backends", default-features = false }
kindle-data = { version = "0.1.0", path = "../kindle-data" }

[dev-dependencies]
candle-core = { workspace = true }
hashbrown = "0.14.5"
bytemuck = "1"
