[package]
authors = ["xupremix <xupremix.me@gmail.com>"]
name = "kindle"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["std", "candle"]
std = ["kindle-core/std", "kindle-macros/std"]
nightly = ["kindle-core/nightly", "kindle-macros/nightly"]
cuda = ["kindle-core/cuda", "kindle-backends/cuda"]
metal = ["kindle-core/metal", "kindle-backends/metal"]
candle = ["kindle-backends/candle"]
ndarray = ["kindle-backends/ndarray"]
burn = ["kindle-backends/burn"]

[dependencies]
kindle-core = { path = "../kindle-core", version = "0.1.0", default-features = false }
kindle-macros = { path = "../kindle-macros/", version = "0.1.0", default-features = false }
kindle-backends = { path = "../kindle-backends", default-features = false }
kindle-data = { version = "0.1.0", path = "../kindle-data" }
anyhow = "1.0.103"

[dev-dependencies]
candle-core = { workspace = true }
hashbrown = "0.14.5"
