//! Machine-checked proof that the canonical catalog covers the operation
//! surface it claims to.
//!
//! The reviewed prose in `audit-evidence/FND-004/` records *why* each mapping is
//! correct. This file records *that* the mapping is still complete, by reading
//! the production source tree contains none of the retired operation-family
//! compatibility names.

#![cfg(feature = "std")]

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use incin_core::exec::OPERATION_CATALOG;


fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("workspace root")
}


#[test]
fn legacy_operation_families_are_absent_from_production_source() {
    fn visit(path: &Path, forbidden: &[&str]) {
        if path.is_dir() {
            for entry in std::fs::read_dir(path).expect("read source directory") {
                visit(&entry.expect("source entry").path(), forbidden);
            }
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            let source = std::fs::read_to_string(path).expect("read Rust source");
            for name in forbidden {
                assert!(!source.contains(name), "forbidden legacy name `{name}` in {}", path.display());
            }
        }
    }

    let root = repo_root();
    let forbidden = [
        "NumericOps", "FloatOps", "TensorOps", "ReductionOps", "ModuleOps",
        "QuantizedOps", "CreationOps", "LossOps", "__backend_compat",
    ];
    for source_root in [
        root.join("crates/incin-core/src"),
        root.join("crates/incin-backends/src"),
        root.join("crates/incin/src"),
    ] {
        visit(&source_root, &forbidden);
    }
}

/// Every stable operation family the run promised to cover is represented.
///
/// A catalog that silently dropped, say, every loss or every optimizer entry
/// point would still satisfy the per-method check above if the traits were
/// edited in the same commit. This pins the families themselves.
#[test]
fn every_stable_operation_family_is_represented() {
    use incin_core::exec::catalog::SemanticProfile;

    let mut seen: BTreeSet<&'static str> = BTreeSet::new();
    for row in OPERATION_CATALOG {
        seen.insert(match row.profile {
            SemanticProfile::Creation => "creation",
            SemanticProfile::Transfer => "transfer",
            SemanticProfile::Autograd => "autograd",
            SemanticProfile::Module | SemanticProfile::Composite => "module",
            SemanticProfile::Loss => "loss",
            SemanticProfile::Optimizer => "optimizer",
            SemanticProfile::Quantized => "quantized",
            SemanticProfile::Reduction | SemanticProfile::IndexReduction => "reduction",
            _ => "tensor",
        });
    }

    for family in [
        "creation",
        "transfer",
        "autograd",
        "module",
        "loss",
        "optimizer",
        "quantized",
        "reduction",
        "tensor",
    ] {
        assert!(seen.contains(family), "no catalog row covers {family}");
    }
}

/// No exact operation may be represented only by a broad family identity.
#[test]
fn no_catalog_row_is_a_broad_family_identity() {
    for row in OPERATION_CATALOG {
        assert!(
            row.operation.is_exact(),
            "{} is a broad family, not an executable identity",
            row.operation,
        );
        assert_ne!(
            row.operation, row.family,
            "{} collapses its own family into its identity",
            row.operation,
        );
    }
}

/// Regenerate (or verify) the reviewed inventory document.
///
/// Run with `INCIN_DOCS=overwrite` to refresh it after a catalog change.
#[test]
fn operation_inventory_document_matches_the_catalog() {
    let path = repo_root().join("audit-evidence/FND-004/operation-inventory.md");
    let expected = render_inventory();
    let actual = std::fs::read_to_string(&path).unwrap_or_default();
    if actual == expected {
        return;
    }
    if std::env::var("INCIN_DOCS").as_deref() == Ok("overwrite") {
        std::fs::create_dir_all(path.parent().expect("evidence directory")).expect("mkdir");
        std::fs::write(&path, expected).expect("inventory document is writable");
        return;
    }
    panic!(
        "{} is stale; regenerate with `INCIN_DOCS=overwrite cargo test -p incin-core --test \
         operation_inventory`",
        path.display(),
    );
}

fn render_inventory() -> String {
    use std::fmt::Write as _;

    let mut out = String::from(
        "# FND-004 canonical operation inventory\n\n\
         Generated by `cargo test -p incin-core --test operation_inventory`. The Rust catalog in \
         `crates/incin-core/src/operation_catalog.rs` is authoritative; this file is a review \
         artifact and is verified against the catalog on every test run.\n\n\
         Each row is one exact executable identity. Families classify rows and never imply backend \
         support.\n\n",
    );

    let _ = writeln!(out, "Total exact operations: {}\n", OPERATION_CATALOG.len());

    let mut by_source: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for row in OPERATION_CATALOG {
        by_source
            .entry(row.legacy_source)
            .or_default()
            .push(row.name);
    }

    let _ = writeln!(
        out,
        "| Exact identity | Family | Profile | Descriptor | Attributes | Inputs | Outputs | \
         Legacy source |",
    );
    let _ = writeln!(out, "|---|---|---|---|---|---|---|---|");
    for row in OPERATION_CATALOG {
        let arity = |range: &core::ops::RangeInclusive<usize>| {
            if *range.end() == usize::MAX {
                format!("{}-many", range.start())
            } else {
                format!("{}-{}", range.start(), range.end())
            }
        };
        let _ = writeln!(
            out,
            "| `{}` | `{:?}` | `{:?}` | `{}` | `{}` | {} | {} | `{}` |",
            row.name,
            row.family,
            row.profile,
            row.descriptor,
            row.attributes,
            arity(&row.input_arity),
            arity(&row.output_arity),
            row.legacy_source,
        );
    }
    out
}
