[package]
authors = ["xupremix <xupremix.me@gmail.com>"]
name = "kindle-core"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = []
nightly = []
cuda = ["candle-core/cuda", "candle-nn/cuda"]
metal = []
# metal = ["candle-core/metal", "candle-nn/metal"]

# candle = ["dep:candle-core", "dep:candle-nn"]
# cuda = ["dep:candle-core?/cuda", "dep:candle-nn?/cuda"]

[dependencies]
kindle-macros = { path = "../kindle-macros", version = "0.1.0", default-features = false }
candle-core = { workspace = true }
candle-nn = { workspace = true }
thiserror = { workspace = true }
half = { workspace = true }
# miette = { workspace = true }
