[package]
authors = ["xupremix <xupremix.me@gmail.com>"]
name = "kindle-core"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = []
nightly = []
cuda = []
metal = []

# candle = ["dep:candle-core", "dep:candle-nn"]
# cuda = ["dep:candle-core?/cuda", "dep:candle-nn?/cuda"]

[dependencies]
kindle-macros = { path = "../kindle-macros", version = "0.1.0", default-features = false }
thiserror = { workspace = true }
half = { workspace = true }
anyhow = "1.0.103"
typenum = "1.20.1"
safetensors = "0.4.1"
bincode = "1.3.3"
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
trybuild = "1.0.117"
# miette = { workspace = true }
