//! Generate `README.md`'s feature tables from the Cargo manifests (`UX-013`).
//!
//! `PROPOSALS.md` §2.10: "Do not maintain independent handwritten support
//! tables that can drift from code." A Cargo feature's name, its default-ness
//! and what it enables are facts about a manifest, so the manifest is what this
//! reads. It had already drifted: the table listed `candle` as the third-party
//! backend feature, which `GOV-006` renamed to `external-candle` and left as a
//! deprecated alias, while the installation example four lines below used the
//! new name.
//!
//! The "Purpose" column comes from the `#` comment above each feature in the
//! manifest - that comment is the only prose description of a feature that lives
//! beside the thing it describes, so making it the source means there is one
//! copy rather than two. The capability tables have a different authority (Rust
//! statics) and are generated by `incin_backends::capability_docs` instead.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const README: &str = "README.md";
const BEGIN_FACADE: &str = "<!-- BEGIN GENERATED: facade-features -->";
const END_FACADE: &str = "<!-- END GENERATED: facade-features -->";
const BEGIN_CRATES: &str = "<!-- BEGIN GENERATED: crate-features -->";
const END_CRATES: &str = "<!-- END GENERATED: crate-features -->";

/// Workspace members whose features the README lists, in the order it lists
/// them. A member absent here is reported rather than silently omitted, so a new
/// crate cannot join the workspace and stay out of the documentation.
const DOCUMENTED: &[&str] = &[
    "incin",
    "incin-backends",
    "incin-core",
    "incin-macros",
    "incin-diagnostics",
    "incin-data",
    "incin-telemetry",
    "incin-viz",
    "incin-viz-plugin-api",
    "incin-lsp",
];

/// One Cargo feature, as declared.
struct Feature {
    name: String,
    enables: Vec<String>,
    /// The `#` comment block immediately above the declaration, if any.
    purpose: Option<String>,
}

/// One crate's `[features]` table.
struct Manifest {
    package: String,
    default: Vec<String>,
    features: Vec<Feature>,
}

pub fn run(check: bool) -> ExitCode {
    let root = repo_root();
    let manifests: Vec<Manifest> = match DOCUMENTED
        .iter()
        .map(|name| read_manifest(&root, name))
        .collect()
    {
        Ok(manifests) => manifests,
        Err(message) => {
            eprintln!("docs: {message}");
            return ExitCode::FAILURE;
        }
    };

    let facade = match manifests.iter().find(|m| m.package == "incin") {
        Some(facade) => facade,
        None => {
            eprintln!("docs: the workspace has no `incin` package to document");
            return ExitCode::FAILURE;
        }
    };

    let path = root.join(README);
    let current = match fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) => {
            eprintln!("docs: cannot read {}: {error}", path.display());
            return ExitCode::FAILURE;
        }
    };

    let mut updated = match splice(&current, BEGIN_FACADE, END_FACADE, &facade_table(facade)) {
        Ok(text) => text,
        Err(message) => {
            eprintln!("docs: {message}");
            return ExitCode::FAILURE;
        }
    };
    updated = match splice(&updated, BEGIN_CRATES, END_CRATES, &crate_list(&manifests)) {
        Ok(text) => text,
        Err(message) => {
            eprintln!("docs: {message}");
            return ExitCode::FAILURE;
        }
    };

    if updated == current {
        println!("docs ok: {README} matches the manifests");
        return ExitCode::SUCCESS;
    }
    if check {
        eprintln!(
            "docs: {README}'s generated regions are stale.\n\
             Regenerate them with `cargo xtask docs`."
        );
        return ExitCode::FAILURE;
    }
    match fs::write(&path, updated) {
        Ok(()) => {
            println!("docs: rewrote {README}");
            ExitCode::SUCCESS
        }
        Err(error) => {
            eprintln!("docs: cannot write {}: {error}", path.display());
            ExitCode::FAILURE
        }
    }
}

/// Every feature a default build ends up with, not just the ones `default`
/// names.
///
/// `default = ["std", "cpu"]` is the *direct* list; a feature those two enable
/// is equally on by default, and a table that answered from the direct list
/// alone would call it optional. Today the closure and the direct list happen to
/// coincide, which is exactly why computing it is worth doing now rather than
/// after the first feature that makes them differ.
fn default_closure(manifest: &Manifest) -> Vec<String> {
    let mut reached = manifest.default.clone();
    let mut index = 0;
    while index < reached.len() {
        let name = reached[index].clone();
        index += 1;
        let Some(feature) = manifest.features.iter().find(|f| f.name == name) else {
            continue;
        };
        for enabled in &feature.enables {
            // `dep:x` activates an optional dependency and `x/y` a feature of
            // one; neither names a feature of this crate.
            if enabled.contains('/') || enabled.starts_with("dep:") {
                continue;
            }
            if !reached.contains(enabled) {
                reached.push(enabled.clone());
            }
        }
    }
    reached
}

/// The facade's own feature matrix: what a `incin = "..."` line can turn on.
fn facade_table(facade: &Manifest) -> String {
    let on_by_default = default_closure(facade);
    let mut out = String::from("| Feature | Default | Purpose |\n|---|:--:|---|\n");
    for feature in &facade.features {
        let default = if on_by_default.contains(&feature.name) {
            "yes"
        } else {
            "no"
        };
        // Not a panic: the generator's job is to render the manifest, and a
        // feature with no comment is a documentation gap to show in the table,
        // not a reason to leave the table unwritten.
        let purpose = feature.purpose.as_deref().unwrap_or(
            "*undocumented — add a `#` comment above this feature in `crates/incin/Cargo.toml`*",
        );
        let _ = writeln!(out, "| `{}` | {} | {} |", feature.name, default, purpose);
    }
    out
}

/// Every other workspace crate, one line each.
fn crate_list(manifests: &[Manifest]) -> String {
    let mut out = String::new();
    let mut featureless: Vec<&str> = Vec::new();
    for manifest in manifests {
        if manifest.package == "incin" {
            continue;
        }
        if manifest.features.is_empty() {
            featureless.push(&manifest.package);
            continue;
        }
        let optional: Vec<String> = manifest
            .features
            .iter()
            .filter(|f| !manifest.default.contains(&f.name))
            .map(|f| format!("`{}`", f.name))
            .collect();
        let defaults = if manifest.default.is_empty() {
            "no default features".to_string()
        } else {
            format!("defaults to `{}`", manifest.default.join(","))
        };
        if optional.is_empty() {
            let _ = writeln!(out, "- `{}`: {defaults}.", manifest.package);
        } else {
            let _ = writeln!(
                out,
                "- `{}`: {defaults}; optional {}.",
                manifest.package,
                list(&optional)
            );
        }
    }
    if !featureless.is_empty() {
        let names: Vec<String> = featureless.iter().map(|n| format!("`{n}`")).collect();
        let _ = writeln!(out, "- {} expose no Cargo features.", list(&names));
    }
    out
}

/// `a`, `a and b`, `a, b, and c` - the form the README already used.
fn list(items: &[String]) -> String {
    match items {
        [] => String::new(),
        [one] => one.clone(),
        [first, second] => format!("{first} and {second}"),
        [rest @ .., last] => format!("{}, and {last}", rest.join(", ")),
    }
}

/// Replaces the text between `begin` and `end`, keeping the markers.
fn splice(text: &str, begin: &str, end: &str, body: &str) -> Result<String, String> {
    let start = text
        .find(begin)
        .ok_or_else(|| format!("{README} is missing the marker `{begin}`"))?;
    let stop = text
        .find(end)
        .ok_or_else(|| format!("{README} is missing the marker `{end}`"))?;
    if stop < start {
        return Err(format!("{README} has `{end}` before `{begin}`"));
    }
    Ok(format!(
        "{}{begin}\n{body}{}",
        &text[..start],
        &text[stop..]
    ))
}

/// Reads one crate's `[features]` table, with the comment above each feature.
///
/// Parsed line by line rather than with the `toml` crate because comments are
/// exactly what this needs and a TOML parser discards them.
fn read_manifest(root: &Path, package: &str) -> Result<Manifest, String> {
    let path = root.join("crates").join(package).join("Cargo.toml");
    let text = fs::read_to_string(&path)
        .map_err(|error| format!("cannot read {}: {error}", path.display()))?;

    let mut features = Vec::new();
    let mut default = Vec::new();
    let mut comment: Vec<String> = Vec::new();
    let mut in_features = false;

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_features = trimmed == "[features]";
            comment.clear();
            continue;
        }
        if !in_features {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix('#') {
            comment.push(rest.trim().to_string());
            continue;
        }
        if trimmed.is_empty() {
            comment.clear();
            continue;
        }
        let Some((name, values)) = trimmed.split_once('=') else {
            continue;
        };
        let name = name.trim().to_string();
        let enables = parse_array(values);
        if name == "default" {
            default = enables;
        } else {
            features.push(Feature {
                name,
                enables,
                purpose: (!comment.is_empty()).then(|| comment.join(" ")),
            });
        }
        comment.clear();
    }

    Ok(Manifest {
        package: package.to_string(),
        default,
        features,
    })
}

/// The contents of a single-line `["a", "b"]`, which is how every feature in
/// this workspace is written.
fn parse_array(text: &str) -> Vec<String> {
    text.trim()
        .trim_start_matches('[')
        .trim_end_matches(']')
        .split(',')
        .map(|item| item.trim().trim_matches('"').to_string())
        .filter(|item| !item.is_empty())
        .collect()
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the xtask manifest directory has a parent")
        .to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_feature_carries_the_comment_written_above_it() {
        let facade = read_manifest(&repo_root(), "incin").expect("the facade manifest is readable");
        let cpu = facade
            .features
            .iter()
            .find(|f| f.name == "cpu")
            .expect("the facade has a `cpu` feature");
        assert_eq!(
            cpu.purpose.as_deref(),
            Some("Enables the built-in CPU backend. This is the only default backend.")
        );
        assert_eq!(cpu.enables, ["incin-backends/cpu"]);
    }

    /// A feature declared over several lines would silently lose its enables
    /// list, so this pins that the workspace does not have one.
    #[test]
    fn every_documented_feature_is_declared_on_one_line() {
        for package in DOCUMENTED {
            let manifest =
                read_manifest(&repo_root(), package).expect("every documented crate is readable");
            for feature in &manifest.features {
                assert!(
                    !feature.name.contains('\n') && !feature.name.contains('['),
                    "{package}'s `{}` is not a single-line declaration",
                    feature.name
                );
            }
        }
    }

    #[test]
    fn the_default_set_is_read_from_the_manifest() {
        let facade = read_manifest(&repo_root(), "incin").expect("the facade manifest is readable");
        assert_eq!(facade.default, ["std", "cpu"]);
    }

    #[test]
    fn splicing_keeps_the_markers_and_replaces_only_the_body() {
        let text = format!("before\n{BEGIN_FACADE}\nstale\n{END_FACADE}\nafter\n");
        let spliced = splice(&text, BEGIN_FACADE, END_FACADE, "fresh\n").expect("markers present");
        assert_eq!(
            spliced,
            format!("before\n{BEGIN_FACADE}\nfresh\n{END_FACADE}\nafter\n")
        );
    }

    /// Each marker is checked on its own. Asserting only that a file with
    /// neither marker fails leaves the `begin` lookup untested - a mutant that
    /// defaults a missing `begin` to offset zero still errors, because the
    /// `end` lookup catches it, and the generated block would then have been
    /// written over the top of the file.
    #[test]
    fn a_missing_marker_is_an_error_rather_than_an_append() {
        assert!(splice("no markers here", BEGIN_FACADE, END_FACADE, "x").is_err());
        assert!(
            splice(
                &format!("only the end\n{END_FACADE}\n"),
                BEGIN_FACADE,
                END_FACADE,
                "x"
            )
            .is_err(),
            "a missing `begin` must fail rather than splice at the top of the file"
        );
        assert!(
            splice(
                &format!("only the beginning\n{BEGIN_FACADE}\n"),
                BEGIN_FACADE,
                END_FACADE,
                "x"
            )
            .is_err(),
            "a missing `end` must fail rather than truncate the file"
        );
    }

    /// `default_closure` cannot be exercised against the real facade, whose
    /// `default = ["std", "cpu"]` reaches nothing further - the two answers
    /// coincide, so a version that never walked the graph would pass. This is
    /// the fixture where they differ.
    #[test]
    fn a_feature_reached_through_a_default_is_also_a_default() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: vec!["cpu".to_string()],
            features: vec![
                Feature {
                    name: "cpu".to_string(),
                    enables: vec!["std".to_string(), "backend/cpu".to_string()],
                    purpose: None,
                },
                Feature {
                    name: "std".to_string(),
                    enables: vec!["dep:serde".to_string()],
                    purpose: None,
                },
                Feature {
                    name: "cuda".to_string(),
                    enables: vec![],
                    purpose: None,
                },
            ],
        };
        let closure = default_closure(&manifest);
        assert!(closure.contains(&"cpu".to_string()));
        assert!(
            closure.contains(&"std".to_string()),
            "`std` is enabled by a default feature and so is itself a default"
        );
        assert!(
            !closure.contains(&"cuda".to_string()),
            "an unreachable feature must not be reported as a default"
        );
        assert!(
            !closure
                .iter()
                .any(|f| f.contains('/') || f.starts_with("dep:")),
            "a dependency activation is not a feature of this crate"
        );
    }

    /// Computing the closure is not the same as using it. Against the real
    /// facade the two answers coincide, so the table has to be rendered from a
    /// manifest where they do not.
    #[test]
    fn the_table_marks_a_transitively_enabled_feature_as_a_default() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: vec!["cpu".to_string()],
            features: vec![
                Feature {
                    name: "cpu".to_string(),
                    enables: vec!["std".to_string()],
                    purpose: Some("the backend".to_string()),
                },
                Feature {
                    name: "std".to_string(),
                    enables: vec![],
                    purpose: Some("the standard library".to_string()),
                },
                Feature {
                    name: "cuda".to_string(),
                    enables: vec![],
                    purpose: Some("the other backend".to_string()),
                },
            ],
        };
        let table = facade_table(&manifest);
        assert!(table.contains("| `cpu` | yes |"), "got:\n{table}");
        assert!(
            table.contains("| `std` | yes |"),
            "`std` is enabled by a default feature, so a default build has it:\n{table}"
        );
        assert!(table.contains("| `cuda` | no |"), "got:\n{table}");
    }

    /// A feature that enables itself, directly or through a cycle, must not
    /// hang the generator.
    #[test]
    fn a_cyclic_feature_graph_terminates() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: vec!["a".to_string()],
            features: vec![
                Feature {
                    name: "a".to_string(),
                    enables: vec!["b".to_string()],
                    purpose: None,
                },
                Feature {
                    name: "b".to_string(),
                    enables: vec!["a".to_string()],
                    purpose: None,
                },
            ],
        };
        assert_eq!(default_closure(&manifest).len(), 2);
    }

    #[test]
    fn the_list_joiner_matches_the_prose_it_replaces() {
        let one = ["`a`".to_string()];
        let two = ["`a`".to_string(), "`b`".to_string()];
        let three = ["`a`".to_string(), "`b`".to_string(), "`c`".to_string()];
        assert_eq!(list(&one), "`a`");
        assert_eq!(list(&two), "`a` and `b`");
        assert_eq!(list(&three), "`a`, `b`, and `c`");
    }
}
