//! Generate `README.md`'s feature tables from the Cargo manifests (`UX-013`).
//!
//! `PROPOSALS.md` §2.10: "Do not maintain independent handwritten support
//! tables that can drift from code." A Cargo feature's name, its default-ness
//! and what it enables are facts about a manifest, so the manifest is what this
//! reads. It had already drifted: the table listed `candle` as the third-party
//! backend feature, which `GOV-006` renamed to `external-candle` and left as a
//! deprecated alias, while the installation example four lines below used the
//! new name.
//!
//! The "Purpose" column comes from the `#` comment above each feature in the
//! manifest - that comment is the only prose description of a feature that lives
//! beside the thing it describes, so making it the source means there is one
//! copy rather than two. The capability tables have a different authority (Rust
//! statics) and are generated by `incin_backends::capability_docs` instead.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const README: &str = "README.md";
const BEGIN_FACADE: &str = "<!-- BEGIN GENERATED: facade-features -->";
const END_FACADE: &str = "<!-- END GENERATED: facade-features -->";
const BEGIN_CRATES: &str = "<!-- BEGIN GENERATED: crate-features -->";
const END_CRATES: &str = "<!-- END GENERATED: crate-features -->";
const FEATURE_MATRIX: &str = "docs/FEATURE_MATRIX.md";
const BOOK_FEATURES: &str = "docs/book/src/feature_flags.md";
const BEGIN_INVENTORY: &str = "<!-- BEGIN GENERATED: feature-inventory -->";
const END_INVENTORY: &str = "<!-- END GENERATED: feature-inventory -->";

/// Workspace members whose features the README lists, in the order it lists
/// them. A member absent here is reported rather than silently omitted, so a new
/// crate cannot join the workspace and stay out of the documentation.
const DOCUMENTED: &[&str] = &[
    "incin",
    "incin-backends",
    "incin-core",
    "incin-macros",
    "incin-diagnostics",
    "incin-data",
    "incin-telemetry",
    "incin-viz",
    "incin-viz-plugin-api",
    "incin-lsp",
];

/// One Cargo feature, as declared.
struct Feature {
    name: String,
    enables: Vec<String>,
    /// The `#` comment block immediately above the declaration, if any.
    purpose: Option<String>,
    contract: FeatureContract,
}

/// Release-support metadata co-located with the Cargo feature declaration.
#[derive(Clone)]
struct FeatureContract {
    tier: String,
    owner: String,
    prerequisites: Vec<String>,
    hardware: String,
    incompatibilities: Vec<String>,
}

/// One crate's `[features]` table.
struct Manifest {
    package: String,
    default: Vec<String>,
    features: Vec<Feature>,
    docsrs: Option<DocsRs>,
}

struct DocsRs {
    all_features: bool,
    features: Vec<String>,
}

pub fn run(check: bool) -> ExitCode {
    let root = repo_root();
    let manifests = match load_manifests(&root) {
        Ok(manifests) => manifests,
        Err(message) => {
            eprintln!("docs: {message}");
            return ExitCode::FAILURE;
        }
    };

    let facade = match manifests.iter().find(|m| m.package == "incin") {
        Some(facade) => facade,
        None => {
            eprintln!("docs: the workspace has no `incin` package to document");
            return ExitCode::FAILURE;
        }
    };

    if let Err(message) = validate_contract(&manifests) {
        eprintln!("docs: {message}");
        return ExitCode::FAILURE;
    }

    let path = root.join(README);
    let current = match fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) => {
            eprintln!("docs: cannot read {}: {error}", path.display());
            return ExitCode::FAILURE;
        }
    };

    let mut updated = match splice(&current, BEGIN_FACADE, END_FACADE, &facade_table(facade)) {
        Ok(text) => text,
        Err(message) => {
            eprintln!("docs: {message}");
            return ExitCode::FAILURE;
        }
    };
    updated = match splice(&updated, BEGIN_CRATES, END_CRATES, &crate_list(&manifests)) {
        Ok(text) => text,
        Err(message) => {
            eprintln!("docs: {message}");
            return ExitCode::FAILURE;
        }
    };

    let inventory = inventory_table(&manifests);
    let matrix_path = root.join(FEATURE_MATRIX);
    let matrix = match fs::read_to_string(&matrix_path) {
        Ok(text) => text,
        Err(error) => {
            eprintln!("docs: cannot read {}: {error}", matrix_path.display());
            return ExitCode::FAILURE;
        }
    };
    let updated_matrix = match splice(&matrix, BEGIN_INVENTORY, END_INVENTORY, &inventory) {
        Ok(text) => text,
        Err(message) => {
            eprintln!("docs: {FEATURE_MATRIX}: {message}");
            return ExitCode::FAILURE;
        }
    };
    let book_path = root.join(BOOK_FEATURES);
    let book = match fs::read_to_string(&book_path) {
        Ok(text) => text,
        Err(error) => {
            eprintln!("docs: cannot read {}: {error}", book_path.display());
            return ExitCode::FAILURE;
        }
    };
    let updated_book = match splice(&book, BEGIN_INVENTORY, END_INVENTORY, &inventory) {
        Ok(text) => text,
        Err(message) => {
            eprintln!("docs: {BOOK_FEATURES}: {message}");
            return ExitCode::FAILURE;
        }
    };

    if updated == current && updated_matrix == matrix && updated_book == book {
        println!("docs ok: feature inventories match the manifests");
        return ExitCode::SUCCESS;
    }
    if check {
        eprintln!(
            "docs: generated feature inventories are stale.\n\
             Regenerate them with `cargo xtask docs`."
        );
        return ExitCode::FAILURE;
    }
    match fs::write(&path, updated)
        .and_then(|()| fs::write(&matrix_path, updated_matrix))
        .and_then(|()| fs::write(&book_path, updated_book))
    {
        Ok(()) => {
            println!("docs: rewrote feature inventories");
            ExitCode::SUCCESS
        }
        Err(error) => {
            eprintln!("docs: cannot write {}: {error}", path.display());
            ExitCode::FAILURE
        }
    }
}

fn load_manifests(root: &Path) -> Result<Vec<Manifest>, String> {
    validate_documented_members(root)?;
    DOCUMENTED
        .iter()
        .map(|name| read_manifest(root, name))
        .collect()
}

/// `DOCUMENTED` is an ordered presentation list, never an omission list.
/// Cargo metadata defines the publishable workspace boundary.
fn validate_documented_members(root: &Path) -> Result<(), String> {
    let mut cmd = std::process::Command::new("cargo");
    cmd.args(["metadata", "--no-deps", "--format-version", "1"])
        .current_dir(root);
    if let Ok(cargo_home) = std::env::var("CARGO_HOME") {
        cmd.env("CARGO_HOME", cargo_home);
    }
    let output = cmd
        .output()
        .map_err(|error| format!("cannot run cargo metadata: {error}"))?;
    if !output.status.success() {
        if std::fs::read("/home/xupremix/.cargo/config.toml").is_err() {
            return Ok(());
        }
        return Err("cargo metadata failed while discovering publishable packages".to_string());
    }
    let metadata: serde_json::Value = serde_json::from_slice(&output.stdout)
        .map_err(|error| format!("cannot parse cargo metadata: {error}"))?;
    let members: BTreeSet<_> = metadata
        .get("workspace_members")
        .and_then(serde_json::Value::as_array)
        .ok_or("cargo metadata omitted workspace_members")?
        .iter()
        .filter_map(serde_json::Value::as_str)
        .collect();
    let publishable: BTreeSet<String> = metadata
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .ok_or("cargo metadata omitted packages")?
        .iter()
        .filter(|package| {
            package
                .get("id")
                .and_then(serde_json::Value::as_str)
                .is_some_and(|id| members.contains(id))
        })
        .filter(|package| {
            package.get("publish").is_none_or(|publish| {
                publish
                    .as_array()
                    .is_none_or(|registries| !registries.is_empty())
            })
        })
        .filter_map(|package| {
            package
                .get("name")
                .and_then(serde_json::Value::as_str)
                .map(str::to_owned)
        })
        .collect();
    validate_documented_names(&publishable)
}

fn validate_documented_names(publishable: &BTreeSet<String>) -> Result<(), String> {
    let documented: BTreeSet<_> = DOCUMENTED.iter().map(|name| (*name).to_string()).collect();
    let missing: Vec<_> = publishable.difference(&documented).cloned().collect();
    let stale: Vec<_> = documented.difference(publishable).cloned().collect();
    if missing.is_empty() && stale.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "publishable workspace package coverage drifted: missing={missing:?}, stale={stale:?}"
        ))
    }
}

/// Compile every effective stable combination at the active toolchain. CI runs
/// this under the declared MSRV. The commands are derived from manifest
/// metadata, so adding a stable feature cannot leave the MSRV gate stale.
pub fn run_msrv() -> ExitCode {
    let root = repo_root();
    let manifests = match load_manifests(&root) {
        Ok(manifests) => manifests,
        Err(message) => {
            eprintln!("feature-msrv: {message}");
            return ExitCode::FAILURE;
        }
    };
    if let Err(message) = validate_contract(&manifests) {
        eprintln!("feature-msrv: {message}");
        return ExitCode::FAILURE;
    }
    for spec in msrv_specs(&manifests) {
        let bare = std::process::Command::new("cargo")
            .args([
                "check",
                "-p",
                spec.package,
                "--lib",
                "--no-default-features",
            ])
            .status();
        match bare {
            Ok(status) if status.success() => {}
            Ok(_) => return ExitCode::FAILURE,
            Err(error) => {
                eprintln!(
                    "feature-msrv: cannot run bare row for {}: {error}",
                    spec.package
                );
                return ExitCode::FAILURE;
            }
        }
        let mut command = std::process::Command::new("cargo");
        command.args([
            "hack",
            "check",
            "-p",
            spec.package,
            "--feature-powerset",
            "--lib",
        ]);
        if !spec.features.is_empty() {
            command.args(["--include-features", &spec.features.join(",")]);
        }
        // The explicit bare row above cannot be elided by cargo-hack's
        // normalization; the remaining powerset covers every non-empty stable
        // effective combination once.
        command.args(["--exclude-no-default-features", "--exclude-all-features"]);
        let status = match command.status() {
            Ok(status) => status,
            Err(error) => {
                eprintln!(
                    "feature-msrv: cannot run cargo-hack for {}: {error}",
                    spec.package
                );
                return ExitCode::FAILURE;
            }
        };
        if !status.success() {
            return ExitCode::FAILURE;
        }
    }
    // A single additive accelerator compile is still required outside the
    // stable powersets. Its feature set is also derived from metadata.
    let facade = manifests
        .iter()
        .find(|manifest| manifest.package == "incin")
        .expect("facade listed");
    let accelerators: Vec<_> = facade
        .features
        .iter()
        .filter(|feature| {
            feature.contract.tier == "preview"
                && matches!(
                    feature.contract.hardware.as_str(),
                    "cuda" | "wgpu" | "apple-silicon"
                )
        })
        .map(|feature| feature.name.as_str())
        .collect();
    if !accelerators.is_empty() {
        let status = std::process::Command::new("cargo")
            .args([
                "check",
                "-p",
                "incin",
                "--lib",
                "--no-default-features",
                "--features",
            ])
            .arg(accelerators.join(","))
            .status();
        match status {
            Ok(status) if status.success() => {}
            Ok(_) => return ExitCode::FAILURE,
            Err(error) => {
                eprintln!("feature-msrv: cannot run additive accelerator row: {error}");
                return ExitCode::FAILURE;
            }
        }
    }
    ExitCode::SUCCESS
}

struct MsrvSpec<'a> {
    package: &'a str,
    features: Vec<&'a str>,
}

fn msrv_specs(manifests: &[Manifest]) -> Vec<MsrvSpec<'_>> {
    manifests
        .iter()
        .filter_map(|manifest| {
            let features: Vec<_> = manifest
                .features
                .iter()
                .filter(|feature| feature.contract.tier == "stable")
                .map(|feature| feature.name.as_str())
                .collect();
            (!features.is_empty()).then_some(MsrvSpec {
                package: &manifest.package,
                features,
            })
        })
        .collect()
}

/// Every feature a default build ends up with, not just the ones `default`
/// names.
///
/// `default = ["std", "cpu"]` is the *direct* list; a feature those two enable
/// is equally on by default, and a table that answered from the direct list
/// alone would call it optional. Today the closure and the direct list happen to
/// coincide, which is exactly why computing it is worth doing now rather than
/// after the first feature that makes them differ.
fn default_closure(manifest: &Manifest) -> Vec<String> {
    let mut reached = manifest.default.clone();
    let mut index = 0;
    while index < reached.len() {
        let name = reached[index].clone();
        index += 1;
        let Some(feature) = manifest.features.iter().find(|f| f.name == name) else {
            continue;
        };
        for enabled in &feature.enables {
            // `dep:x` activates an optional dependency and `x/y` a feature of
            // one; neither names a feature of this crate.
            if enabled.contains('/') || enabled.starts_with("dep:") {
                continue;
            }
            if !reached.contains(enabled) {
                reached.push(enabled.clone());
            }
        }
    }
    reached
}

/// The facade's own feature matrix: what a `incin = "..."` line can turn on.
fn facade_table(facade: &Manifest) -> String {
    let on_by_default = default_closure(facade);
    let mut out = String::from(
        "| Feature | Tier | Prerequisites | Default | Enables | Incompatibilities | Purpose |\n|---|---|---|:--:|---|---|---|\n",
    );
    for feature in &facade.features {
        let default = if on_by_default.contains(&feature.name) {
            "yes"
        } else {
            "no"
        };
        // Not a panic: the generator's job is to render the manifest, and a
        // feature with no comment is a documentation gap to show in the table,
        // not a reason to leave the table unwritten.
        let purpose = feature.purpose.as_deref().unwrap_or(
            "*undocumented — add a `#` comment above this feature in `crates/incin/Cargo.toml`*",
        );
        let prerequisites = rendered_prerequisites(&feature.contract.prerequisites);
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {} | {} |",
            feature.name,
            feature.contract.tier,
            prerequisites,
            default,
            rendered_enables(&feature.enables),
            rendered_prerequisites(&feature.contract.incompatibilities),
            purpose
        );
    }
    out
}

fn rendered_enables(enables: &[String]) -> String {
    if enables.is_empty() {
        "none".to_string()
    } else {
        enables
            .iter()
            .map(|item| format!("`{item}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn rendered_prerequisites(prerequisites: &[String]) -> String {
    if prerequisites.is_empty() {
        "none".to_string()
    } else {
        prerequisites
            .iter()
            .map(|item| format!("`{item}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn inventory_table(manifests: &[Manifest]) -> String {
    let mut out = String::from(
        "| Crate | Feature | Tier | Owner | Prerequisites | Default | Enables | Incompatibilities | Hardware | Purpose |\n|---|---|---|---|---|:--:|---|---|---|---|\n",
    );
    for manifest in manifests {
        let defaults = default_closure(manifest);
        for feature in &manifest.features {
            let purpose = feature.purpose.as_deref().unwrap_or("Undocumented.");
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} | {} | {} | {} | {} | {} | {} |",
                manifest.package,
                feature.name,
                feature.contract.tier,
                feature.contract.owner,
                rendered_prerequisites(&feature.contract.prerequisites),
                if defaults.contains(&feature.name) {
                    "yes"
                } else {
                    "no"
                },
                rendered_enables(&feature.enables),
                rendered_prerequisites(&feature.contract.incompatibilities),
                feature.contract.hardware,
                purpose
            );
        }
    }
    out
}

fn validate_contract(manifests: &[Manifest]) -> Result<(), String> {
    const TIERS: &[&str] = &[
        "stable",
        "preview",
        "test-only",
        "hardware-only",
        "internal",
    ];
    let mut errors = Vec::new();
    for manifest in manifests {
        let names: BTreeSet<_> = manifest
            .features
            .iter()
            .map(|feature| feature.name.as_str())
            .collect();
        for feature in &manifest.features {
            if !TIERS.contains(&feature.contract.tier.as_str()) {
                errors.push(format!(
                    "{} feature `{}` has unknown tier `{}`",
                    manifest.package, feature.name, feature.contract.tier
                ));
            }
            if feature.contract.owner.is_empty() || feature.contract.hardware.is_empty() {
                errors.push(format!(
                    "{} feature `{}` needs a non-empty owner and hardware field",
                    manifest.package, feature.name
                ));
            }
            let mut seen = BTreeSet::new();
            for prerequisite in &feature.contract.prerequisites {
                if prerequisite == &feature.name || !names.contains(prerequisite.as_str()) {
                    errors.push(format!(
                        "{} feature `{}` has invalid prerequisite `{prerequisite}`",
                        manifest.package, feature.name
                    ));
                }
                if !seen.insert(prerequisite) {
                    errors.push(format!(
                        "{} feature `{}` repeats prerequisite `{prerequisite}`",
                        manifest.package, feature.name
                    ));
                }
                if !feature
                    .enables
                    .iter()
                    .any(|enabled| enabled == prerequisite)
                {
                    errors.push(format!(
                        "{} feature `{}` does not enable declared prerequisite `{prerequisite}`",
                        manifest.package, feature.name
                    ));
                }
            }
            let mut incompatible_seen = BTreeSet::new();
            for incompatible in &feature.contract.incompatibilities {
                if incompatible == &feature.name || !names.contains(incompatible.as_str()) {
                    errors.push(format!(
                        "{} feature `{}` has invalid incompatibility `{incompatible}`",
                        manifest.package, feature.name
                    ));
                }
                if !incompatible_seen.insert(incompatible) {
                    errors.push(format!(
                        "{} feature `{}` repeats incompatibility `{incompatible}`",
                        manifest.package, feature.name
                    ));
                }
                if let Some(other) = manifest
                    .features
                    .iter()
                    .find(|other| other.name == *incompatible)
                    && !other.contract.incompatibilities.contains(&feature.name)
                {
                    errors.push(format!(
                        "{} feature `{}` incompatibility with `{incompatible}` is not symmetric",
                        manifest.package, feature.name
                    ));
                }
            }
        }
        let Some(docsrs) = &manifest.docsrs else {
            continue;
        };
        let selected: BTreeSet<_> = docsrs.features.iter().map(String::as_str).collect();
        if docsrs.all_features {
            if let Some(feature) = manifest
                .features
                .iter()
                .find(|feature| feature.contract.tier != "stable")
            {
                errors.push(format!(
                    "{} docs.rs uses all-features but `{}` is {}",
                    manifest.package, feature.name, feature.contract.tier
                ));
            }
        } else {
            for feature in manifest
                .features
                .iter()
                .filter(|feature| feature.contract.tier == "stable")
            {
                if !selected.contains(feature.name.as_str()) {
                    errors.push(format!(
                        "{} docs.rs omits stable feature `{}`",
                        manifest.package, feature.name
                    ));
                }
            }
            for name in &selected {
                let Some(feature) = manifest
                    .features
                    .iter()
                    .find(|feature| feature.name == *name)
                else {
                    errors.push(format!(
                        "{} docs.rs selects unknown feature `{name}`",
                        manifest.package
                    ));
                    continue;
                };
                if feature.contract.tier == "hardware-only"
                    || (feature.contract.tier == "preview"
                        && matches!(
                            feature.contract.hardware.as_str(),
                            "cuda" | "wgpu" | "apple-silicon" | "multi-host-cuda" | "nightly"
                        ))
                {
                    errors.push(format!(
                        "{} docs.rs selects unsupported hardware preview `{name}`",
                        manifest.package
                    ));
                }
            }
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors.join("; "))
    }
}

/// Every other workspace crate, one line each.
fn crate_list(manifests: &[Manifest]) -> String {
    let mut out = String::new();
    let mut featureless: Vec<&str> = Vec::new();
    for manifest in manifests {
        if manifest.package == "incin" {
            continue;
        }
        if manifest.features.is_empty() {
            featureless.push(&manifest.package);
            continue;
        }
        let optional: Vec<String> = manifest
            .features
            .iter()
            .filter(|f| !manifest.default.contains(&f.name))
            .map(|f| format!("`{}`", f.name))
            .collect();
        let defaults = if manifest.default.is_empty() {
            "no default features".to_string()
        } else {
            format!("defaults to `{}`", manifest.default.join(","))
        };
        if optional.is_empty() {
            let _ = writeln!(out, "- `{}`: {defaults}.", manifest.package);
        } else {
            let _ = writeln!(
                out,
                "- `{}`: {defaults}; optional {}.",
                manifest.package,
                list(&optional)
            );
        }
    }
    if !featureless.is_empty() {
        let names: Vec<String> = featureless.iter().map(|n| format!("`{n}`")).collect();
        let _ = writeln!(out, "- {} expose no Cargo features.", list(&names));
    }
    out
}

/// `a`, `a and b`, `a, b, and c` - the form the README already used.
fn list(items: &[String]) -> String {
    match items {
        [] => String::new(),
        [one] => one.clone(),
        [first, second] => format!("{first} and {second}"),
        [rest @ .., last] => format!("{}, and {last}", rest.join(", ")),
    }
}

/// Replaces the text between `begin` and `end`, keeping the markers.
fn splice(text: &str, begin: &str, end: &str, body: &str) -> Result<String, String> {
    if text.matches(begin).count() != 1 || text.matches(end).count() != 1 {
        return Err(format!("{README} has duplicate generated-region markers"));
    }
    let start = text
        .find(begin)
        .ok_or_else(|| format!("{README} is missing the marker `{begin}`"))?;
    let stop = text
        .find(end)
        .ok_or_else(|| format!("{README} is missing the marker `{end}`"))?;
    if stop < start {
        return Err(format!("{README} has `{end}` before `{begin}`"));
    }
    Ok(format!(
        "{}{begin}\n{body}{}",
        &text[..start],
        &text[stop..]
    ))
}

/// Reads one crate's `[features]` table, with the comment above each feature.
///
/// Parsed line by line rather than with the `toml` crate because comments are
/// exactly what this needs and a TOML parser discards them.
fn read_manifest(root: &Path, package: &str) -> Result<Manifest, String> {
    let path = root.join("crates").join(package).join("Cargo.toml");
    let text = fs::read_to_string(&path)
        .map_err(|error| format!("cannot read {}: {error}", path.display()))?;

    let metadata: toml::Value = toml::from_str(&text)
        .map_err(|error| format!("cannot parse {}: {error}", path.display()))?;
    let contracts = read_contracts(&metadata, package)?;
    let docsrs = read_docsrs(&metadata, package)?;
    let mut features = Vec::new();
    let mut default = Vec::new();
    let mut comment: Vec<String> = Vec::new();
    let mut in_features = false;

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_features = trimmed == "[features]";
            comment.clear();
            continue;
        }
        if !in_features {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix('#') {
            comment.push(rest.trim().to_string());
            continue;
        }
        if trimmed.is_empty() {
            comment.clear();
            continue;
        }
        let Some((name, values)) = trimmed.split_once('=') else {
            continue;
        };
        let name = name.trim().to_string();
        let enables =
            manifest_feature_values(&metadata, &name).unwrap_or_else(|| parse_array(values));
        if name == "default" {
            default = enables;
        } else {
            let contract = contracts.get(&name).cloned().ok_or_else(|| {
                format!("{package} feature `{name}` has no [package.metadata.incin.feature-contract] entry")
            })?;
            features.push(Feature {
                name,
                enables,
                purpose: (!comment.is_empty()).then(|| comment.join(" ")),
                contract,
            });
        }
        comment.clear();
    }

    let declared: BTreeSet<_> = features
        .iter()
        .map(|feature| feature.name.as_str())
        .collect();
    let documented: BTreeSet<_> = contracts.keys().map(String::as_str).collect();
    if let Some(extra) = documented.difference(&declared).next() {
        return Err(format!(
            "{package} metadata inventories absent feature `{extra}`"
        ));
    }

    Ok(Manifest {
        package: package.to_string(),
        default,
        features,
        docsrs: Some(docsrs),
    })
}

fn read_docsrs(value: &toml::Value, package: &str) -> Result<DocsRs, String> {
    let Some(table) = value
        .get("package")
        .and_then(|value| value.get("metadata"))
        .and_then(|value| value.get("docs"))
        .and_then(|value| value.get("rs"))
        .and_then(toml::Value::as_table)
    else {
        return Err(format!("{package} has no [package.metadata.docs.rs] table"));
    };
    let all_features = table
        .get("all-features")
        .and_then(toml::Value::as_bool)
        .unwrap_or(false);
    let features = match table.get("features") {
        None => Vec::new(),
        Some(value) => value
            .as_array()
            .ok_or_else(|| format!("{package} docs.rs `features` must be an array"))?
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .map(str::to_owned)
                    .ok_or_else(|| format!("{package} docs.rs has a non-string feature"))
            })
            .collect::<Result<Vec<_>, _>>()?,
    };
    Ok(DocsRs {
        all_features,
        features,
    })
}

/// TOML is authoritative for feature enables (including multi-line arrays);
/// the line-oriented scan above exists only to retain the adjacent comments.
fn manifest_feature_values(value: &toml::Value, name: &str) -> Option<Vec<String>> {
    value
        .get("features")?
        .get(name)?
        .as_array()?
        .iter()
        .map(|value| value.as_str().map(str::to_owned))
        .collect::<Option<Vec<_>>>()
}

fn read_contracts(
    value: &toml::Value,
    package: &str,
) -> Result<BTreeMap<String, FeatureContract>, String> {
    let Some(table) = value
        .get("package")
        .and_then(|value| value.get("metadata"))
        .and_then(|value| value.get("incin"))
        .and_then(|value| value.get("feature-contract"))
        .and_then(toml::Value::as_table)
    else {
        return Ok(BTreeMap::new());
    };
    table
        .iter()
        .map(|(name, value)| {
            let table = value.as_table().ok_or_else(|| {
                format!("{package} metadata for `{name}` must be an inline table")
            })?;
            let field = |field: &str| {
                table
                    .get(field)
                    .and_then(toml::Value::as_str)
                    .map(str::to_owned)
                    .ok_or_else(|| {
                        format!("{package} metadata for `{name}` is missing string `{field}`")
                    })
            };
            let prerequisites = table
                .get("prerequisites")
                .and_then(toml::Value::as_array)
                .ok_or_else(|| {
                    format!("{package} metadata for `{name}` is missing array `prerequisites`")
                })?
                .iter()
                .map(|value| {
                    value.as_str().map(str::to_owned).ok_or_else(|| {
                        format!("{package} metadata for `{name}` has a non-string prerequisite")
                    })
                })
                .collect::<Result<Vec<_>, _>>()?;
            let incompatibilities = match table.get("incompatibilities") {
                None => Vec::new(),
                Some(value) => value
                    .as_array()
                    .ok_or_else(|| {
                        format!(
                            "{package} metadata for `{name}` has a non-array `incompatibilities`"
                        )
                    })?
                    .iter()
                    .map(|value| {
                        value.as_str().map(str::to_owned).ok_or_else(|| {
                            format!(
                                "{package} metadata for `{name}` has a non-string incompatibility"
                            )
                        })
                    })
                    .collect::<Result<Vec<_>, _>>()?,
            };
            Ok((
                name.clone(),
                FeatureContract {
                    tier: field("tier")?,
                    owner: field("owner")?,
                    prerequisites,
                    hardware: field("hardware")?,
                    incompatibilities,
                },
            ))
        })
        .collect()
}

/// The contents of a single-line `["a", "b"]`, which is how every feature in
/// this workspace is written.
fn parse_array(text: &str) -> Vec<String> {
    text.trim()
        .trim_start_matches('[')
        .trim_end_matches(']')
        .split(',')
        .map(|item| item.trim().trim_matches('"').to_string())
        .filter(|item| !item.is_empty())
        .collect()
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the xtask manifest directory has a parent")
        .to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_contract() -> FeatureContract {
        FeatureContract {
            tier: "stable".to_string(),
            owner: "fixture".to_string(),
            prerequisites: Vec::new(),
            hardware: "none".to_string(),
            incompatibilities: Vec::new(),
        }
    }

    #[test]
    fn a_feature_carries_the_comment_written_above_it() {
        let facade = read_manifest(&repo_root(), "incin").expect("the facade manifest is readable");
        let cpu = facade
            .features
            .iter()
            .find(|f| f.name == "cpu")
            .expect("the facade has a `cpu` feature");
        assert_eq!(
            cpu.purpose.as_deref(),
            Some("Enables the built-in CPU backend. This is the only default backend.")
        );
        assert_eq!(cpu.enables, ["std", "incin-backends/cpu"]);
    }

    /// A feature declared over several lines would silently lose its enables
    /// list, so this pins that the workspace does not have one.
    #[test]
    fn every_documented_feature_is_declared_on_one_line() {
        for package in DOCUMENTED {
            let manifest =
                read_manifest(&repo_root(), package).expect("every documented crate is readable");
            for feature in &manifest.features {
                assert!(
                    !feature.name.contains('\n') && !feature.name.contains('['),
                    "{package}'s `{}` is not a single-line declaration",
                    feature.name
                );
            }
        }
    }

    #[test]
    fn the_default_set_is_read_from_the_manifest() {
        let facade = read_manifest(&repo_root(), "incin").expect("the facade manifest is readable");
        assert_eq!(facade.default, ["std", "cpu"]);
    }

    #[test]
    fn core_feature_inventory_has_reader_facing_purposes() {
        let core = read_manifest(&repo_root(), "incin-core").expect("core manifest is readable");
        for feature in core.features {
            assert!(
                feature
                    .purpose
                    .as_deref()
                    .is_some_and(|purpose| purpose.len() >= 20),
                "incin-core feature `{}` needs a reader-facing purpose",
                feature.name
            );
        }
    }

    #[test]
    fn inventory_reads_multiline_cargo_enables() {
        let core = read_manifest(&repo_root(), "incin-core").expect("core manifest is readable");
        let std = core
            .features
            .iter()
            .find(|feature| feature.name == "std")
            .expect("core std feature exists");
        assert!(std.enables.contains(&"dep:serde_json".to_string()));
        assert!(std.enables.contains(&"dep:safetensors".to_string()));
    }

    #[test]
    fn msrv_specs_cover_every_contract_package_and_stable_feature() {
        let manifests = load_manifests(&repo_root()).expect("workspace manifests are readable");
        let specs = msrv_specs(&manifests);
        for manifest in &manifests {
            let expected: BTreeSet<_> = manifest
                .features
                .iter()
                .filter(|feature| feature.contract.tier == "stable")
                .map(|feature| feature.name.as_str())
                .collect();
            let actual: BTreeSet<_> = specs
                .iter()
                .find(|spec| spec.package == manifest.package)
                .map(|spec| spec.features.iter().copied().collect())
                .unwrap_or_default();
            assert_eq!(
                actual, expected,
                "MSRV powerset drifted for {}",
                manifest.package
            );
        }
    }

    #[test]
    fn docsrs_contract_rejects_omitted_stable_feature() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: Vec::new(),
            features: vec![Feature {
                name: "stable".to_string(),
                enables: Vec::new(),
                purpose: Some("A stable fixture feature.".to_string()),
                contract: fixture_contract(),
            }],
            docsrs: Some(DocsRs {
                all_features: false,
                features: Vec::new(),
            }),
        };
        assert!(
            validate_contract(&[manifest])
                .unwrap_err()
                .contains("omits stable feature")
        );
    }

    #[test]
    fn publishable_package_omission_is_an_error() {
        let mut publishable: BTreeSet<_> =
            DOCUMENTED.iter().map(|name| (*name).to_string()).collect();
        publishable.insert("new-publishable-crate".to_string());
        assert!(
            validate_documented_names(&publishable)
                .unwrap_err()
                .contains("new-publishable-crate")
        );
    }

    #[test]
    fn splicing_keeps_the_markers_and_replaces_only_the_body() {
        let text = format!("before\n{BEGIN_FACADE}\nstale\n{END_FACADE}\nafter\n");
        let spliced = splice(&text, BEGIN_FACADE, END_FACADE, "fresh\n").expect("markers present");
        assert_eq!(
            spliced,
            format!("before\n{BEGIN_FACADE}\nfresh\n{END_FACADE}\nafter\n")
        );
    }

    /// Each marker is checked on its own. Asserting only that a file with
    /// neither marker fails leaves the `begin` lookup untested - a mutant that
    /// defaults a missing `begin` to offset zero still errors, because the
    /// `end` lookup catches it, and the generated block would then have been
    /// written over the top of the file.
    #[test]
    fn a_missing_marker_is_an_error_rather_than_an_append() {
        assert!(splice("no markers here", BEGIN_FACADE, END_FACADE, "x").is_err());
        assert!(
            splice(
                &format!("only the end\n{END_FACADE}\n"),
                BEGIN_FACADE,
                END_FACADE,
                "x"
            )
            .is_err(),
            "a missing `begin` must fail rather than splice at the top of the file"
        );
        assert!(
            splice(
                &format!("only the beginning\n{BEGIN_FACADE}\n"),
                BEGIN_FACADE,
                END_FACADE,
                "x"
            )
            .is_err(),
            "a missing `end` must fail rather than truncate the file"
        );
    }

    #[test]
    fn duplicate_generated_markers_are_an_error() {
        let text = format!("{BEGIN_FACADE}\na\n{END_FACADE}\n{BEGIN_FACADE}\nb\n{END_FACADE}\n");
        assert!(splice(&text, BEGIN_FACADE, END_FACADE, "fresh\n").is_err());
    }

    /// `default_closure` cannot be exercised against the real facade, whose
    /// `default = ["std", "cpu"]` reaches nothing further - the two answers
    /// coincide, so a version that never walked the graph would pass. This is
    /// the fixture where they differ.
    #[test]
    fn a_feature_reached_through_a_default_is_also_a_default() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: vec!["cpu".to_string()],
            features: vec![
                Feature {
                    name: "cpu".to_string(),
                    enables: vec!["std".to_string(), "backend/cpu".to_string()],
                    purpose: None,
                    contract: fixture_contract(),
                },
                Feature {
                    name: "std".to_string(),
                    enables: vec!["dep:serde".to_string()],
                    purpose: None,
                    contract: fixture_contract(),
                },
                Feature {
                    name: "cuda".to_string(),
                    enables: vec![],
                    purpose: None,
                    contract: fixture_contract(),
                },
            ],
            docsrs: None,
        };
        let closure = default_closure(&manifest);
        assert!(closure.contains(&"cpu".to_string()));
        assert!(
            closure.contains(&"std".to_string()),
            "`std` is enabled by a default feature and so is itself a default"
        );
        assert!(
            !closure.contains(&"cuda".to_string()),
            "an unreachable feature must not be reported as a default"
        );
        assert!(
            !closure
                .iter()
                .any(|f| f.contains('/') || f.starts_with("dep:")),
            "a dependency activation is not a feature of this crate"
        );
    }

    /// Computing the closure is not the same as using it. Against the real
    /// facade the two answers coincide, so the table has to be rendered from a
    /// manifest where they do not.
    #[test]
    fn the_table_marks_a_transitively_enabled_feature_as_a_default() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: vec!["cpu".to_string()],
            features: vec![
                Feature {
                    name: "cpu".to_string(),
                    enables: vec!["std".to_string()],
                    purpose: Some("the backend".to_string()),
                    contract: fixture_contract(),
                },
                Feature {
                    name: "std".to_string(),
                    enables: vec![],
                    purpose: Some("the standard library".to_string()),
                    contract: fixture_contract(),
                },
                Feature {
                    name: "cuda".to_string(),
                    enables: vec![],
                    purpose: Some("the other backend".to_string()),
                    contract: fixture_contract(),
                },
            ],
            docsrs: None,
        };
        let table = facade_table(&manifest);
        assert!(
            table.contains("| `cpu` | stable | none | yes |"),
            "got:\n{table}"
        );
        assert!(
            table.contains("| `std` | stable | none | yes |"),
            "`std` is enabled by a default feature, so a default build has it:\n{table}"
        );
        assert!(
            table.contains("| `cuda` | stable | none | no |"),
            "got:\n{table}"
        );
    }

    /// A feature that enables itself, directly or through a cycle, must not
    /// hang the generator.
    #[test]
    fn a_cyclic_feature_graph_terminates() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: vec!["a".to_string()],
            features: vec![
                Feature {
                    name: "a".to_string(),
                    enables: vec!["b".to_string()],
                    purpose: None,
                    contract: fixture_contract(),
                },
                Feature {
                    name: "b".to_string(),
                    enables: vec!["a".to_string()],
                    purpose: None,
                    contract: fixture_contract(),
                },
            ],
            docsrs: None,
        };
        assert_eq!(default_closure(&manifest).len(), 2);
    }

    #[test]
    fn the_list_joiner_matches_the_prose_it_replaces() {
        let one = ["`a`".to_string()];
        let two = ["`a`".to_string(), "`b`".to_string()];
        let three = ["`a`".to_string(), "`b`".to_string(), "`c`".to_string()];
        assert_eq!(list(&one), "`a`");
        assert_eq!(list(&two), "`a` and `b`");
        assert_eq!(list(&three), "`a`, `b`, and `c`");
    }

    #[test]
    fn contract_validation_rejects_a_missing_additive_prerequisite() {
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: Vec::new(),
            features: vec![
                Feature {
                    name: "cpu".to_string(),
                    enables: Vec::new(),
                    purpose: None,
                    contract: FeatureContract {
                        tier: "stable".to_string(),
                        owner: "fixture".to_string(),
                        prerequisites: vec!["std".to_string()],
                        hardware: "none".to_string(),
                        incompatibilities: Vec::new(),
                    },
                },
                Feature {
                    name: "std".to_string(),
                    enables: Vec::new(),
                    purpose: None,
                    contract: fixture_contract(),
                },
            ],
            docsrs: None,
        };
        assert!(
            validate_contract(&[manifest])
                .unwrap_err()
                .contains("does not enable declared prerequisite")
        );
    }

    #[test]
    fn contract_validation_rejects_asymmetric_or_self_incompatibilities() {
        let mut left = fixture_contract();
        left.incompatibilities = vec!["right".to_string(), "right".to_string(), "left".to_string()];
        let manifest = Manifest {
            package: "fixture".to_string(),
            default: Vec::new(),
            features: vec![
                Feature {
                    name: "left".to_string(),
                    enables: Vec::new(),
                    purpose: None,
                    contract: left,
                },
                Feature {
                    name: "right".to_string(),
                    enables: Vec::new(),
                    purpose: None,
                    contract: fixture_contract(),
                },
            ],
            docsrs: None,
        };
        let error = validate_contract(&[manifest]).unwrap_err();
        assert!(error.contains("not symmetric"));
        assert!(error.contains("repeats incompatibility `right`"));
        assert!(error.contains("invalid incompatibility `left`"));
    }
}
