//! Fused GEMM and Linear epilogue kernel emitter (CUDA, WGSL, MSL).
//!
//! Generates zero-allocation fused epilogues combining bias addition, residual connections,
//! and non-linear activations (GELU, ReLU, SiLU) into a single compute pass, eliminating
//! intermediate VRAM writes during forward and inference passes.

use alloc::string::String;
use core::fmt::Write;
use incin_core::tensor::dtype::DTypeId;

/// Epilogue transformation kind fused immediately following a matrix multiplication.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FusedEpilogueKind {
    /// Identity (no epilogue transformation).
    Identity,
    /// Adds 1D bias vector broadcast across rows: `y = x + bias`.
    Bias,
    /// Adds bias and applies ReLU: `y = relu(x + bias)`.
    BiasRelu,
    /// Adds bias and applies GELU: `y = gelu(x + bias)`.
    BiasGelu,
    /// Adds bias and applies SiLU (Swish): `y = silu(x + bias)`.
    BiasSilu,
    /// Adds bias and an external residual skip tensor: `y = x + bias + residual`.
    BiasResidual,
    /// Adds bias, residual skip tensor, and applies GELU: `y = gelu(x + bias + residual)`.
    BiasResidualGelu,
}

/// Specification for a fused matrix-multiplication epilogue kernel.
#[derive(Debug, Clone, PartialEq)]
pub struct FusedEpilogueSpec {
    /// Function identifier.
    pub name: String,
    /// Data type.
    pub dtype: DTypeId,
    /// Epilogue transformation.
    pub kind: FusedEpilogueKind,
    /// Number of output columns (feature dimension for bias broadcast).
    pub cols: Option<usize>,
    /// Block/workgroup size.
    pub work_group_size: usize,
}

impl FusedEpilogueSpec {
    /// Creates a fused epilogue specification.
    #[must_use]
    pub fn new(name: impl Into<String>, dtype: DTypeId, kind: FusedEpilogueKind) -> Self {
        Self {
            name: name.into(),
            dtype,
            kind,
            cols: None,
            work_group_size: 256,
        }
    }

    /// Sets the known static column dimension for unrolled bias stride arithmetic.
    #[must_use]
    pub fn with_cols(mut self, cols: usize) -> Self {
        self.cols = Some(cols);
        self
    }

    /// Whether this epilogue requires a residual tensor input.
    #[must_use]
    pub const fn has_residual(&self) -> bool {
        matches!(
            self.kind,
            FusedEpilogueKind::BiasResidual | FusedEpilogueKind::BiasResidualGelu
        )
    }

    /// Whether this epilogue requires a bias vector input.
    #[must_use]
    pub const fn has_bias(&self) -> bool {
        !matches!(self.kind, FusedEpilogueKind::Identity)
    }

    /// Renders the fused epilogue CUDA C++ kernel.
    #[must_use]
    pub fn render_cuda(&self) -> String {
        let mut out = String::new();
        let ty = cuda_type(self.dtype);

        writeln!(
            out,
            "// Generated by incin-backends fused epilogue codegen (CUDA)"
        )
        .unwrap();
        writeln!(out, "#include <cuda_fp16.h>").unwrap();
        writeln!(out, "#include <cuda_bf16.h>").unwrap();
        writeln!(out, "#include <math.h>").unwrap();
        writeln!(out).unwrap();

        write!(out, "__global__ void {}(", self.name).unwrap();
        write!(out, "const {ty}* __restrict__ matmul_out, ").unwrap();
        if self.has_bias() {
            write!(out, "const {ty}* __restrict__ bias, ").unwrap();
        }
        if self.has_residual() {
            write!(out, "const {ty}* __restrict__ residual, ").unwrap();
        }
        write!(out, "{ty}* __restrict__ final_out, ").unwrap();
        if self.cols.is_none() {
            write!(out, "const int cols, ").unwrap();
        }
        writeln!(out, "const int numel) {{").unwrap();

        writeln!(
            out,
            "    const int idx = blockIdx.x * blockDim.x + threadIdx.x;"
        )
        .unwrap();
        writeln!(out, "    if (idx >= numel) return;").unwrap();
        writeln!(out).unwrap();

        let col_expr = match self.cols {
            Some(c) => alloc::format!("(idx % {c})"),
            None => "(idx % cols)".into(),
        };

        writeln!(out, "    {ty} acc = matmul_out[idx];").unwrap();
        if self.has_bias() {
            writeln!(out, "    const {ty} b = bias[{col_expr}];").unwrap();
            writeln!(out, "    acc = acc + b;").unwrap();
        }
        if self.has_residual() {
            writeln!(out, "    acc = acc + residual[idx];").unwrap();
        }

        match self.kind {
            FusedEpilogueKind::Identity
            | FusedEpilogueKind::Bias
            | FusedEpilogueKind::BiasResidual => {}
            FusedEpilogueKind::BiasRelu => {
                writeln!(out, "    acc = fmaxf(0.0f, acc);").unwrap();
            }
            FusedEpilogueKind::BiasGelu | FusedEpilogueKind::BiasResidualGelu => {
                writeln!(
                    out,
                    "    acc = 0.5f * acc * (1.0f + tanhf(0.7978845608f * (acc + 0.044715f * acc * acc * acc)));"
                )
                .unwrap();
            }
            FusedEpilogueKind::BiasSilu => {
                writeln!(out, "    acc = acc / (1.0f + expf(-acc));").unwrap();
            }
        }

        writeln!(out, "    final_out[idx] = acc;").unwrap();
        writeln!(out, "}}").unwrap();
        out
    }

    /// Renders the fused epilogue WGSL compute shader.
    #[must_use]
    pub fn render_wgsl(&self) -> String {
        let mut out = String::new();
        let ty = wgsl_type(self.dtype);

        writeln!(
            out,
            "// Generated by incin-backends fused epilogue codegen (WGSL)"
        )
        .unwrap();
        writeln!(out).unwrap();

        let mut binding = 0;
        writeln!(
            out,
            "@group(0) @binding({binding}) var<storage, read> matmul_out: array<{ty}>;"
        )
        .unwrap();
        binding += 1;

        if self.has_bias() {
            writeln!(
                out,
                "@group(0) @binding({binding}) var<storage, read> bias: array<{ty}>;"
            )
            .unwrap();
            binding += 1;
        }

        if self.has_residual() {
            writeln!(
                out,
                "@group(0) @binding({binding}) var<storage, read> residual: array<{ty}>;"
            )
            .unwrap();
            binding += 1;
        }

        writeln!(
            out,
            "@group(0) @binding({binding}) var<storage, read_write> final_out: array<{ty}>;"
        )
        .unwrap();
        binding += 1;

        if self.cols.is_none() {
            writeln!(out, "@group(0) @binding({binding}) var<uniform> cols: u32;").unwrap();
        }

        writeln!(out).unwrap();
        writeln!(
            out,
            "@compute @workgroup_size({}, 1, 1)",
            self.work_group_size
        )
        .unwrap();
        writeln!(
            out,
            "fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{"
        )
        .unwrap();
        writeln!(out, "    let idx = global_id.x;").unwrap();
        writeln!(out, "    if (idx >= arrayLength(&final_out)) {{ return; }}").unwrap();
        writeln!(out).unwrap();

        let col_expr = match self.cols {
            Some(c) => alloc::format!("(idx % {c}u)"),
            None => "(idx % cols)".into(),
        };

        writeln!(out, "    var acc = matmul_out[idx];").unwrap();
        if self.has_bias() {
            writeln!(out, "    let b = bias[{col_expr}];").unwrap();
            writeln!(out, "    acc = acc + b;").unwrap();
        }
        if self.has_residual() {
            writeln!(out, "    acc = acc + residual[idx];").unwrap();
        }

        match self.kind {
            FusedEpilogueKind::Identity
            | FusedEpilogueKind::Bias
            | FusedEpilogueKind::BiasResidual => {}
            FusedEpilogueKind::BiasRelu => {
                writeln!(out, "    acc = max(0.0, acc);").unwrap();
            }
            FusedEpilogueKind::BiasGelu | FusedEpilogueKind::BiasResidualGelu => {
                writeln!(
                    out,
                    "    acc = 0.5 * acc * (1.0 + tanh(0.7978845608 * (acc + 0.044715 * acc * acc * acc)));"
                )
                .unwrap();
            }
            FusedEpilogueKind::BiasSilu => {
                writeln!(out, "    acc = acc / (1.0 + exp(-acc));").unwrap();
            }
        }

        writeln!(out, "    final_out[idx] = acc;").unwrap();
        writeln!(out, "}}").unwrap();
        out
    }

    /// Renders the fused epilogue Metal Shading Language (MSL) kernel.
    #[must_use]
    pub fn render_msl(&self) -> String {
        let mut out = String::new();
        let ty = msl_type(self.dtype);

        writeln!(
            out,
            "// Generated by incin-backends fused epilogue codegen (MSL)"
        )
        .unwrap();
        writeln!(out, "#include <metal_stdlib>").unwrap();
        writeln!(out, "using namespace metal;").unwrap();
        writeln!(out).unwrap();

        let mut buf_idx = 0;
        write!(out, "kernel void {}(", self.name).unwrap();
        write!(out, "device const {ty}* matmul_out [[buffer({buf_idx})]], ").unwrap();
        buf_idx += 1;

        if self.has_bias() {
            write!(out, "device const {ty}* bias [[buffer({buf_idx})]], ").unwrap();
            buf_idx += 1;
        }

        if self.has_residual() {
            write!(out, "device const {ty}* residual [[buffer({buf_idx})]], ").unwrap();
            buf_idx += 1;
        }

        write!(out, "device {ty}* final_out [[buffer({buf_idx})]], ").unwrap();
        buf_idx += 1;

        if self.cols.is_none() {
            write!(out, "constant uint& cols [[buffer({buf_idx})]], ").unwrap();
            buf_idx += 1;
        }

        write!(out, "constant uint& numel [[buffer({buf_idx})]], ").unwrap();
        writeln!(out, "uint idx [[thread_position_in_grid]]) {{").unwrap();

        writeln!(out, "    if (idx >= numel) return;").unwrap();
        writeln!(out).unwrap();

        let col_expr = match self.cols {
            Some(c) => alloc::format!("(idx % {c}u)"),
            None => "(idx % cols)".into(),
        };

        writeln!(out, "    {ty} acc = matmul_out[idx];").unwrap();
        if self.has_bias() {
            writeln!(out, "    const {ty} b = bias[{col_expr}];").unwrap();
            writeln!(out, "    acc = acc + b;").unwrap();
        }
        if self.has_residual() {
            writeln!(out, "    acc = acc + residual[idx];").unwrap();
        }

        match self.kind {
            FusedEpilogueKind::Identity
            | FusedEpilogueKind::Bias
            | FusedEpilogueKind::BiasResidual => {}
            FusedEpilogueKind::BiasRelu => {
                writeln!(out, "    acc = max(0.0f, acc);").unwrap();
            }
            FusedEpilogueKind::BiasGelu | FusedEpilogueKind::BiasResidualGelu => {
                writeln!(
                    out,
                    "    acc = 0.5f * acc * (1.0f + tanh(0.7978845608f * (acc + 0.044715f * acc * acc * acc)));"
                )
                .unwrap();
            }
            FusedEpilogueKind::BiasSilu => {
                writeln!(out, "    acc = acc / (1.0f + exp(-acc));").unwrap();
            }
        }

        writeln!(out, "    final_out[idx] = acc;").unwrap();
        writeln!(out, "}}").unwrap();
        out
    }
}

fn cuda_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F64 => "double",
        DTypeId::F16 => "__half",
        DTypeId::BF16 => "__nv_bfloat16",
        _ => "float",
    }
}

fn wgsl_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "f32",
        DTypeId::F16 => "f16",
        _ => "f32",
    }
}

fn msl_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F16 => "half",
        DTypeId::BF16 => "bfloat",
        _ => "float",
    }
}
