//! Shape-informed 2D block-tiled and register-tiled GEMM kernel emitter (CUDA, WGSL, MSL).
//!
//! Generates high-throughput matrix multiplication kernels with compile-time tile geometries,
//! double buffering, and register caching, achieving near-peak tensor compute without
//! external library dependencies.

use alloc::string::String;
use core::fmt::Write;
use incin_core::tensor::dtype::DTypeId;

/// Tile geometry configuration for matrix multiplication.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct GemmTileConfig {
    /// Tile size along M dimension (rows of LHS/output).
    pub bm: usize,
    /// Tile size along N dimension (cols of RHS/output).
    pub bn: usize,
    /// Tile size along K dimension (inner contraction dimension).
    pub bk: usize,
    /// Thread micro-tile size along M.
    pub tm: usize,
    /// Thread micro-tile size along N.
    pub tn: usize,
}

impl Default for GemmTileConfig {
    fn default() -> Self {
        Self {
            bm: 64,
            bn: 64,
            bk: 16,
            tm: 4,
            tn: 4,
        }
    }
}

/// Specification for a tiled GEMM kernel.
#[derive(Debug, Clone, PartialEq)]
pub struct GemmSpec {
    /// Kernel function identifier.
    pub name: String,
    /// Data type.
    pub dtype: DTypeId,
    /// Tile configuration.
    pub tile: GemmTileConfig,
    /// Known static M extent (if known at compile time).
    pub static_m: Option<usize>,
    /// Known static N extent (if known at compile time).
    pub static_n: Option<usize>,
    /// Known static K extent (if known at compile time).
    pub static_k: Option<usize>,
}

impl GemmSpec {
    /// Creates a new GEMM specification with default tile configuration.
    #[must_use]
    pub fn new(name: impl Into<String>, dtype: DTypeId) -> Self {
        Self {
            name: name.into(),
            dtype,
            tile: GemmTileConfig::default(),
            static_m: None,
            static_n: None,
            static_k: None,
        }
    }

    /// Sets custom tile geometry.
    #[must_use]
    pub const fn with_tile(mut self, tile: GemmTileConfig) -> Self {
        self.tile = tile;
        self
    }

    /// Sets known static dimension sizes.
    #[must_use]
    pub const fn with_static_dims(mut self, m: usize, n: usize, k: usize) -> Self {
        self.static_m = Some(m);
        self.static_n = Some(n);
        self.static_k = Some(k);
        self
    }

    /// Renders the tiled CUDA C++ GEMM kernel.
    #[must_use]
    pub fn render_cuda(&self) -> String {
        let mut out = String::new();
        let ty = cuda_type(self.dtype);
        let bm = self.tile.bm;
        let bn = self.tile.bn;
        let bk = self.tile.bk;
        let tm = self.tile.tm;
        let tn = self.tile.tn;
        let block_threads = (bm / tm) * (bn / tn);

        writeln!(
            out,
            "// Generated by incin-backends tiled GEMM codegen (CUDA)"
        )
        .unwrap();
        writeln!(out, "#include <cuda_fp16.h>").unwrap();
        writeln!(out, "#include <cuda_bf16.h>").unwrap();
        writeln!(out).unwrap();

        write!(out, "__global__ void {}(", self.name).unwrap();
        write!(out, "const {ty}* __restrict__ a, ").unwrap();
        write!(out, "const {ty}* __restrict__ b, ").unwrap();
        write!(out, "{ty}* __restrict__ c, ").unwrap();
        write!(out, "const int m, const int k, const int n) {{").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    const int bx = blockIdx.x;").unwrap();
        writeln!(out, "    const int by = blockIdx.y;").unwrap();
        writeln!(out, "    const int tid = threadIdx.x;").unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "    const int thread_row = (tid / {}) * {};",
            bn / tn,
            tm
        )
        .unwrap();
        writeln!(
            out,
            "    const int thread_col = (tid % {}) * {};",
            bn / tn,
            tn
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    __shared__ float s_a[{}][{}];", bm, bk + 1).unwrap();
        writeln!(out, "    __shared__ float s_b[{}][{}];", bk, bn + 1).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    float r_c[{}][{}] = {{0.0f}};", tm, tn).unwrap();
        writeln!(out, "    float r_a[{}];", tm).unwrap();
        writeln!(out, "    float r_b[{}];", tn).unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "    for (int bk_idx = 0; bk_idx < k; bk_idx += {}) {{",
            bk
        )
        .unwrap();
        writeln!(out, "        // Load tile from A into shared memory").unwrap();
        writeln!(
            out,
            "        for (int load_idx = tid; load_idx < {}; load_idx += {}) {{",
            bm * bk,
            block_threads
        )
        .unwrap();
        writeln!(
            out,
            "            int a_row = by * {} + (load_idx / {});",
            bm, bk
        )
        .unwrap();
        writeln!(out, "            int a_col = bk_idx + (load_idx % {});", bk).unwrap();
        writeln!(out, "            s_a[load_idx / {}][load_idx % {}] = (a_row < m && a_col < k) ? static_cast<float>(a[a_row * k + a_col]) : 0.0f;", bk, bk).unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        // Load tile from B into shared memory").unwrap();
        writeln!(
            out,
            "        for (int load_idx = tid; load_idx < {}; load_idx += {}) {{",
            bk * bn,
            block_threads
        )
        .unwrap();
        writeln!(out, "            int b_row = bk_idx + (load_idx / {});", bn).unwrap();
        writeln!(
            out,
            "            int b_col = bx * {} + (load_idx % {});",
            bn, bn
        )
        .unwrap();
        writeln!(out, "            s_b[load_idx / {}][load_idx % {}] = (b_row < k && b_col < n) ? static_cast<float>(b[b_row * n + b_col]) : 0.0f;", bn, bn).unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        __syncthreads();").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "        // Compute matrix multiplication on registers").unwrap();
        writeln!(out, "        #pragma unroll").unwrap();
        writeln!(
            out,
            "        for (int dot_k = 0; dot_k < {}; ++dot_k) {{",
            bk
        )
        .unwrap();
        writeln!(out, "            #pragma unroll").unwrap();
        writeln!(
            out,
            "            for (int i = 0; i < {}; ++i) r_a[i] = s_a[thread_row + i][dot_k];",
            tm
        )
        .unwrap();
        writeln!(out, "            #pragma unroll").unwrap();
        writeln!(
            out,
            "            for (int j = 0; j < {}; ++j) r_b[j] = s_b[dot_k][thread_col + j];",
            tn
        )
        .unwrap();
        writeln!(out, "            #pragma unroll").unwrap();
        writeln!(out, "            for (int i = 0; i < {}; ++i) {{", tm).unwrap();
        writeln!(out, "                #pragma unroll").unwrap();
        writeln!(out, "                for (int j = 0; j < {}; ++j) {{", tn).unwrap();
        writeln!(
            out,
            "                    r_c[i][j] = fmaf(r_a[i], r_b[j], r_c[i][j]);"
        )
        .unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        __syncthreads();").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    // Write back results to global memory").unwrap();
        writeln!(out, "    #pragma unroll").unwrap();
        writeln!(out, "    for (int i = 0; i < {}; ++i) {{", tm).unwrap();
        writeln!(out, "        int out_r = by * {} + thread_row + i;", bm).unwrap();
        writeln!(out, "        if (out_r < m) {{").unwrap();
        writeln!(out, "            #pragma unroll").unwrap();
        writeln!(out, "            for (int j = 0; j < {}; ++j) {{", tn).unwrap();
        writeln!(
            out,
            "                int out_c = bx * {} + thread_col + j;",
            bn
        )
        .unwrap();
        writeln!(out, "                if (out_c < n) {{").unwrap();
        writeln!(
            out,
            "                    c[out_r * n + out_c] = static_cast<{ty}>(r_c[i][j]);"
        )
        .unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();

        out
    }

    /// Renders the tiled WGSL compute shader for GEMM.
    #[must_use]
    pub fn render_wgsl(&self) -> String {
        let mut out = String::new();
        let ty = wgsl_type(self.dtype);
        let bm = self.tile.bm;
        let bn = self.tile.bn;
        let bk = self.tile.bk;
        let tm = self.tile.tm;
        let tn = self.tile.tn;
        let block_threads = (bm / tm) * (bn / tn);

        writeln!(
            out,
            "// Generated by incin-backends tiled GEMM codegen (WGSL)"
        )
        .unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "@group(0) @binding(0) var<storage, read> a: array<{ty}>;"
        )
        .unwrap();
        writeln!(
            out,
            "@group(0) @binding(1) var<storage, read> b: array<{ty}>;"
        )
        .unwrap();
        writeln!(
            out,
            "@group(0) @binding(2) var<storage, read_write> c: array<{ty}>;"
        )
        .unwrap();
        writeln!(out, "struct GemmUniforms {{ m: u32, k: u32, n: u32 }};").unwrap();
        writeln!(
            out,
            "@group(0) @binding(3) var<uniform> dims: GemmUniforms;"
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "var<workgroup> s_a: array<array<f32, {}>, {}>;",
            bk, bm
        )
        .unwrap();
        writeln!(
            out,
            "var<workgroup> s_b: array<array<f32, {}>, {}>;",
            bn, bk
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "@compute @workgroup_size({}, 1, 1)", block_threads).unwrap();
        writeln!(out, "fn main(@builtin(local_invocation_id) local_id: vec3<u32>, @builtin(workgroup_id) group_id: vec3<u32>) {{").unwrap();
        writeln!(out, "    let bx = group_id.x;").unwrap();
        writeln!(out, "    let by = group_id.y;").unwrap();
        writeln!(out, "    let tid = local_id.x;").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    let thread_row = (tid / {}u) * {}u;", bn / tn, tm).unwrap();
        writeln!(out, "    let thread_col = (tid % {}u) * {}u;", bn / tn, tn).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    var r_c: array<array<f32, {}>, {}>;", tn, tm).unwrap();
        writeln!(out, "    var r_a: array<f32, {}>;", tm).unwrap();
        writeln!(out, "    var r_b: array<f32, {}>;", tn).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    var bk_idx = 0u;").unwrap();
        writeln!(out, "    while (bk_idx < dims.k) {{").unwrap();
        writeln!(out, "        var load_idx = tid;").unwrap();
        writeln!(out, "        while (load_idx < {}u) {{", bm * bk).unwrap();
        writeln!(
            out,
            "            let a_row = by * {}u + (load_idx / {}u);",
            bm, bk
        )
        .unwrap();
        writeln!(
            out,
            "            let a_col = bk_idx + (load_idx % {}u);",
            bk
        )
        .unwrap();
        writeln!(out, "            if (a_row < dims.m && a_col < dims.k) {{").unwrap();
        writeln!(
            out,
            "                s_a[load_idx / {}u][load_idx % {}u] = f32(a[a_row * dims.k + a_col]);",
            bk, bk
        )
        .unwrap();
        writeln!(out, "            }} else {{").unwrap();
        writeln!(
            out,
            "                s_a[load_idx / {}u][load_idx % {}u] = 0.0;",
            bk, bk
        )
        .unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "            load_idx += {}u;", block_threads).unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "        load_idx = tid;").unwrap();
        writeln!(out, "        while (load_idx < {}u) {{", bk * bn).unwrap();
        writeln!(
            out,
            "            let b_row = bk_idx + (load_idx / {}u);",
            bn
        )
        .unwrap();
        writeln!(
            out,
            "            let b_col = bx * {}u + (load_idx % {}u);",
            bn, bn
        )
        .unwrap();
        writeln!(out, "            if (b_row < dims.k && b_col < dims.n) {{").unwrap();
        writeln!(
            out,
            "                s_b[load_idx / {}u][load_idx % {}u] = f32(b[b_row * dims.n + b_col]);",
            bn, bn
        )
        .unwrap();
        writeln!(out, "            }} else {{").unwrap();
        writeln!(
            out,
            "                s_b[load_idx / {}u][load_idx % {}u] = 0.0;",
            bn, bn
        )
        .unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "            load_idx += {}u;", block_threads).unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        workgroupBarrier();").unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "        for (var dot_k = 0u; dot_k < {}u; dot_k++) {{",
            bk
        )
        .unwrap();
        writeln!(
            out,
            "            for (var i = 0u; i < {}u; i++) {{ r_a[i] = s_a[thread_row + i][dot_k]; }}",
            tm
        )
        .unwrap();
        writeln!(
            out,
            "            for (var j = 0u; j < {}u; j++) {{ r_b[j] = s_b[dot_k][thread_col + j]; }}",
            tn
        )
        .unwrap();
        writeln!(out, "            for (var i = 0u; i < {}u; i++) {{", tm).unwrap();
        writeln!(out, "                for (var j = 0u; j < {}u; j++) {{", tn).unwrap();
        writeln!(
            out,
            "                    r_c[i][j] = fma(r_a[i], r_b[j], r_c[i][j]);"
        )
        .unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        workgroupBarrier();").unwrap();
        writeln!(out, "        bk_idx += {}u;", bk).unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    for (var i = 0u; i < {}u; i++) {{", tm).unwrap();
        writeln!(out, "        let out_r = by * {}u + thread_row + i;", bm).unwrap();
        writeln!(out, "        if (out_r < dims.m) {{").unwrap();
        writeln!(out, "            for (var j = 0u; j < {}u; j++) {{", tn).unwrap();
        writeln!(
            out,
            "                let out_c = bx * {}u + thread_col + j;",
            bn
        )
        .unwrap();
        writeln!(out, "                if (out_c < dims.n) {{").unwrap();
        writeln!(
            out,
            "                    c[out_r * dims.n + out_c] = {ty}(r_c[i][j]);"
        )
        .unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();

        out
    }

    /// Renders the tiled Metal Shading Language (MSL) kernel for GEMM.
    #[must_use]
    pub fn render_msl(&self) -> String {
        let mut out = String::new();
        let ty = msl_type(self.dtype);
        let bm = self.tile.bm;
        let bn = self.tile.bn;
        let bk = self.tile.bk;
        let tm = self.tile.tm;
        let tn = self.tile.tn;
        let block_threads = (bm / tm) * (bn / tn);

        writeln!(
            out,
            "// Generated by incin-backends tiled GEMM codegen (MSL)"
        )
        .unwrap();
        writeln!(out, "#include <metal_stdlib>").unwrap();
        writeln!(out, "using namespace metal;").unwrap();
        writeln!(out).unwrap();

        write!(out, "kernel void {}(", self.name).unwrap();
        write!(out, "device const {ty}* a [[buffer(0)]], ").unwrap();
        write!(out, "device const {ty}* b [[buffer(1)]], ").unwrap();
        write!(out, "device {ty}* c [[buffer(2)]], ").unwrap();
        write!(out, "constant uint& m [[buffer(3)]], ").unwrap();
        write!(out, "constant uint& k [[buffer(4)]], ").unwrap();
        write!(out, "constant uint& n [[buffer(5)]], ").unwrap();
        writeln!(out, "uint2 group_id [[threadgroup_position_in_grid]], uint tid [[thread_position_in_threadgroup]]) {{").unwrap();

        writeln!(out, "    uint bx = group_id.x;").unwrap();
        writeln!(out, "    uint by = group_id.y;").unwrap();
        writeln!(out, "    uint thread_row = (tid / {}u) * {}u;", bn / tn, tm).unwrap();
        writeln!(out, "    uint thread_col = (tid % {}u) * {}u;", bn / tn, tn).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    threadgroup float s_a[{}][{}];", bm, bk).unwrap();
        writeln!(out, "    threadgroup float s_b[{}][{}];", bk, bn).unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    float r_c[{}][{}] = {{0.0f}};", tm, tn).unwrap();
        writeln!(out, "    float r_a[{}];", tm).unwrap();
        writeln!(out, "    float r_b[{}];", tn).unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "    for (uint bk_idx = 0; bk_idx < k; bk_idx += {}) {{",
            bk
        )
        .unwrap();
        writeln!(
            out,
            "        for (uint load_idx = tid; load_idx < {}; load_idx += {}) {{",
            bm * bk,
            block_threads
        )
        .unwrap();
        writeln!(
            out,
            "            uint a_row = by * {} + (load_idx / {});",
            bm, bk
        )
        .unwrap();
        writeln!(
            out,
            "            uint a_col = bk_idx + (load_idx % {});",
            bk
        )
        .unwrap();
        writeln!(out, "            s_a[load_idx / {}][load_idx % {}] = (a_row < m && a_col < k) ? float(a[a_row * k + a_col]) : 0.0f;", bk, bk).unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(
            out,
            "        for (uint load_idx = tid; load_idx < {}; load_idx += {}) {{",
            bk * bn,
            block_threads
        )
        .unwrap();
        writeln!(
            out,
            "            uint b_row = bk_idx + (load_idx / {});",
            bn
        )
        .unwrap();
        writeln!(
            out,
            "            uint b_col = bx * {} + (load_idx % {});",
            bn, bn
        )
        .unwrap();
        writeln!(out, "            s_b[load_idx / {}][load_idx % {}] = (b_row < k && b_col < n) ? float(b[b_row * n + b_col]) : 0.0f;", bn, bn).unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(
            out,
            "        threadgroup_barrier(mem_flags::mem_threadgroup);"
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "        for (uint dot_k = 0; dot_k < {}; ++dot_k) {{",
            bk
        )
        .unwrap();
        writeln!(
            out,
            "            for (uint i = 0; i < {}; ++i) r_a[i] = s_a[thread_row + i][dot_k];",
            tm
        )
        .unwrap();
        writeln!(
            out,
            "            for (uint j = 0; j < {}; ++j) r_b[j] = s_b[dot_k][thread_col + j];",
            tn
        )
        .unwrap();
        writeln!(out, "            for (uint i = 0; i < {}; ++i) {{", tm).unwrap();
        writeln!(out, "                for (uint j = 0; j < {}; ++j) {{", tn).unwrap();
        writeln!(
            out,
            "                    r_c[i][j] = fma(r_a[i], r_b[j], r_c[i][j]);"
        )
        .unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(
            out,
            "        threadgroup_barrier(mem_flags::mem_threadgroup);"
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    for (uint i = 0; i < {}; ++i) {{", tm).unwrap();
        writeln!(out, "        uint out_r = by * {} + thread_row + i;", bm).unwrap();
        writeln!(out, "        if (out_r < m) {{").unwrap();
        writeln!(out, "            for (uint j = 0; j < {}; ++j) {{", tn).unwrap();
        writeln!(
            out,
            "                uint out_c = bx * {} + thread_col + j;",
            bn
        )
        .unwrap();
        writeln!(out, "                if (out_c < n) {{").unwrap();
        writeln!(
            out,
            "                    c[out_r * n + out_c] = {ty}(r_c[i][j]);"
        )
        .unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();

        out
    }
}

fn cuda_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F64 => "double",
        DTypeId::F16 => "__half",
        DTypeId::BF16 => "__nv_bfloat16",
        _ => "float",
    }
}

fn wgsl_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "f32",
        DTypeId::F16 => "f16",
        _ => "f32",
    }
}

fn msl_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F16 => "half",
        DTypeId::BF16 => "bfloat",
        _ => "float",
    }
}
