//! Pointwise kernel specification and target emitters for CUDA, WGSL, and MSL (PRF-007).

use alloc::{boxed::Box, string::String, vec::Vec};
use core::fmt::Write;
use incin_core::tensor::dtype::DTypeId;

/// Unary pointwise mathematical operators.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UnaryOp {
    /// Absolute value.
    Abs,
    /// Natural exponential.
    Exp,
    /// Natural logarithm.
    Log,
    /// Sine.
    Sin,
    /// Cosine.
    Cos,
    /// Square root.
    Sqrt,
    /// Reciprocal square root.
    Rsqrt,
    /// Arithmetic negation.
    Neg,
    /// Rectified linear unit.
    Relu,
    /// Gaussian error linear unit.
    Gelu,
    /// Sigmoid linear unit (Swish).
    Silu,
    /// Logistic sigmoid.
    Sigmoid,
    /// Hyperbolic tangent.
    Tanh,
    /// Floor.
    Floor,
    /// Ceiling.
    Ceil,
    /// Multiplicative reciprocal.
    Reciprocal,
    /// Square (`x * x`).
    Square,
}

/// Binary pointwise mathematical operators.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BinaryOp {
    /// Addition.
    Add,
    /// Subtraction.
    Sub,
    /// Multiplication.
    Mul,
    /// Division.
    Div,
    /// Exponentiation (`lhs ^ rhs`).
    Pow,
    /// Element-wise maximum.
    Maximum,
    /// Element-wise minimum.
    Minimum,
}

/// Ternary pointwise mathematical operators.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TernaryOp {
    /// Clamps a value into an inclusive low/high range.
    Clamp,
    /// Fused multiply-add (`a * b + c`) when the target supports it.
    Fma,
}

/// Abstract AST expression for pointwise kernel evaluation.
#[derive(Debug, Clone, PartialEq)]
pub enum PointwiseExpr {
    /// Input argument by 0-based index.
    Arg(usize),
    /// Scalar literal constant.
    ScalarConst(f64),
    /// Unary operation over an expression.
    Unary(UnaryOp, Box<PointwiseExpr>),
    /// Binary operation over two expressions.
    Binary(BinaryOp, Box<PointwiseExpr>, Box<PointwiseExpr>),
    /// Ternary operation over three expressions.
    Ternary(
        TernaryOp,
        Box<PointwiseExpr>,
        Box<PointwiseExpr>,
        Box<PointwiseExpr>,
    ),
}

/// Layout mode for memory indexing in generated code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LayoutKind {
    /// Contiguous row-major memory access.
    Contiguous,
    /// Arbitrary strided memory access.
    Strided,
    /// Binary operation with scalar broadcast (arg 0 array, arg 1 scalar).
    ScalarBroadcast,
}

/// Specification for a single cross-backend pointwise kernel.
#[derive(Debug, Clone, PartialEq)]
pub struct PointwiseOpSpec {
    /// Kernel function name identifier.
    pub name: String,
    /// Data type for each input operand.
    pub inputs: Vec<DTypeId>,
    /// Output data type.
    pub output: DTypeId,
    /// Expression tree representing computation per element.
    pub expr: PointwiseExpr,
    /// Memory layout pattern.
    pub layout: LayoutKind,
    /// Target workgroup/block size.
    pub work_group_size: usize,
}

impl PointwiseOpSpec {
    /// Creates a unary pointwise op spec for contiguous inputs.
    pub fn unary(name: impl Into<String>, op: UnaryOp, dtype: DTypeId) -> Self {
        Self {
            name: name.into(),
            inputs: vec![dtype],
            output: dtype,
            expr: PointwiseExpr::Unary(op, Box::new(PointwiseExpr::Arg(0))),
            layout: LayoutKind::Contiguous,
            work_group_size: 256,
        }
    }

    /// Creates a binary pointwise op spec for contiguous inputs.
    pub fn binary(
        name: impl Into<String>,
        op: BinaryOp,
        lhs_dtype: DTypeId,
        rhs_dtype: DTypeId,
    ) -> Self {
        Self {
            name: name.into(),
            inputs: vec![lhs_dtype, rhs_dtype],
            output: lhs_dtype,
            expr: PointwiseExpr::Binary(
                op,
                Box::new(PointwiseExpr::Arg(0)),
                Box::new(PointwiseExpr::Arg(1)),
            ),
            layout: LayoutKind::Contiguous,
            work_group_size: 256,
        }
    }

    /// Renders CUDA C++ kernel source code.
    #[must_use]
    pub fn render_cuda(&self) -> String {
        let mut out = String::new();
        let out_type = cuda_type(self.output);

        writeln!(out, "// Generated by incin-backends codegen (CUDA)").unwrap();
        writeln!(out, "#include <cuda_fp16.h>").unwrap();
        writeln!(out, "#include <cuda_bf16.h>").unwrap();
        writeln!(out).unwrap();

        write!(out, "__global__ void {}(", self.name).unwrap();
        for (i, &dt) in self.inputs.iter().enumerate() {
            write!(out, "const {}* __restrict__ in{}, ", cuda_type(dt), i).unwrap();
        }
        write!(out, "{}* __restrict__ out_data, ", out_type).unwrap();
        writeln!(out, "const int numel) {{").unwrap();

        writeln!(
            out,
            "    const int idx = blockIdx.x * blockDim.x + threadIdx.x;"
        )
        .unwrap();
        writeln!(out, "    if (idx >= numel) return;").unwrap();

        for (i, &dt) in self.inputs.iter().enumerate() {
            match self.layout {
                LayoutKind::ScalarBroadcast if i == 1 => {
                    writeln!(out, "    const {} val{} = in1[0];", cuda_type(dt), i).unwrap();
                }
                _ => {
                    writeln!(out, "    const {} val{} = in{}[idx];", cuda_type(dt), i, i).unwrap();
                }
            }
        }

        let expr_str = render_expr_cuda(&self.expr);
        writeln!(
            out,
            "    out_data[idx] = static_cast<{}>({});",
            out_type, expr_str
        )
        .unwrap();
        writeln!(out, "}}").unwrap();

        out
    }

    /// Renders WebGPU Shading Language (WGSL) shader source code.
    #[must_use]
    pub fn render_wgsl(&self) -> String {
        let mut out = String::new();
        let out_type = wgsl_type(self.output);

        writeln!(out, "// Generated by incin-backends codegen (WGSL)").unwrap();
        writeln!(out).unwrap();

        for (i, &dt) in self.inputs.iter().enumerate() {
            writeln!(
                out,
                "@group(0) @binding({}) var<storage, read> in{}: array<{}>;",
                i,
                i,
                wgsl_type(dt)
            )
            .unwrap();
        }
        writeln!(
            out,
            "@group(0) @binding({}) var<storage, read_write> out_data: array<{}>;",
            self.inputs.len(),
            out_type
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "@compute @workgroup_size({}, 1, 1)",
            self.work_group_size
        )
        .unwrap();
        writeln!(
            out,
            "fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{"
        )
        .unwrap();
        writeln!(out, "    let idx = global_id.x;").unwrap();
        writeln!(out, "    if (idx >= arrayLength(&out_data)) {{ return; }}").unwrap();

        for (i, _) in self.inputs.iter().enumerate() {
            match self.layout {
                LayoutKind::ScalarBroadcast if i == 1 => {
                    writeln!(out, "    let val{} = in1[0];", i).unwrap();
                }
                _ => {
                    writeln!(out, "    let val{} = in{}[idx];", i, i).unwrap();
                }
            }
        }

        let expr_str = render_expr_wgsl(&self.expr);
        writeln!(out, "    out_data[idx] = {}({});", out_type, expr_str).unwrap();
        writeln!(out, "}}").unwrap();

        out
    }

    /// Renders Metal Shading Language (MSL) shader source code.
    #[must_use]
    pub fn render_msl(&self) -> String {
        let mut out = String::new();
        let out_type = msl_type(self.output);

        writeln!(out, "// Generated by incin-backends codegen (MSL)").unwrap();
        writeln!(out, "#include <metal_stdlib>").unwrap();
        writeln!(out, "using namespace metal;").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "kernel void {}(", self.name).unwrap();
        for (i, &dt) in self.inputs.iter().enumerate() {
            writeln!(
                out,
                "    device const {}* in{} [[buffer({})]],",
                msl_type(dt),
                i,
                i
            )
            .unwrap();
        }
        writeln!(
            out,
            "    device {}* out_data [[buffer({})]],",
            out_type,
            self.inputs.len()
        )
        .unwrap();
        writeln!(out, "    uint idx [[thread_position_in_grid]]\n) {{").unwrap();

        for (i, &dt) in self.inputs.iter().enumerate() {
            match self.layout {
                LayoutKind::ScalarBroadcast if i == 1 => {
                    writeln!(out, "    const {} val{} = in1[0];", msl_type(dt), i).unwrap();
                }
                _ => {
                    writeln!(out, "    const {} val{} = in{}[idx];", msl_type(dt), i, i).unwrap();
                }
            }
        }

        let expr_str = render_expr_msl(&self.expr);
        writeln!(
            out,
            "    out_data[idx] = static_cast<{}>({});",
            out_type, expr_str
        )
        .unwrap();
        writeln!(out, "}}").unwrap();

        out
    }
}

/// Convenience functions for standalone rendering.
pub fn render_cuda(spec: &PointwiseOpSpec) -> String {
    spec.render_cuda()
}

/// Renders one pointwise op as WGSL source for the WGPU backend.
pub fn render_wgsl(spec: &PointwiseOpSpec) -> String {
    spec.render_wgsl()
}

/// Renders one pointwise op as MSL source for the Metal backend.
pub fn render_msl(spec: &PointwiseOpSpec) -> String {
    spec.render_msl()
}

fn cuda_type(dtype: DTypeId) -> &'static str {
    match dtype {
        DTypeId::F32 => "float",
        DTypeId::F64 => "double",
        DTypeId::F16 => "__half",
        DTypeId::BF16 => "__nv_bfloat16",
        DTypeId::U8 => "unsigned char",
        DTypeId::U32 => "unsigned int",
        DTypeId::I64 => "long long",
        DTypeId::Q8_0 | _ => "unsigned char",
    }
}

fn wgsl_type(dtype: DTypeId) -> &'static str {
    match dtype {
        DTypeId::F32 | DTypeId::F64 => "f32",
        DTypeId::F16 | DTypeId::BF16 => "f16",
        DTypeId::U8 | DTypeId::U32 => "u32",
        DTypeId::I64 => "i32",
        DTypeId::Q8_0 | _ => "u32",
    }
}

fn msl_type(dtype: DTypeId) -> &'static str {
    match dtype {
        DTypeId::F32 => "float",
        DTypeId::F64 => "double",
        DTypeId::F16 | DTypeId::BF16 => "half",
        DTypeId::U8 => "uchar",
        DTypeId::U32 => "uint",
        DTypeId::I64 => "long",
        DTypeId::Q8_0 | _ => "uchar",
    }
}

fn render_expr_cuda(expr: &PointwiseExpr) -> String {
    match expr {
        PointwiseExpr::Arg(idx) => format!("val{idx}"),
        PointwiseExpr::ScalarConst(val) => format!("{val:?}f"),
        PointwiseExpr::Unary(op, inner) => {
            let inner_s = render_expr_cuda(inner);
            match op {
                UnaryOp::Abs => format!("fabs({inner_s})"),
                UnaryOp::Exp => format!("expf({inner_s})"),
                UnaryOp::Log => format!("logf({inner_s})"),
                UnaryOp::Sin => format!("sinf({inner_s})"),
                UnaryOp::Cos => format!("cosf({inner_s})"),
                UnaryOp::Sqrt => format!("sqrtf({inner_s})"),
                UnaryOp::Rsqrt => format!("rsqrtf({inner_s})"),
                UnaryOp::Neg => format!("-({inner_s})"),
                UnaryOp::Relu => format!("fmaxf(0.0f, {inner_s})"),
                UnaryOp::Gelu => format!(
                    "(0.5f * {inner_s} * (1.0f + tanhf(0.7978845608f * ({inner_s} + 0.044715f * {inner_s} * {inner_s} * {inner_s}))))"
                ),
                UnaryOp::Silu => format!("({inner_s} / (1.0f + expf(-({inner_s}))))"),
                UnaryOp::Sigmoid => format!("(1.0f / (1.0f + expf(-({inner_s}))))"),
                UnaryOp::Tanh => format!("tanhf({inner_s})"),
                UnaryOp::Floor => format!("floorf({inner_s})"),
                UnaryOp::Ceil => format!("ceilf({inner_s})"),
                UnaryOp::Reciprocal => format!("(1.0f / ({inner_s}))"),
                UnaryOp::Square => format!("(({inner_s}) * ({inner_s}))"),
            }
        }
        PointwiseExpr::Binary(op, lhs, rhs) => {
            let lhs_s = render_expr_cuda(lhs);
            let rhs_s = render_expr_cuda(rhs);
            match op {
                BinaryOp::Add => format!("({lhs_s} + {rhs_s})"),
                BinaryOp::Sub => format!("({lhs_s} - {rhs_s})"),
                BinaryOp::Mul => format!("({lhs_s} * {rhs_s})"),
                BinaryOp::Div => format!("({lhs_s} / {rhs_s})"),
                BinaryOp::Pow => format!("powf({lhs_s}, {rhs_s})"),
                BinaryOp::Maximum => format!("fmaxf({lhs_s}, {rhs_s})"),
                BinaryOp::Minimum => format!("fminf({lhs_s}, {rhs_s})"),
            }
        }
        PointwiseExpr::Ternary(op, a, b, c) => {
            let a_s = render_expr_cuda(a);
            let b_s = render_expr_cuda(b);
            let c_s = render_expr_cuda(c);
            match op {
                TernaryOp::Clamp => format!("fminf(fmaxf({a_s}, {b_s}), {c_s})"),
                TernaryOp::Fma => format!("fmaf({a_s}, {b_s}, {c_s})"),
            }
        }
    }
}

fn render_expr_wgsl(expr: &PointwiseExpr) -> String {
    match expr {
        PointwiseExpr::Arg(idx) => format!("val{idx}"),
        PointwiseExpr::ScalarConst(val) => format!("{val:?}"),
        PointwiseExpr::Unary(op, inner) => {
            let inner_s = render_expr_wgsl(inner);
            match op {
                UnaryOp::Abs => format!("abs({inner_s})"),
                UnaryOp::Exp => format!("exp({inner_s})"),
                UnaryOp::Log => format!("log({inner_s})"),
                UnaryOp::Sin => format!("sin({inner_s})"),
                UnaryOp::Cos => format!("cos({inner_s})"),
                UnaryOp::Sqrt => format!("sqrt({inner_s})"),
                UnaryOp::Rsqrt => format!("inverseSqrt({inner_s})"),
                UnaryOp::Neg => format!("-({inner_s})"),
                UnaryOp::Relu => format!("max(0.0, {inner_s})"),
                UnaryOp::Gelu => format!(
                    "(0.5 * {inner_s} * (1.0 + tanh(0.7978845608 * ({inner_s} + 0.044715 * {inner_s} * {inner_s} * {inner_s}))))"
                ),
                UnaryOp::Silu => format!("({inner_s} / (1.0 + exp(-({inner_s}))))"),
                UnaryOp::Sigmoid => format!("(1.0 / (1.0 + exp(-({inner_s}))))"),
                UnaryOp::Tanh => format!("tanh({inner_s})"),
                UnaryOp::Floor => format!("floor({inner_s})"),
                UnaryOp::Ceil => format!("ceil({inner_s})"),
                UnaryOp::Reciprocal => format!("(1.0 / ({inner_s}))"),
                UnaryOp::Square => format!("(({inner_s}) * ({inner_s}))"),
            }
        }
        PointwiseExpr::Binary(op, lhs, rhs) => {
            let lhs_s = render_expr_wgsl(lhs);
            let rhs_s = render_expr_wgsl(rhs);
            match op {
                BinaryOp::Add => format!("({lhs_s} + {rhs_s})"),
                BinaryOp::Sub => format!("({lhs_s} - {rhs_s})"),
                BinaryOp::Mul => format!("({lhs_s} * {rhs_s})"),
                BinaryOp::Div => format!("({lhs_s} / {rhs_s})"),
                BinaryOp::Pow => format!("pow({lhs_s}, {rhs_s})"),
                BinaryOp::Maximum => format!("max({lhs_s}, {rhs_s})"),
                BinaryOp::Minimum => format!("min({lhs_s}, {rhs_s})"),
            }
        }
        PointwiseExpr::Ternary(op, a, b, c) => {
            let a_s = render_expr_wgsl(a);
            let b_s = render_expr_wgsl(b);
            let c_s = render_expr_wgsl(c);
            match op {
                TernaryOp::Clamp => format!("clamp({a_s}, {b_s}, {c_s})"),
                TernaryOp::Fma => format!("fma({a_s}, {b_s}, {c_s})"),
            }
        }
    }
}

fn render_expr_msl(expr: &PointwiseExpr) -> String {
    match expr {
        PointwiseExpr::Arg(idx) => format!("val{idx}"),
        PointwiseExpr::ScalarConst(val) => format!("{val:?}"),
        PointwiseExpr::Unary(op, inner) => {
            let inner_s = render_expr_msl(inner);
            match op {
                UnaryOp::Abs => format!("abs({inner_s})"),
                UnaryOp::Exp => format!("exp({inner_s})"),
                UnaryOp::Log => format!("log({inner_s})"),
                UnaryOp::Sin => format!("sin({inner_s})"),
                UnaryOp::Cos => format!("cos({inner_s})"),
                UnaryOp::Sqrt => format!("sqrt({inner_s})"),
                UnaryOp::Rsqrt => format!("rsqrt({inner_s})"),
                UnaryOp::Neg => format!("-({inner_s})"),
                UnaryOp::Relu => format!("max(0.0f, {inner_s})"),
                UnaryOp::Gelu => format!(
                    "(0.5f * {inner_s} * (1.0f + tanh(0.7978845608f * ({inner_s} + 0.044715f * {inner_s} * {inner_s} * {inner_s}))))"
                ),
                UnaryOp::Silu => format!("({inner_s} / (1.0f + exp(-({inner_s}))))"),
                UnaryOp::Sigmoid => format!("(1.0f / (1.0f + exp(-({inner_s}))))"),
                UnaryOp::Tanh => format!("tanh({inner_s})"),
                UnaryOp::Floor => format!("floor({inner_s})"),
                UnaryOp::Ceil => format!("ceil({inner_s})"),
                UnaryOp::Reciprocal => format!("(1.0f / ({inner_s}))"),
                UnaryOp::Square => format!("(({inner_s}) * ({inner_s}))"),
            }
        }
        PointwiseExpr::Binary(op, lhs, rhs) => {
            let lhs_s = render_expr_msl(lhs);
            let rhs_s = render_expr_msl(rhs);
            match op {
                BinaryOp::Add => format!("({lhs_s} + {rhs_s})"),
                BinaryOp::Sub => format!("({lhs_s} - {rhs_s})"),
                BinaryOp::Mul => format!("({lhs_s} * {rhs_s})"),
                BinaryOp::Div => format!("({lhs_s} / {rhs_s})"),
                BinaryOp::Pow => format!("pow({lhs_s}, {rhs_s})"),
                BinaryOp::Maximum => format!("max({lhs_s}, {rhs_s})"),
                BinaryOp::Minimum => format!("min({lhs_s}, {rhs_s})"),
            }
        }
        PointwiseExpr::Ternary(op, a, b, c) => {
            let a_s = render_expr_msl(a);
            let b_s = render_expr_msl(b);
            let c_s = render_expr_msl(c);
            match op {
                TernaryOp::Clamp => format!("clamp({a_s}, {b_s}, {c_s})"),
                TernaryOp::Fma => format!("fma({a_s}, {b_s}, {c_s})"),
            }
        }
    }
}
