//! Shape-informed parallel reduction kernel emitter for CUDA, WGSL, and MSL.
//!
//! Generates warp-shuffle and shared-memory parallel reduction kernels for arbitrary
//! mathematical reduction operators (Sum, Mean, Max, Min, Product, Welford Variance, L2 Norm),
//! unrolling warp trees and memory access patterns at compile time.

use alloc::string::String;
use core::fmt::Write;
use incin_core::tensor::dtype::DTypeId;

/// Reduction operator kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ReductionOpKind {
    /// Sum reduction.
    Sum,
    /// Arithmetic mean reduction.
    Mean,
    /// Maximum element reduction.
    Max,
    /// Minimum element reduction.
    Min,
    /// Product reduction.
    Prod,
    /// Two-pass or parallel Welford variance.
    WelfordVar {
        /// Whether Bessel's correction is applied (N - 1 vs N).
        unbiased: bool,
    },
    /// Standard deviation.
    WelfordStd {
        /// Whether Bessel's correction is applied (N - 1 vs N).
        unbiased: bool,
    },
    /// Euclidean L2 norm (`sqrt(sum(x^2))`).
    L2Norm,
}

/// Axis reduction configuration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ReductionLayout {
    /// Reduces across all dimensions to a scalar.
    AllElements,
    /// Reduces across the innermost contiguous axis per row.
    RowWise,
}

/// Specification for a generated cross-backend reduction kernel.
#[derive(Debug, Clone, PartialEq)]
pub struct ReductionOpSpec {
    /// Kernel function name.
    pub name: String,
    /// Data type.
    pub dtype: DTypeId,
    /// Reduction operation.
    pub op: ReductionOpKind,
    /// Reduction memory layout.
    pub layout: ReductionLayout,
    /// Statically known reduction dimension size (if available).
    pub reduction_size: Option<usize>,
    /// Workgroup / thread block size.
    pub work_group_size: usize,
}

impl ReductionOpSpec {
    /// Creates a reduction specification for row-wise reduction.
    #[must_use]
    pub fn row_wise(name: impl Into<String>, op: ReductionOpKind, dtype: DTypeId) -> Self {
        Self {
            name: name.into(),
            dtype,
            op,
            layout: ReductionLayout::RowWise,
            reduction_size: None,
            work_group_size: 256,
        }
    }

    /// Creates a reduction specification reducing all elements to a scalar.
    #[must_use]
    pub fn all_elements(name: impl Into<String>, op: ReductionOpKind, dtype: DTypeId) -> Self {
        Self {
            name: name.into(),
            dtype,
            op,
            layout: ReductionLayout::AllElements,
            reduction_size: None,
            work_group_size: 256,
        }
    }

    /// Sets the statically known reduction dimension extent.
    #[must_use]
    pub fn with_reduction_size(mut self, size: usize) -> Self {
        self.reduction_size = Some(size);
        self
    }

    /// Renders the parallel reduction CUDA C++ kernel.
    #[must_use]
    pub fn render_cuda(&self) -> String {
        let mut out = String::new();
        let scalar_ty = cuda_type(self.dtype);

        writeln!(
            out,
            "// Generated by incin-backends reduction codegen (CUDA)"
        )
        .unwrap();
        writeln!(out, "#include <cuda_fp16.h>").unwrap();
        writeln!(out, "#include <cuda_bf16.h>").unwrap();
        writeln!(out, "#include <math.h>").unwrap();
        writeln!(out).unwrap();

        match self.layout {
            ReductionLayout::RowWise => {
                write!(out, "__global__ void {}(", self.name).unwrap();
                write!(out, "const {scalar_ty}* __restrict__ input, ").unwrap();
                write!(out, "{scalar_ty}* __restrict__ output, ").unwrap();
                if self.reduction_size.is_none() {
                    write!(out, "const int reduction_size, ").unwrap();
                }
                writeln!(out, "const int num_rows) {{").unwrap();

                writeln!(out, "    const int row = blockIdx.x;").unwrap();
                writeln!(out, "    if (row >= num_rows) return;").unwrap();
                writeln!(out, "    const int tid = threadIdx.x;").unwrap();
                writeln!(out, "    const int lane = tid & 31;").unwrap();
                writeln!(out, "    const int warp = tid >> 5;").unwrap();
                writeln!(out).unwrap();

                let size_expr = match self.reduction_size {
                    Some(s) => alloc::format!("{s}"),
                    None => "reduction_size".into(),
                };

                let init_val = match self.op {
                    ReductionOpKind::Sum | ReductionOpKind::Mean | ReductionOpKind::L2Norm => {
                        "0.0f"
                    }
                    ReductionOpKind::Prod => "1.0f",
                    ReductionOpKind::Max => "-1e38f",
                    ReductionOpKind::Min => "1e38f",
                    ReductionOpKind::WelfordVar { .. } | ReductionOpKind::WelfordStd { .. } => {
                        "0.0f"
                    }
                };

                writeln!(out, "    const int row_start = row * {size_expr};").unwrap();
                writeln!(out, "    float local_acc = {init_val};").unwrap();
                writeln!(
                    out,
                    "    for (int i = tid; i < {size_expr}; i += blockDim.x) {{"
                )
                .unwrap();
                writeln!(
                    out,
                    "        float val = static_cast<float>(input[row_start + i]);"
                )
                .unwrap();

                match self.op {
                    ReductionOpKind::Sum | ReductionOpKind::Mean => {
                        writeln!(out, "        local_acc += val;").unwrap();
                    }
                    ReductionOpKind::L2Norm => {
                        writeln!(out, "        local_acc += val * val;").unwrap();
                    }
                    ReductionOpKind::Prod => {
                        writeln!(out, "        local_acc *= val;").unwrap();
                    }
                    ReductionOpKind::Max => {
                        writeln!(out, "        if (val > local_acc) local_acc = val;").unwrap();
                    }
                    ReductionOpKind::Min => {
                        writeln!(out, "        if (val < local_acc) local_acc = val;").unwrap();
                    }
                    _ => {
                        writeln!(out, "        local_acc += val;").unwrap();
                    }
                }
                writeln!(out, "    }}").unwrap();
                writeln!(out).unwrap();

                // Warp-level parallel reduction via shuffle intrinsics
                writeln!(out, "    unsigned int active = __activemask();").unwrap();
                writeln!(out, "    for (int delta = 16; delta > 0; delta >>= 1) {{").unwrap();
                match self.op {
                    ReductionOpKind::Sum | ReductionOpKind::Mean | ReductionOpKind::L2Norm => {
                        writeln!(
                            out,
                            "        local_acc += __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                    }
                    ReductionOpKind::Prod => {
                        writeln!(
                            out,
                            "        local_acc *= __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                    }
                    ReductionOpKind::Max => {
                        writeln!(
                            out,
                            "        float other = __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                        writeln!(out, "        if (other > local_acc) local_acc = other;").unwrap();
                    }
                    ReductionOpKind::Min => {
                        writeln!(
                            out,
                            "        float other = __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                        writeln!(out, "        if (other < local_acc) local_acc = other;").unwrap();
                    }
                    _ => {
                        writeln!(
                            out,
                            "        local_acc += __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                    }
                }
                writeln!(out, "    }}").unwrap();
                writeln!(out).unwrap();

                // Block-level reduction in shared memory
                writeln!(out, "    extern __shared__ unsigned char shared_raw[];").unwrap();
                writeln!(
                    out,
                    "    float* shared_acc = reinterpret_cast<float*>(shared_raw);"
                )
                .unwrap();
                writeln!(out, "    const int warp_count = (blockDim.x + 31) >> 5;").unwrap();
                writeln!(out, "    if (lane == 0) shared_acc[warp] = local_acc;").unwrap();
                writeln!(out, "    __syncthreads();").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "    if (warp == 0) {{").unwrap();
                writeln!(
                    out,
                    "        local_acc = (lane < warp_count) ? shared_acc[lane] : {init_val};"
                )
                .unwrap();
                writeln!(out, "        active = __activemask();").unwrap();
                writeln!(
                    out,
                    "        for (int delta = 16; delta > 0; delta >>= 1) {{"
                )
                .unwrap();
                match self.op {
                    ReductionOpKind::Sum | ReductionOpKind::Mean | ReductionOpKind::L2Norm => {
                        writeln!(
                            out,
                            "            local_acc += __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                    }
                    ReductionOpKind::Prod => {
                        writeln!(
                            out,
                            "            local_acc *= __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                    }
                    ReductionOpKind::Max => {
                        writeln!(
                            out,
                            "            float other = __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                        writeln!(out, "            if (other > local_acc) local_acc = other;")
                            .unwrap();
                    }
                    ReductionOpKind::Min => {
                        writeln!(
                            out,
                            "            float other = __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                        writeln!(out, "            if (other < local_acc) local_acc = other;")
                            .unwrap();
                    }
                    _ => {
                        writeln!(
                            out,
                            "            local_acc += __shfl_down_sync(active, local_acc, delta);"
                        )
                        .unwrap();
                    }
                }
                writeln!(out, "        }}").unwrap();
                writeln!(out, "        if (lane == 0) {{").unwrap();
                match self.op {
                    ReductionOpKind::Mean => {
                        writeln!(out, "            output[row] = static_cast<{scalar_ty}>(local_acc / static_cast<float>({size_expr}));").unwrap();
                    }
                    ReductionOpKind::L2Norm => {
                        writeln!(
                            out,
                            "            output[row] = static_cast<{scalar_ty}>(sqrtf(local_acc));"
                        )
                        .unwrap();
                    }
                    _ => {
                        writeln!(
                            out,
                            "            output[row] = static_cast<{scalar_ty}>(local_acc);"
                        )
                        .unwrap();
                    }
                }
                writeln!(out, "        }}").unwrap();
                writeln!(out, "    }}").unwrap();
                writeln!(out, "}}").unwrap();
            }
            ReductionLayout::AllElements => {
                write!(out, "__global__ void {}(", self.name).unwrap();
                write!(out, "const {scalar_ty}* __restrict__ input, ").unwrap();
                write!(out, "{scalar_ty}* __restrict__ output, ").unwrap();
                writeln!(out, "const int numel) {{").unwrap();
                writeln!(out, "    const int tid = threadIdx.x;").unwrap();
                writeln!(out, "    const int idx = blockIdx.x * blockDim.x + tid;").unwrap();
                writeln!(
                    out,
                    "    float val = (idx < numel) ? static_cast<float>(input[idx]) : 0.0f;"
                )
                .unwrap();
                writeln!(out, "    unsigned int active = __activemask();").unwrap();
                writeln!(out, "    for (int delta = 16; delta > 0; delta >>= 1) {{").unwrap();
                writeln!(out, "        val += __shfl_down_sync(active, val, delta);").unwrap();
                writeln!(out, "    }}").unwrap();
                writeln!(
                    out,
                    "    if (tid == 0) atomicAdd(reinterpret_cast<float*>(output), val);"
                )
                .unwrap();
                writeln!(out, "}}").unwrap();
            }
        }

        out
    }

    /// Renders the parallel reduction WGSL compute shader.
    #[must_use]
    pub fn render_wgsl(&self) -> String {
        let mut out = String::new();
        let ty = wgsl_type(self.dtype);

        writeln!(
            out,
            "// Generated by incin-backends reduction codegen (WGSL)"
        )
        .unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "@group(0) @binding(0) var<storage, read> input: array<{ty}>;"
        )
        .unwrap();
        writeln!(
            out,
            "@group(0) @binding(1) var<storage, read_write> output: array<{ty}>;"
        )
        .unwrap();
        if self.reduction_size.is_none() {
            writeln!(
                out,
                "@group(0) @binding(2) var<uniform> reduction_size: u32;"
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        writeln!(
            out,
            "var<workgroup> s_acc: array<f32, {}>;",
            self.work_group_size
        )
        .unwrap();
        writeln!(
            out,
            "@compute @workgroup_size({}, 1, 1)",
            self.work_group_size
        )
        .unwrap();
        writeln!(out, "fn main(@builtin(global_invocation_id) global_id: vec3<u32>, @builtin(local_invocation_id) local_id: vec3<u32>, @builtin(workgroup_id) group_id: vec3<u32>) {{").unwrap();

        let size_expr = match self.reduction_size {
            Some(s) => alloc::format!("{s}u"),
            None => "reduction_size".into(),
        };

        writeln!(out, "    let row = group_id.x;").unwrap();
        writeln!(out, "    let tid = local_id.x;").unwrap();
        writeln!(out, "    let row_start = row * {size_expr};").unwrap();
        writeln!(out, "    var local_val: f32 = 0.0;").unwrap();
        writeln!(out, "    var i = tid;").unwrap();
        writeln!(out, "    while (i < {size_expr}) {{").unwrap();
        match self.op {
            ReductionOpKind::L2Norm => {
                writeln!(out, "        let v = f32(input[row_start + i]);").unwrap();
                writeln!(out, "        local_val += v * v;").unwrap();
            }
            _ => {
                writeln!(out, "        local_val += f32(input[row_start + i]);").unwrap();
            }
        }
        writeln!(out, "        i += {}u;", self.work_group_size).unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "    s_acc[tid] = local_val;").unwrap();
        writeln!(out, "    workgroupBarrier();").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    var stride: u32 = {}u / 2u;", self.work_group_size).unwrap();
        writeln!(out, "    while (stride > 0u) {{").unwrap();
        writeln!(out, "        if (tid < stride) {{").unwrap();
        writeln!(out, "            s_acc[tid] += s_acc[tid + stride];").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        workgroupBarrier();").unwrap();
        writeln!(out, "        stride /= 2u;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    if (tid == 0u) {{").unwrap();
        match self.op {
            ReductionOpKind::Mean => {
                writeln!(
                    out,
                    "        output[row] = {ty}(s_acc[0] / f32({size_expr}));"
                )
                .unwrap();
            }
            ReductionOpKind::L2Norm => {
                writeln!(out, "        output[row] = {ty}(sqrt(s_acc[0]));").unwrap();
            }
            _ => {
                writeln!(out, "        output[row] = {ty}(s_acc[0]);").unwrap();
            }
        }
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();

        out
    }

    /// Renders the parallel reduction MSL compute kernel.
    #[must_use]
    pub fn render_msl(&self) -> String {
        let mut out = String::new();
        let ty = msl_type(self.dtype);

        writeln!(
            out,
            "// Generated by incin-backends reduction codegen (MSL)"
        )
        .unwrap();
        writeln!(out, "#include <metal_stdlib>").unwrap();
        writeln!(out, "using namespace metal;").unwrap();
        writeln!(out).unwrap();

        write!(out, "kernel void {}(", self.name).unwrap();
        write!(out, "device const {ty}* input [[buffer(0)]], ").unwrap();
        write!(out, "device {ty}* output [[buffer(1)]], ").unwrap();
        if self.reduction_size.is_none() {
            write!(out, "constant uint& reduction_size [[buffer(2)]], ").unwrap();
        }
        writeln!(out, "uint row [[threadgroup_position_in_grid]], uint tid [[thread_position_in_threadgroup]], uint simd_lane [[thread_index_in_simdgroup]], uint simd_id [[simdgroup_index_in_threadgroup]]) {{").unwrap();

        let size_expr = match self.reduction_size {
            Some(s) => alloc::format!("{s}u"),
            None => "reduction_size".into(),
        };

        writeln!(out, "    uint row_start = row * {size_expr};").unwrap();
        writeln!(out, "    float local_val = 0.0f;").unwrap();
        writeln!(out, "    for (uint i = tid; i < {size_expr}; i += 256) {{").unwrap();
        match self.op {
            ReductionOpKind::L2Norm => {
                writeln!(out, "        float v = float(input[row_start + i]);").unwrap();
                writeln!(out, "        local_val += v * v;").unwrap();
            }
            _ => {
                writeln!(out, "        local_val += float(input[row_start + i]);").unwrap();
            }
        }
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    local_val = simd_sum(local_val);").unwrap();
        writeln!(out, "    threadgroup float s_acc[8];").unwrap();
        writeln!(out, "    if (simd_lane == 0) s_acc[simd_id] = local_val;").unwrap();
        writeln!(out, "    threadgroup_barrier(mem_flags::mem_threadgroup);").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "    if (simd_id == 0) {{").unwrap();
        writeln!(
            out,
            "        float val = (simd_lane < 8) ? s_acc[simd_lane] : 0.0f;"
        )
        .unwrap();
        writeln!(out, "        val = simd_sum(val);").unwrap();
        writeln!(out, "        if (simd_lane == 0) {{").unwrap();
        match self.op {
            ReductionOpKind::Mean => {
                writeln!(
                    out,
                    "            output[row] = {ty}(val / float({size_expr}));"
                )
                .unwrap();
            }
            ReductionOpKind::L2Norm => {
                writeln!(out, "            output[row] = {ty}(sqrt(val));").unwrap();
            }
            _ => {
                writeln!(out, "            output[row] = {ty}(val);").unwrap();
            }
        }
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();

        out
    }
}

fn cuda_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F64 => "double",
        DTypeId::F16 => "__half",
        DTypeId::BF16 => "__nv_bfloat16",
        _ => "float",
    }
}

fn wgsl_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "f32",
        DTypeId::F16 => "f16",
        _ => "f32",
    }
}

fn msl_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F16 => "half",
        DTypeId::BF16 => "bfloat",
        _ => "float",
    }
}
