//! Shape-informed vectorized kernel emitter for CUDA, WGSL, and MSL.
//!
//! Exploits compile-time tensor alignment and dimension divisibility (e.g. `numel % 4 == 0`)
//! to generate 128-bit wide memory transactions (`float4`, `__half2`, `vec4<f32>`),
//! eliminating scalar loop overhead and maximizing GPU memory bus saturation.

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec::Vec;
use core::fmt::Write;
use incin_core::tensor::dtype::DTypeId;

use super::pointwise::{BinaryOp, PointwiseExpr, TernaryOp, UnaryOp};

/// Vectorization width for memory loads, compute, and stores.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VectorWidth {
    /// 1 element per thread (scalar fallback).
    Scalar = 1,
    /// 2 elements per thread (64-bit transaction, e.g. `float2`, `half2`).
    Vec2 = 2,
    /// 4 elements per thread (128-bit transaction, e.g. `float4`, `vec4`).
    Vec4 = 4,
}

impl VectorWidth {
    /// Computes the optimal vector width from a known compile-time shape extent.
    #[must_use]
    pub const fn from_numel(numel: usize) -> Self {
        if numel.is_multiple_of(4) {
            Self::Vec4
        } else if numel.is_multiple_of(2) {
            Self::Vec2
        } else {
            Self::Scalar
        }
    }

    /// Number of elements processed per thread.
    #[must_use]
    pub const fn lanes(self) -> usize {
        self as usize
    }
}

/// Specification for a vectorized pointwise kernel.
#[derive(Debug, Clone, PartialEq)]
pub struct VectorizedOpSpec {
    /// Kernel function name.
    pub name: String,
    /// Data type for each input operand.
    pub inputs: Vec<DTypeId>,
    /// Output data type.
    pub output: DTypeId,
    /// Computation expression evaluated per scalar lane.
    pub expr: PointwiseExpr,
    /// Vector width.
    pub vector_width: VectorWidth,
    /// Workgroup/block thread count.
    pub work_group_size: usize,
}

impl VectorizedOpSpec {
    /// Creates a vectorized unary operation specification.
    pub fn unary(name: impl Into<String>, op: UnaryOp, dtype: DTypeId, width: VectorWidth) -> Self {
        Self {
            name: name.into(),
            inputs: alloc::vec![dtype],
            output: dtype,
            expr: PointwiseExpr::Unary(op, Box::new(PointwiseExpr::Arg(0))),
            vector_width: width,
            work_group_size: 256,
        }
    }

    /// Creates a vectorized binary operation specification.
    pub fn binary(
        name: impl Into<String>,
        op: BinaryOp,
        lhs_dtype: DTypeId,
        rhs_dtype: DTypeId,
        width: VectorWidth,
    ) -> Self {
        Self {
            name: name.into(),
            inputs: alloc::vec![lhs_dtype, rhs_dtype],
            output: lhs_dtype,
            expr: PointwiseExpr::Binary(
                op,
                Box::new(PointwiseExpr::Arg(0)),
                Box::new(PointwiseExpr::Arg(1)),
            ),
            vector_width: width,
            work_group_size: 256,
        }
    }

    /// Renders vectorized CUDA C++ kernel code.
    #[must_use]
    pub fn render_cuda(&self) -> String {
        let mut out = String::new();
        let lanes = self.vector_width.lanes();
        let scalar_type = cuda_scalar_type(self.output);
        let vec_type = cuda_vec_type(self.output, self.vector_width);

        writeln!(
            out,
            "// Generated by incin-backends shape-vectorized codegen (CUDA)"
        )
        .unwrap();
        writeln!(out, "#include <cuda_fp16.h>").unwrap();
        writeln!(out, "#include <cuda_bf16.h>").unwrap();
        writeln!(out).unwrap();

        write!(out, "__global__ void {}(", self.name).unwrap();
        for (i, &dt) in self.inputs.iter().enumerate() {
            let in_vec = cuda_vec_type(dt, self.vector_width);
            write!(out, "const {}* __restrict__ in{}, ", in_vec, i).unwrap();
        }
        write!(out, "{}* __restrict__ out_data, ", vec_type).unwrap();
        writeln!(out, "const int num_vectors) {{").unwrap();

        writeln!(
            out,
            "    const int vec_idx = blockIdx.x * blockDim.x + threadIdx.x;"
        )
        .unwrap();
        writeln!(out, "    if (vec_idx >= num_vectors) return;").unwrap();
        writeln!(out).unwrap();

        // Load vectorized inputs
        for (i, &dt) in self.inputs.iter().enumerate() {
            let in_vec = cuda_vec_type(dt, self.vector_width);
            writeln!(out, "    const {in_vec} in{i}_val = in{i}[vec_idx];").unwrap();
        }
        writeln!(out).unwrap();

        // Unroll expression evaluation per lane in registers
        for lane in 0..lanes {
            for (i, &dt) in self.inputs.iter().enumerate() {
                let scalar_in = cuda_scalar_type(dt);
                let component = cuda_component_access("in", i, lane, self.vector_width);
                writeln!(
                    out,
                    "    const {scalar_in} val{i}_lane{lane} = {component};"
                )
                .unwrap();
            }
            let lane_expr = render_lane_expr_cuda(&self.expr, lane);
            writeln!(
                out,
                "    const {scalar_type} res_lane{lane} = static_cast<{scalar_type}>({lane_expr});"
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        // Store vectorized result
        match self.vector_width {
            VectorWidth::Scalar => {
                writeln!(out, "    out_data[vec_idx] = res_lane0;").unwrap();
            }
            VectorWidth::Vec2 => {
                writeln!(
                    out,
                    "    out_data[vec_idx] = make_{vec_type}(res_lane0, res_lane1);"
                )
                .unwrap();
            }
            VectorWidth::Vec4 => {
                writeln!(
                    out,
                    "    out_data[vec_idx] = make_{vec_type}(res_lane0, res_lane1, res_lane2, res_lane3);"
                )
                .unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
        out
    }

    /// Renders vectorized WGSL shader source code.
    #[must_use]
    pub fn render_wgsl(&self) -> String {
        let mut out = String::new();
        let lanes = self.vector_width.lanes();
        let vec_type = wgsl_vec_type(self.output, self.vector_width);

        writeln!(
            out,
            "// Generated by incin-backends shape-vectorized codegen (WGSL)"
        )
        .unwrap();
        writeln!(out).unwrap();

        for (i, &dt) in self.inputs.iter().enumerate() {
            let in_vec = wgsl_vec_type(dt, self.vector_width);
            writeln!(
                out,
                "@group(0) @binding({}) var<storage, read> in{}: array<{}>;",
                i, i, in_vec
            )
            .unwrap();
        }
        writeln!(
            out,
            "@group(0) @binding({}) var<storage, read_write> out_data: array<{}>;",
            self.inputs.len(),
            vec_type
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "@compute @workgroup_size({}, 1, 1)",
            self.work_group_size
        )
        .unwrap();
        writeln!(
            out,
            "fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{"
        )
        .unwrap();
        writeln!(out, "    let vec_idx = global_id.x;").unwrap();
        writeln!(
            out,
            "    if (vec_idx >= arrayLength(&out_data)) {{ return; }}"
        )
        .unwrap();
        writeln!(out).unwrap();

        for (i, _) in self.inputs.iter().enumerate() {
            writeln!(out, "    let in{i}_val = in{i}[vec_idx];").unwrap();
        }

        for lane in 0..lanes {
            for (i, _) in self.inputs.iter().enumerate() {
                let comp = wgsl_component_access("in", i, lane, self.vector_width);
                writeln!(out, "    let val{i}_lane{lane} = {comp};").unwrap();
            }
            let lane_expr = render_lane_expr_wgsl(&self.expr, lane);
            writeln!(out, "    let res_lane{lane} = {lane_expr};").unwrap();
        }

        match self.vector_width {
            VectorWidth::Scalar => {
                writeln!(out, "    out_data[vec_idx] = res_lane0;").unwrap();
            }
            VectorWidth::Vec2 => {
                writeln!(out, "    out_data[vec_idx] = vec2(res_lane0, res_lane1);").unwrap();
            }
            VectorWidth::Vec4 => {
                writeln!(
                    out,
                    "    out_data[vec_idx] = vec4(res_lane0, res_lane1, res_lane2, res_lane3);"
                )
                .unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
        out
    }

    /// Renders vectorized Metal Shading Language (MSL) kernel code.
    #[must_use]
    pub fn render_msl(&self) -> String {
        let mut out = String::new();
        let lanes = self.vector_width.lanes();
        let scalar_type = msl_scalar_type(self.output);
        let vec_type = msl_vec_type(self.output, self.vector_width);

        writeln!(
            out,
            "// Generated by incin-backends shape-vectorized codegen (MSL)"
        )
        .unwrap();
        writeln!(out, "#include <metal_stdlib>").unwrap();
        writeln!(out, "using namespace metal;").unwrap();
        writeln!(out).unwrap();

        write!(out, "kernel void {}(", self.name).unwrap();
        for (i, &dt) in self.inputs.iter().enumerate() {
            let in_vec = msl_vec_type(dt, self.vector_width);
            write!(out, "device const {}* in{} [[buffer({})]], ", in_vec, i, i).unwrap();
        }
        write!(
            out,
            "device {}* out_data [[buffer({})]], ",
            vec_type,
            self.inputs.len()
        )
        .unwrap();
        write!(
            out,
            "constant uint& num_vectors [[buffer({})]], ",
            self.inputs.len() + 1
        )
        .unwrap();
        writeln!(out, "uint vec_idx [[thread_position_in_grid]]) {{").unwrap();

        writeln!(out, "    if (vec_idx >= num_vectors) return;").unwrap();
        writeln!(out).unwrap();

        for (i, &dt) in self.inputs.iter().enumerate() {
            let in_vec = msl_vec_type(dt, self.vector_width);
            writeln!(out, "    const {in_vec} in{i}_val = in{i}[vec_idx];").unwrap();
        }

        for lane in 0..lanes {
            for (i, &dt) in self.inputs.iter().enumerate() {
                let scalar_in = msl_scalar_type(dt);
                let comp = msl_component_access("in", i, lane, self.vector_width);
                writeln!(out, "    const {scalar_in} val{i}_lane{lane} = {comp};").unwrap();
            }
            let lane_expr = render_lane_expr_msl(&self.expr, lane);
            writeln!(out, "    const {scalar_type} res_lane{lane} = {lane_expr};").unwrap();
        }

        match self.vector_width {
            VectorWidth::Scalar => {
                writeln!(out, "    out_data[vec_idx] = res_lane0;").unwrap();
            }
            VectorWidth::Vec2 => {
                writeln!(
                    out,
                    "    out_data[vec_idx] = {vec_type}(res_lane0, res_lane1);"
                )
                .unwrap();
            }
            VectorWidth::Vec4 => {
                writeln!(
                    out,
                    "    out_data[vec_idx] = {vec_type}(res_lane0, res_lane1, res_lane2, res_lane3);"
                )
                .unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
        out
    }
}

fn cuda_scalar_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F64 => "double",
        DTypeId::F16 => "__half",
        DTypeId::BF16 => "__nv_bfloat16",
        DTypeId::U8 => "unsigned char",
        DTypeId::U32 => "unsigned int",
        DTypeId::I64 => "long long",
        _ => "float",
    }
}

fn cuda_vec_type(dt: DTypeId, width: VectorWidth) -> &'static str {
    match (dt, width) {
        (DTypeId::F32, VectorWidth::Scalar) => "float",
        (DTypeId::F32, VectorWidth::Vec2) => "float2",
        (DTypeId::F32, VectorWidth::Vec4) => "float4",
        (DTypeId::F64, VectorWidth::Scalar) => "double",
        (DTypeId::F64, VectorWidth::Vec2) => "double2",
        (DTypeId::F64, VectorWidth::Vec4) => "double4",
        (DTypeId::F16, VectorWidth::Scalar) => "__half",
        (DTypeId::F16, VectorWidth::Vec2) => "__half2",
        (DTypeId::F16, VectorWidth::Vec4) => "float2",
        (DTypeId::U8, VectorWidth::Scalar) => "unsigned char",
        (DTypeId::U8, VectorWidth::Vec2) => "ushort",
        (DTypeId::U8, VectorWidth::Vec4) => "uchar4",
        (DTypeId::U32, VectorWidth::Scalar) => "unsigned int",
        (DTypeId::U32, VectorWidth::Vec2) => "uint2",
        (DTypeId::U32, VectorWidth::Vec4) => "uint4",
        (DTypeId::I64, VectorWidth::Scalar) => "long long",
        (DTypeId::I64, VectorWidth::Vec2) => "longlong2",
        (DTypeId::I64, VectorWidth::Vec4) => "longlong4",
        _ => "float4",
    }
}

fn cuda_component_access(
    prefix: &str,
    input_idx: usize,
    lane: usize,
    width: VectorWidth,
) -> String {
    if width == VectorWidth::Scalar {
        alloc::format!("{prefix}{input_idx}_val")
    } else {
        let field = match lane {
            0 => "x",
            1 => "y",
            2 => "z",
            3 => "w",
            _ => "x",
        };
        alloc::format!("{prefix}{input_idx}_val.{field}")
    }
}

fn wgsl_vec_type(dt: DTypeId, width: VectorWidth) -> &'static str {
    match (dt, width) {
        (DTypeId::F32, VectorWidth::Scalar) => "f32",
        (DTypeId::F32, VectorWidth::Vec2) => "vec2<f32>",
        (DTypeId::F32, VectorWidth::Vec4) => "vec4<f32>",
        (DTypeId::F16, VectorWidth::Scalar) => "f16",
        (DTypeId::F16, VectorWidth::Vec2) => "vec2<f16>",
        (DTypeId::F16, VectorWidth::Vec4) => "vec4<f16>",
        (DTypeId::U32, VectorWidth::Scalar) => "u32",
        (DTypeId::U32, VectorWidth::Vec2) => "vec2<u32>",
        (DTypeId::U32, VectorWidth::Vec4) => "vec4<u32>",
        (DTypeId::I64, VectorWidth::Scalar) => "i32",
        (DTypeId::I64, VectorWidth::Vec2) => "vec2<i32>",
        (DTypeId::I64, VectorWidth::Vec4) => "vec4<i32>",
        _ => "vec4<f32>",
    }
}

fn wgsl_component_access(
    prefix: &str,
    input_idx: usize,
    lane: usize,
    width: VectorWidth,
) -> String {
    if width == VectorWidth::Scalar {
        alloc::format!("{prefix}{input_idx}_val")
    } else {
        let field = match lane {
            0 => "x",
            1 => "y",
            2 => "z",
            3 => "w",
            _ => "x",
        };
        alloc::format!("{prefix}{input_idx}_val.{field}")
    }
}

fn msl_scalar_type(dt: DTypeId) -> &'static str {
    match dt {
        DTypeId::F32 => "float",
        DTypeId::F64 => "float",
        DTypeId::F16 => "half",
        DTypeId::BF16 => "bfloat",
        DTypeId::U8 => "uchar",
        DTypeId::U32 => "uint",
        DTypeId::I64 => "long",
        _ => "float",
    }
}

fn msl_vec_type(dt: DTypeId, width: VectorWidth) -> &'static str {
    match (dt, width) {
        (DTypeId::F32, VectorWidth::Scalar) => "float",
        (DTypeId::F32, VectorWidth::Vec2) => "float2",
        (DTypeId::F32, VectorWidth::Vec4) => "float4",
        (DTypeId::F16, VectorWidth::Scalar) => "half",
        (DTypeId::F16, VectorWidth::Vec2) => "half2",
        (DTypeId::F16, VectorWidth::Vec4) => "half4",
        (DTypeId::U32, VectorWidth::Scalar) => "uint",
        (DTypeId::U32, VectorWidth::Vec2) => "uint2",
        (DTypeId::U32, VectorWidth::Vec4) => "uint4",
        _ => "float4",
    }
}

fn msl_component_access(prefix: &str, input_idx: usize, lane: usize, width: VectorWidth) -> String {
    if width == VectorWidth::Scalar {
        alloc::format!("{prefix}{input_idx}_val")
    } else {
        let field = match lane {
            0 => "x",
            1 => "y",
            2 => "z",
            3 => "w",
            _ => "x",
        };
        alloc::format!("{prefix}{input_idx}_val.{field}")
    }
}

fn render_lane_expr_cuda(expr: &PointwiseExpr, lane: usize) -> String {
    match expr {
        PointwiseExpr::Arg(idx) => alloc::format!("val{idx}_lane{lane}"),
        PointwiseExpr::ScalarConst(val) => alloc::format!("{val:.8}f"),
        PointwiseExpr::Unary(op, inner) => {
            let inner_s = render_lane_expr_cuda(inner, lane);
            match op {
                UnaryOp::Abs => alloc::format!("fabsf({inner_s})"),
                UnaryOp::Exp => alloc::format!("expf({inner_s})"),
                UnaryOp::Log => alloc::format!("logf({inner_s})"),
                UnaryOp::Sin => alloc::format!("sinf({inner_s})"),
                UnaryOp::Cos => alloc::format!("cosf({inner_s})"),
                UnaryOp::Sqrt => alloc::format!("sqrtf({inner_s})"),
                UnaryOp::Rsqrt => alloc::format!("rsqrtf({inner_s})"),
                UnaryOp::Neg => alloc::format!("(-{inner_s})"),
                UnaryOp::Relu => alloc::format!("fmaxf(0.0f, {inner_s})"),
                UnaryOp::Gelu => alloc::format!(
                    "0.5f * {inner_s} * (1.0f + tanhf(0.7978845608f * ({inner_s} + 0.044715f * {inner_s} * {inner_s} * {inner_s})))"
                ),
                UnaryOp::Silu => alloc::format!("({inner_s} / (1.0f + expf(-{inner_s})))"),
                UnaryOp::Sigmoid => alloc::format!("(1.0f / (1.0f + expf(-{inner_s})))"),
                UnaryOp::Tanh => alloc::format!("tanhf({inner_s})"),
                UnaryOp::Floor => alloc::format!("floorf({inner_s})"),
                UnaryOp::Ceil => alloc::format!("ceilf({inner_s})"),
                UnaryOp::Reciprocal => alloc::format!("(1.0f / ({inner_s}))"),
                UnaryOp::Square => alloc::format!("(({inner_s}) * ({inner_s}))"),
            }
        }
        PointwiseExpr::Binary(op, lhs, rhs) => {
            let lhs_s = render_lane_expr_cuda(lhs, lane);
            let rhs_s = render_lane_expr_cuda(rhs, lane);
            match op {
                BinaryOp::Add => alloc::format!("({lhs_s} + {rhs_s})"),
                BinaryOp::Sub => alloc::format!("({lhs_s} - {rhs_s})"),
                BinaryOp::Mul => alloc::format!("({lhs_s} * {rhs_s})"),
                BinaryOp::Div => alloc::format!("({lhs_s} / {rhs_s})"),
                BinaryOp::Pow => alloc::format!("powf({lhs_s}, {rhs_s})"),
                BinaryOp::Maximum => alloc::format!("fmaxf({lhs_s}, {rhs_s})"),
                BinaryOp::Minimum => alloc::format!("fminf({lhs_s}, {rhs_s})"),
            }
        }
        PointwiseExpr::Ternary(op, a, b, c) => {
            let a_s = render_lane_expr_cuda(a, lane);
            let b_s = render_lane_expr_cuda(b, lane);
            let c_s = render_lane_expr_cuda(c, lane);
            match op {
                TernaryOp::Clamp => alloc::format!("fminf(fmaxf({a_s}, {b_s}), {c_s})"),
                TernaryOp::Fma => alloc::format!("fmaf({a_s}, {b_s}, {c_s})"),
            }
        }
    }
}

fn render_lane_expr_wgsl(expr: &PointwiseExpr, lane: usize) -> String {
    match expr {
        PointwiseExpr::Arg(idx) => alloc::format!("val{idx}_lane{lane}"),
        PointwiseExpr::ScalarConst(val) => alloc::format!("{val:.8}"),
        PointwiseExpr::Unary(op, inner) => {
            let inner_s = render_lane_expr_wgsl(inner, lane);
            match op {
                UnaryOp::Abs => alloc::format!("abs({inner_s})"),
                UnaryOp::Exp => alloc::format!("exp({inner_s})"),
                UnaryOp::Log => alloc::format!("log({inner_s})"),
                UnaryOp::Sin => alloc::format!("sin({inner_s})"),
                UnaryOp::Cos => alloc::format!("cos({inner_s})"),
                UnaryOp::Sqrt => alloc::format!("sqrt({inner_s})"),
                UnaryOp::Rsqrt => alloc::format!("inverseSqrt({inner_s})"),
                UnaryOp::Neg => alloc::format!("(-{inner_s})"),
                UnaryOp::Relu => alloc::format!("max(0.0, {inner_s})"),
                UnaryOp::Gelu => alloc::format!(
                    "0.5 * {inner_s} * (1.0 + tanh(0.7978845608 * ({inner_s} + 0.044715 * {inner_s} * {inner_s} * {inner_s})))"
                ),
                UnaryOp::Silu => alloc::format!("({inner_s} / (1.0 + exp(-{inner_s})))"),
                UnaryOp::Sigmoid => alloc::format!("(1.0 / (1.0 + exp(-{inner_s})))"),
                UnaryOp::Tanh => alloc::format!("tanh({inner_s})"),
                UnaryOp::Floor => alloc::format!("floor({inner_s})"),
                UnaryOp::Ceil => alloc::format!("ceil({inner_s})"),
                UnaryOp::Reciprocal => alloc::format!("(1.0 / ({inner_s}))"),
                UnaryOp::Square => alloc::format!("(({inner_s}) * ({inner_s}))"),
            }
        }
        PointwiseExpr::Binary(op, lhs, rhs) => {
            let lhs_s = render_lane_expr_wgsl(lhs, lane);
            let rhs_s = render_lane_expr_wgsl(rhs, lane);
            match op {
                BinaryOp::Add => alloc::format!("({lhs_s} + {rhs_s})"),
                BinaryOp::Sub => alloc::format!("({lhs_s} - {rhs_s})"),
                BinaryOp::Mul => alloc::format!("({lhs_s} * {rhs_s})"),
                BinaryOp::Div => alloc::format!("({lhs_s} / {rhs_s})"),
                BinaryOp::Pow => alloc::format!("pow({lhs_s}, {rhs_s})"),
                BinaryOp::Maximum => alloc::format!("max({lhs_s}, {rhs_s})"),
                BinaryOp::Minimum => alloc::format!("min({lhs_s}, {rhs_s})"),
            }
        }
        PointwiseExpr::Ternary(op, a, b, c) => {
            let a_s = render_lane_expr_wgsl(a, lane);
            let b_s = render_lane_expr_wgsl(b, lane);
            let c_s = render_lane_expr_wgsl(c, lane);
            match op {
                TernaryOp::Clamp => alloc::format!("clamp({a_s}, {b_s}, {c_s})"),
                TernaryOp::Fma => alloc::format!("fma({a_s}, {b_s}, {c_s})"),
            }
        }
    }
}

fn render_lane_expr_msl(expr: &PointwiseExpr, lane: usize) -> String {
    match expr {
        PointwiseExpr::Arg(idx) => alloc::format!("val{idx}_lane{lane}"),
        PointwiseExpr::ScalarConst(val) => alloc::format!("{val:.8}f"),
        PointwiseExpr::Unary(op, inner) => {
            let inner_s = render_lane_expr_msl(inner, lane);
            match op {
                UnaryOp::Abs => alloc::format!("abs({inner_s})"),
                UnaryOp::Exp => alloc::format!("exp({inner_s})"),
                UnaryOp::Log => alloc::format!("log({inner_s})"),
                UnaryOp::Sin => alloc::format!("sin({inner_s})"),
                UnaryOp::Cos => alloc::format!("cos({inner_s})"),
                UnaryOp::Sqrt => alloc::format!("sqrt({inner_s})"),
                UnaryOp::Rsqrt => alloc::format!("rsqrt({inner_s})"),
                UnaryOp::Neg => alloc::format!("(-{inner_s})"),
                UnaryOp::Relu => alloc::format!("max(0.0f, {inner_s})"),
                UnaryOp::Gelu => alloc::format!(
                    "0.5f * {inner_s} * (1.0f + tanh(0.7978845608f * ({inner_s} + 0.044715f * {inner_s} * {inner_s} * {inner_s})))"
                ),
                UnaryOp::Silu => alloc::format!("({inner_s} / (1.0f + exp(-{inner_s})))"),
                UnaryOp::Sigmoid => alloc::format!("(1.0f / (1.0f + exp(-{inner_s})))"),
                UnaryOp::Tanh => alloc::format!("tanh({inner_s})"),
                UnaryOp::Floor => alloc::format!("floor({inner_s})"),
                UnaryOp::Ceil => alloc::format!("ceil({inner_s})"),
                UnaryOp::Reciprocal => alloc::format!("(1.0f / ({inner_s}))"),
                UnaryOp::Square => alloc::format!("(({inner_s}) * ({inner_s}))"),
            }
        }
        PointwiseExpr::Binary(op, lhs, rhs) => {
            let lhs_s = render_lane_expr_msl(lhs, lane);
            let rhs_s = render_lane_expr_msl(rhs, lane);
            match op {
                BinaryOp::Add => alloc::format!("({lhs_s} + {rhs_s})"),
                BinaryOp::Sub => alloc::format!("({lhs_s} - {rhs_s})"),
                BinaryOp::Mul => alloc::format!("({lhs_s} * {rhs_s})"),
                BinaryOp::Div => alloc::format!("({lhs_s} / {rhs_s})"),
                BinaryOp::Pow => alloc::format!("pow({lhs_s}, {rhs_s})"),
                BinaryOp::Maximum => alloc::format!("max({lhs_s}, {rhs_s})"),
                BinaryOp::Minimum => alloc::format!("min({lhs_s}, {rhs_s})"),
            }
        }
        PointwiseExpr::Ternary(op, a, b, c) => {
            let a_s = render_lane_expr_msl(a, lane);
            let b_s = render_lane_expr_msl(b, lane);
            let c_s = render_lane_expr_msl(c, lane);
            match op {
                TernaryOp::Clamp => alloc::format!("clamp({a_s}, {b_s}, {c_s})"),
                TernaryOp::Fma => alloc::format!("fma({a_s}, {b_s}, {c_s})"),
            }
        }
    }
}
