[package]
name = "native_training_demo"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
kindle = { path = "../..", features = ["cpu"] }
kindle-backends = { path = "../../../kindle-backends", features = ["cpu", "wgpu", ] }
kindle-telemetry = { path = "../../../kindle-telemetry" }
kindle-core = { path = "../../../kindle-core" }
anyhow = "1.0.103"

[lints]
workspace = true
