#!/usr/bin/env python3
"""Write a usage example for every operation, and keep only the ones that compile.

The reference previously showed examples harvested from the book. That made
coverage an accident of what the prose happened to demonstrate: most operations
had none, and the ones that did got a snippet written to make a different
point. These are written for the operation, from its own catalog entry -- its
entry point, arity and attributes -- so every operation can have one.

Generated examples are only worth as much as their compiler check, so the
whole set is emitted as one test file, compiled, and any example rustc rejects
is dropped rather than shipped. `--check` fails instead of dropping, which is
what CI runs: an example that stops compiling is a change to the API that the
reference has not caught up with.

    python3 tools/build-api-examples.py [--check]
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAYLOAD = ROOT / "docs/api-site-data.json"
OUTPUT = ROOT / "docs/api-examples.json"
HARNESS = ROOT / "crates/incin/tests/api_examples.rs"

# Every example builds its own operands. A helper shared by the generated file
# would read fine here and be meaningless on the page, where the reader sees the
# example alone: `let t = t23()?;` names nothing they can look up. What is shown
# is what is compiled, so the construction has to be part of it.
T23 = 'let t = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;'
A23 = 'let a = Tensor::<s![2, 3], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;'
U23 = 'let b = Tensor::<s![2, 3], B>::from_slice(&[6.0, 5.0, 4.0, 3.0, 2.0, 1.0], ())?;'

PRELUDE = """//! Generated by tools/build-api-examples.py -- do not edit by hand.
//!
//! Every example the capability reference shows for an operation lives here, so
//! that "this is how you call it" is a claim the compiler checks. An example
//! that stops compiling is an API change the reference has not caught up with,
//! and this file is where that shows up.
#![cfg(feature = "cpu")]
#![allow(unused_variables, unused_imports, clippy::type_complexity)]

use incin::prelude::*;

type B = incin_backends::cpu::CpuBackendImpl;

"""


def method(api: str | None) -> str | None:
    """The method name a caller types, from the catalog's entry point."""
    if not api:
        return None
    if api.startswith("::"):
        return api[2:]
    owner, _, name = api.partition("::")
    return name or None


def example_for(op: dict) -> str | None:
    """A worked call for this operation, or `None` if its shape needs a hand."""
    catalog = op.get("catalog") or {}
    family, kind = catalog.get("family"), catalog.get("kind")
    attrs = catalog.get("attrs")
    name = method(catalog.get("api"))
    if not name:
        return None

    if family == "UnaryFloat" and attrs == "NoAttributes":
        return f"{T23}\nlet y = t.{name}()?;"
    if family == "UnaryFloat" and attrs == "ScalarAttributes":
        return f"{T23}\nlet y = t.{name}(2.0)?;"
    if family == "BinaryBroadcast" and attrs == "NoAttributes":
        return f"{A23}\n{U23}\nlet y = a.{name}(&b)?;"
    if family == "Comparison":
        return f"{A23}\n{U23}\nlet mask = a.{name}(&b)?;"
    if family == "Logical":
        return (f"{A23}\n{U23}\n"
                f"let left = a.cmp_gt(&b)?;\nlet right = b.cmp_gt(&a)?;\n"
                f"let y = left.{name}(&right)?;")
    if family == "Reduction" and attrs == "NoAttributes":
        return f"{T23}\nlet total = t.{name}()?;"
    if family == "Reduction" and attrs == "AxisAttributes":
        return f"{T23}\nlet reduced = t.{name}(axis!(0))?;"
    if family == "IndexReduction":
        return f"{T23}\nlet positions = t.{name}(axis!(0))?;"
    if family == "Reduction" and attrs == "AxisVarianceAttributes":
        return f"{T23}\nlet spread = t.{name}(axis!(0), 1)?;"
    if family == "Transfer" and kind == "Storage" and name.endswith("vec1"):
        return f"{T23}\nlet host = t.{name}::<f32>()?;"
    if family == "Autograd":
        return f"{T23}\nlet tracked = t.{name}();"
    if family == "Loss" and name in {"mse_loss", "l1_loss"}:
        return (f"{A23.replace(chr(97)+chr(32)+chr(61), 'prediction =')}\n"
                f"{U23.replace(chr(98)+chr(32)+chr(61), 'target =')}\n"
                f"let loss = prediction.{name}(&target)?;")
    if family == "MatMul" and name == "matmul":
        return (f"{A23}\n"
                "let b = Tensor::<s![3, 2], B>::from_slice(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], ())?;\n"
                "let product = a.matmul(&b)?;")
    if family == "Creation" and kind in {"Fill", "Random"}:
        # The target API takes the shape as an argument, not a turbofish.
        return f"let t: Dense<s![2, 3], B> = Cpu.{name}(shape![2, 3])?;"
    return None


def main() -> int:
    check = "--check" in sys.argv
    payload = json.loads(PAYLOAD.read_text())

    if check:
        # Check what is committed and shown, not what a fresh draft would
        # produce: the drafts that never compiled were dropped on purpose, and
        # re-proposing them every run would make this gate cry wolf.
        if not OUTPUT.exists():
            sys.stderr.write(f"{OUTPUT.relative_to(ROOT)} is missing; run this tool without --check\n")
            return 1
        drafted = json.loads(OUTPUT.read_text(encoding="utf-8"))["examples"]
    else:
        drafted = {}
        for op in payload["operations"]:
            body = example_for(op)
            if body:
                drafted[op["name"]] = body

    def emit(selected: dict) -> None:
        parts = [PRELUDE]
        for opname, body in sorted(selected.items()):
            indented = "\n".join("    " + line for line in body.splitlines())
            parts.append(
                f"\n#[test]\nfn example_{opname}() -> Result<()> {{\n{indented}\n    Ok(())\n}}\n"
            )
        HARNESS.write_text("".join(parts), encoding="utf-8")

    def failing(selected: dict) -> set[str]:
        """Which examples rustc rejects, found by span rather than by message.

        Scraping the human-readable output for a function name does not work:
        most diagnostics never name the enclosing function, so a regex over
        stderr reports nothing while the file does not build. The JSON
        diagnostics carry line spans, and the emitted file has one example per
        function, so the line is enough to say which example is at fault.
        """
        emit(selected)
        proc = subprocess.run(
            ["cargo", "test", "--no-run", "-q", "-p", "incin", "--message-format=json",
             "--no-default-features", "--features", "cpu", "--test", "api_examples"],
            cwd=ROOT, capture_output=True, text=True,
        )
        if proc.returncode == 0:
            return set()
        text = HARNESS.read_text().splitlines()
        owner_at = {}
        current = None
        for number, line in enumerate(text, start=1):
            match = re.match(r"fn example_([a-z0-9_]+)\(", line)
            if match:
                current = match.group(1)
            owner_at[number] = current
        bad = set()
        for raw in proc.stdout.splitlines():
            try:
                message = json.loads(raw).get("message") or {}
            except json.JSONDecodeError:
                continue
            if message.get("level") != "error":
                continue
            for span in message.get("spans", []):
                if span.get("file_name", "").endswith("api_examples.rs"):
                    owner = owner_at.get(span.get("line_start", 0))
                    if owner:
                        bad.add(owner)
        if not bad and proc.returncode:
            sys.stderr.write(proc.stderr)
            raise SystemExit("api_examples.rs does not build and no example could be blamed")
        return bad

    rejected = sorted(failing(drafted))
    if rejected:
        if check:
            sys.stderr.write(f"{len(rejected)} generated examples no longer compile: "
                             + ", ".join(rejected) + "\n")
            return 1
        for name in rejected:
            drafted.pop(name, None)
        still = failing(drafted)
        if still:
            raise SystemExit("examples still failing after the drop: " + ", ".join(sorted(still)))

    # Compiling is not the bar. An example that builds and then returns an
    # error is worse than no example, because it reads as working code.
    run = subprocess.run(
        ["cargo", "test", "-q", "-p", "incin", "--no-default-features",
         "--features", "cpu", "--test", "api_examples"],
        cwd=ROOT, capture_output=True, text=True,
    )
    broken = sorted(set(re.findall(r"^\s{4}example_([a-z0-9_]+)$", run.stdout, re.M)))
    if broken:
        if check:
            sys.stderr.write(run.stdout)
            sys.stderr.write(f"\n{len(broken)} examples compile but fail at run time: "
                             + ", ".join(broken) + "\n")
            return 1
        for name in broken:
            drafted.pop(name, None)
        emit(drafted)
        again = subprocess.run(
            ["cargo", "test", "-q", "-p", "incin", "--no-default-features",
             "--features", "cpu", "--test", "api_examples"],
            cwd=ROOT, capture_output=True, text=True,
        )
        if again.returncode:
            sys.stderr.write(again.stdout)
            raise SystemExit("examples still failing at run time after the drop")
        rejected = sorted(set(rejected) | set(broken))

    OUTPUT.write_text(json.dumps({"examples": drafted}, indent=1) + "\n", encoding="utf-8")
    total = len(payload["operations"])
    print(f"{len(drafted)} of {total} operations have a compiled example"
          + (f"; dropped {len(rejected)} that rustc rejected" if rejected else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
